package com.aii.crm.agr.core.persistence.bo;

import java.util.Date;

public class AgrTemplateH {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.AGREEMENT_TEMPLATE_H_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long agreementTemplateHId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.AGR_VERSION_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long agrVersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.AGREEMENT_TEMPLATE_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long agreementTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.AGR_TYPE_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long agrTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.TEMPLATE_CODE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private String templateCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.TEMPLATE_STATUS
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private String templateStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.STATUS_TIME
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Date statusTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.UP_TEMPLATE_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long upTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.AGREEMENT_TEMPLATE_NAME
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private String agreementTemplateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.AGR_LEVEL_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long agrLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.AGR_DOC_URL
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private String agrDocUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.OPERATOR_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.ORGANIZATION_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.CREATE_DATE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.CREATE_OP_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long createOpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.CREATE_ORG_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long createOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.OP_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.ORG_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.DONE_DATE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.DONE_CODE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private String doneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.STATE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.IS_ADDENDUM
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long isAddendum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.LANGUAGE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agr_template_h.OFFER_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    private Long offerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.AGREEMENT_TEMPLATE_H_ID
     *
     * @return the value of agr_template_h.AGREEMENT_TEMPLATE_H_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getAgreementTemplateHId() {
        return agreementTemplateHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.AGREEMENT_TEMPLATE_H_ID
     *
     * @param agreementTemplateHId the value for agr_template_h.AGREEMENT_TEMPLATE_H_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setAgreementTemplateHId(Long agreementTemplateHId) {
        this.agreementTemplateHId = agreementTemplateHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.AGR_VERSION_ID
     *
     * @return the value of agr_template_h.AGR_VERSION_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getAgrVersionId() {
        return agrVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.AGR_VERSION_ID
     *
     * @param agrVersionId the value for agr_template_h.AGR_VERSION_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setAgrVersionId(Long agrVersionId) {
        this.agrVersionId = agrVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.AGREEMENT_TEMPLATE_ID
     *
     * @return the value of agr_template_h.AGREEMENT_TEMPLATE_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getAgreementTemplateId() {
        return agreementTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.AGREEMENT_TEMPLATE_ID
     *
     * @param agreementTemplateId the value for agr_template_h.AGREEMENT_TEMPLATE_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setAgreementTemplateId(Long agreementTemplateId) {
        this.agreementTemplateId = agreementTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.AGR_TYPE_ID
     *
     * @return the value of agr_template_h.AGR_TYPE_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getAgrTypeId() {
        return agrTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.AGR_TYPE_ID
     *
     * @param agrTypeId the value for agr_template_h.AGR_TYPE_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setAgrTypeId(Long agrTypeId) {
        this.agrTypeId = agrTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.TEMPLATE_CODE
     *
     * @return the value of agr_template_h.TEMPLATE_CODE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public String getTemplateCode() {
        return templateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.TEMPLATE_CODE
     *
     * @param templateCode the value for agr_template_h.TEMPLATE_CODE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode == null ? null : templateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.TEMPLATE_STATUS
     *
     * @return the value of agr_template_h.TEMPLATE_STATUS
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public String getTemplateStatus() {
        return templateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.TEMPLATE_STATUS
     *
     * @param templateStatus the value for agr_template_h.TEMPLATE_STATUS
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setTemplateStatus(String templateStatus) {
        this.templateStatus = templateStatus == null ? null : templateStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.STATUS_TIME
     *
     * @return the value of agr_template_h.STATUS_TIME
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Date getStatusTime() {
        return statusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.STATUS_TIME
     *
     * @param statusTime the value for agr_template_h.STATUS_TIME
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setStatusTime(Date statusTime) {
        this.statusTime = statusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.UP_TEMPLATE_ID
     *
     * @return the value of agr_template_h.UP_TEMPLATE_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getUpTemplateId() {
        return upTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.UP_TEMPLATE_ID
     *
     * @param upTemplateId the value for agr_template_h.UP_TEMPLATE_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setUpTemplateId(Long upTemplateId) {
        this.upTemplateId = upTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.AGREEMENT_TEMPLATE_NAME
     *
     * @return the value of agr_template_h.AGREEMENT_TEMPLATE_NAME
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public String getAgreementTemplateName() {
        return agreementTemplateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.AGREEMENT_TEMPLATE_NAME
     *
     * @param agreementTemplateName the value for agr_template_h.AGREEMENT_TEMPLATE_NAME
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setAgreementTemplateName(String agreementTemplateName) {
        this.agreementTemplateName = agreementTemplateName == null ? null : agreementTemplateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.AGR_LEVEL_ID
     *
     * @return the value of agr_template_h.AGR_LEVEL_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getAgrLevelId() {
        return agrLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.AGR_LEVEL_ID
     *
     * @param agrLevelId the value for agr_template_h.AGR_LEVEL_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setAgrLevelId(Long agrLevelId) {
        this.agrLevelId = agrLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.AGR_DOC_URL
     *
     * @return the value of agr_template_h.AGR_DOC_URL
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public String getAgrDocUrl() {
        return agrDocUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.AGR_DOC_URL
     *
     * @param agrDocUrl the value for agr_template_h.AGR_DOC_URL
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setAgrDocUrl(String agrDocUrl) {
        this.agrDocUrl = agrDocUrl == null ? null : agrDocUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.OPERATOR_ID
     *
     * @return the value of agr_template_h.OPERATOR_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.OPERATOR_ID
     *
     * @param operatorId the value for agr_template_h.OPERATOR_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.ORGANIZATION_ID
     *
     * @return the value of agr_template_h.ORGANIZATION_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.ORGANIZATION_ID
     *
     * @param organizationId the value for agr_template_h.ORGANIZATION_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.CREATE_DATE
     *
     * @return the value of agr_template_h.CREATE_DATE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.CREATE_DATE
     *
     * @param createDate the value for agr_template_h.CREATE_DATE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.CREATE_OP_ID
     *
     * @return the value of agr_template_h.CREATE_OP_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getCreateOpId() {
        return createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.CREATE_OP_ID
     *
     * @param createOpId the value for agr_template_h.CREATE_OP_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setCreateOpId(Long createOpId) {
        this.createOpId = createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.CREATE_ORG_ID
     *
     * @return the value of agr_template_h.CREATE_ORG_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getCreateOrgId() {
        return createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.CREATE_ORG_ID
     *
     * @param createOrgId the value for agr_template_h.CREATE_ORG_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setCreateOrgId(Long createOrgId) {
        this.createOrgId = createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.OP_ID
     *
     * @return the value of agr_template_h.OP_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.OP_ID
     *
     * @param opId the value for agr_template_h.OP_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.ORG_ID
     *
     * @return the value of agr_template_h.ORG_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.ORG_ID
     *
     * @param orgId the value for agr_template_h.ORG_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.DONE_DATE
     *
     * @return the value of agr_template_h.DONE_DATE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.DONE_DATE
     *
     * @param doneDate the value for agr_template_h.DONE_DATE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.DONE_CODE
     *
     * @return the value of agr_template_h.DONE_CODE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public String getDoneCode() {
        return doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.DONE_CODE
     *
     * @param doneCode the value for agr_template_h.DONE_CODE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setDoneCode(String doneCode) {
        this.doneCode = doneCode == null ? null : doneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.STATE
     *
     * @return the value of agr_template_h.STATE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.STATE
     *
     * @param state the value for agr_template_h.STATE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.IS_ADDENDUM
     *
     * @return the value of agr_template_h.IS_ADDENDUM
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getIsAddendum() {
        return isAddendum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.IS_ADDENDUM
     *
     * @param isAddendum the value for agr_template_h.IS_ADDENDUM
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setIsAddendum(Long isAddendum) {
        this.isAddendum = isAddendum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.LANGUAGE
     *
     * @return the value of agr_template_h.LANGUAGE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.LANGUAGE
     *
     * @param language the value for agr_template_h.LANGUAGE
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agr_template_h.OFFER_ID
     *
     * @return the value of agr_template_h.OFFER_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public Long getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agr_template_h.OFFER_ID
     *
     * @param offerId the value for agr_template_h.OFFER_ID
     *
     * @mbg.generated Sat May 18 10:21:01 CST 2019
     */
    public void setOfferId(Long offerId) {
        this.offerId = offerId;
    }
}