package com.aii.crm.ci.web.persistence.bo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CiInteractionAttrValueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public CiInteractionAttrValueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInteractionAttrValueIdIsNull() {
            addCriterion("INTERACTION_ATTR_VALUE_ID is null");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdIsNotNull() {
            addCriterion("INTERACTION_ATTR_VALUE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdEqualTo(Long value) {
            addCriterion("INTERACTION_ATTR_VALUE_ID =", value, "interactionAttrValueId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdNotEqualTo(Long value) {
            addCriterion("INTERACTION_ATTR_VALUE_ID <>", value, "interactionAttrValueId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdGreaterThan(Long value) {
            addCriterion("INTERACTION_ATTR_VALUE_ID >", value, "interactionAttrValueId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdGreaterThanOrEqualTo(Long value) {
            addCriterion("INTERACTION_ATTR_VALUE_ID >=", value, "interactionAttrValueId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdLessThan(Long value) {
            addCriterion("INTERACTION_ATTR_VALUE_ID <", value, "interactionAttrValueId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdLessThanOrEqualTo(Long value) {
            addCriterion("INTERACTION_ATTR_VALUE_ID <=", value, "interactionAttrValueId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdIn(List<Long> values) {
            addCriterion("INTERACTION_ATTR_VALUE_ID in", values, "interactionAttrValueId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdNotIn(List<Long> values) {
            addCriterion("INTERACTION_ATTR_VALUE_ID not in", values, "interactionAttrValueId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdBetween(Long value1, Long value2) {
            addCriterion("INTERACTION_ATTR_VALUE_ID between", value1, value2, "interactionAttrValueId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrValueIdNotBetween(Long value1, Long value2) {
            addCriterion("INTERACTION_ATTR_VALUE_ID not between", value1, value2, "interactionAttrValueId");
            return (Criteria) this;
        }

        public Criteria andInteractionIdIsNull() {
            addCriterion("INTERACTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andInteractionIdIsNotNull() {
            addCriterion("INTERACTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInteractionIdEqualTo(Long value) {
            addCriterion("INTERACTION_ID =", value, "interactionId");
            return (Criteria) this;
        }

        public Criteria andInteractionIdNotEqualTo(Long value) {
            addCriterion("INTERACTION_ID <>", value, "interactionId");
            return (Criteria) this;
        }

        public Criteria andInteractionIdGreaterThan(Long value) {
            addCriterion("INTERACTION_ID >", value, "interactionId");
            return (Criteria) this;
        }

        public Criteria andInteractionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("INTERACTION_ID >=", value, "interactionId");
            return (Criteria) this;
        }

        public Criteria andInteractionIdLessThan(Long value) {
            addCriterion("INTERACTION_ID <", value, "interactionId");
            return (Criteria) this;
        }

        public Criteria andInteractionIdLessThanOrEqualTo(Long value) {
            addCriterion("INTERACTION_ID <=", value, "interactionId");
            return (Criteria) this;
        }

        public Criteria andInteractionIdIn(List<Long> values) {
            addCriterion("INTERACTION_ID in", values, "interactionId");
            return (Criteria) this;
        }

        public Criteria andInteractionIdNotIn(List<Long> values) {
            addCriterion("INTERACTION_ID not in", values, "interactionId");
            return (Criteria) this;
        }

        public Criteria andInteractionIdBetween(Long value1, Long value2) {
            addCriterion("INTERACTION_ID between", value1, value2, "interactionId");
            return (Criteria) this;
        }

        public Criteria andInteractionIdNotBetween(Long value1, Long value2) {
            addCriterion("INTERACTION_ID not between", value1, value2, "interactionId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdIsNull() {
            addCriterion("INTERACTION_ATTR_ID is null");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdIsNotNull() {
            addCriterion("INTERACTION_ATTR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdEqualTo(Long value) {
            addCriterion("INTERACTION_ATTR_ID =", value, "interactionAttrId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdNotEqualTo(Long value) {
            addCriterion("INTERACTION_ATTR_ID <>", value, "interactionAttrId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdGreaterThan(Long value) {
            addCriterion("INTERACTION_ATTR_ID >", value, "interactionAttrId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("INTERACTION_ATTR_ID >=", value, "interactionAttrId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdLessThan(Long value) {
            addCriterion("INTERACTION_ATTR_ID <", value, "interactionAttrId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdLessThanOrEqualTo(Long value) {
            addCriterion("INTERACTION_ATTR_ID <=", value, "interactionAttrId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdIn(List<Long> values) {
            addCriterion("INTERACTION_ATTR_ID in", values, "interactionAttrId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdNotIn(List<Long> values) {
            addCriterion("INTERACTION_ATTR_ID not in", values, "interactionAttrId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdBetween(Long value1, Long value2) {
            addCriterion("INTERACTION_ATTR_ID between", value1, value2, "interactionAttrId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrIdNotBetween(Long value1, Long value2) {
            addCriterion("INTERACTION_ATTR_ID not between", value1, value2, "interactionAttrId");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeIsNull() {
            addCriterion("INTERACTION_ATTR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeIsNotNull() {
            addCriterion("INTERACTION_ATTR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeEqualTo(String value) {
            addCriterion("INTERACTION_ATTR_CODE =", value, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeNotEqualTo(String value) {
            addCriterion("INTERACTION_ATTR_CODE <>", value, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeGreaterThan(String value) {
            addCriterion("INTERACTION_ATTR_CODE >", value, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("INTERACTION_ATTR_CODE >=", value, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeLessThan(String value) {
            addCriterion("INTERACTION_ATTR_CODE <", value, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeLessThanOrEqualTo(String value) {
            addCriterion("INTERACTION_ATTR_CODE <=", value, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeLike(String value) {
            addCriterion("INTERACTION_ATTR_CODE like", value, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeNotLike(String value) {
            addCriterion("INTERACTION_ATTR_CODE not like", value, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeIn(List<String> values) {
            addCriterion("INTERACTION_ATTR_CODE in", values, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeNotIn(List<String> values) {
            addCriterion("INTERACTION_ATTR_CODE not in", values, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeBetween(String value1, String value2) {
            addCriterion("INTERACTION_ATTR_CODE between", value1, value2, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrCodeNotBetween(String value1, String value2) {
            addCriterion("INTERACTION_ATTR_CODE not between", value1, value2, "interactionAttrCode");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueIsNull() {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueIsNotNull() {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueEqualTo(String value) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE =", value, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueNotEqualTo(String value) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE <>", value, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueGreaterThan(String value) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE >", value, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueGreaterThanOrEqualTo(String value) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE >=", value, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueLessThan(String value) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE <", value, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueLessThanOrEqualTo(String value) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE <=", value, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueLike(String value) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE like", value, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueNotLike(String value) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE not like", value, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueIn(List<String> values) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE in", values, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueNotIn(List<String> values) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE not in", values, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueBetween(String value1, String value2) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE between", value1, value2, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andInteractionAttrAttrValueNotBetween(String value1, String value2) {
            addCriterion("INTERACTION_ATTR_ATTR_VALUE not between", value1, value2, "interactionAttrAttrValue");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNull() {
            addCriterion("CUST_ID is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("CUST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(Long value) {
            addCriterion("CUST_ID =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(Long value) {
            addCriterion("CUST_ID <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(Long value) {
            addCriterion("CUST_ID >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CUST_ID >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(Long value) {
            addCriterion("CUST_ID <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(Long value) {
            addCriterion("CUST_ID <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<Long> values) {
            addCriterion("CUST_ID in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<Long> values) {
            addCriterion("CUST_ID not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(Long value1, Long value2) {
            addCriterion("CUST_ID between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(Long value1, Long value2) {
            addCriterion("CUST_ID not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("TENANT_ID is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("TENANT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(String value) {
            addCriterion("TENANT_ID =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(String value) {
            addCriterion("TENANT_ID <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(String value) {
            addCriterion("TENANT_ID >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
            addCriterion("TENANT_ID >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(String value) {
            addCriterion("TENANT_ID <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(String value) {
            addCriterion("TENANT_ID <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLike(String value) {
            addCriterion("TENANT_ID like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotLike(String value) {
            addCriterion("TENANT_ID not like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<String> values) {
            addCriterion("TENANT_ID in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<String> values) {
            addCriterion("TENANT_ID not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(String value1, String value2) {
            addCriterion("TENANT_ID between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(String value1, String value2) {
            addCriterion("TENANT_ID not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeIsNull() {
            addCriterion("INTERACTION_TIME is null");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeIsNotNull() {
            addCriterion("INTERACTION_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeEqualTo(Date value) {
            addCriterion("INTERACTION_TIME =", value, "interactionTime");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeNotEqualTo(Date value) {
            addCriterion("INTERACTION_TIME <>", value, "interactionTime");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeGreaterThan(Date value) {
            addCriterion("INTERACTION_TIME >", value, "interactionTime");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("INTERACTION_TIME >=", value, "interactionTime");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeLessThan(Date value) {
            addCriterion("INTERACTION_TIME <", value, "interactionTime");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeLessThanOrEqualTo(Date value) {
            addCriterion("INTERACTION_TIME <=", value, "interactionTime");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeIn(List<Date> values) {
            addCriterion("INTERACTION_TIME in", values, "interactionTime");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeNotIn(List<Date> values) {
            addCriterion("INTERACTION_TIME not in", values, "interactionTime");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeBetween(Date value1, Date value2) {
            addCriterion("INTERACTION_TIME between", value1, value2, "interactionTime");
            return (Criteria) this;
        }

        public Criteria andInteractionTimeNotBetween(Date value1, Date value2) {
            addCriterion("INTERACTION_TIME not between", value1, value2, "interactionTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated do_not_delete_during_merge Tue May 21 15:48:16 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ci_interaction_attr_value
     *
     * @mbg.generated Tue May 21 15:48:16 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}