package com.aii.crm.agr.web.persistence.mapper;

import com.aii.crm.agr.web.persistence.bo.AgrAgreementH;
import com.aii.crm.agr.web.persistence.bo.AgrAgreementHExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgrAgreementHMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    long countByExample(AgrAgreementHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    int deleteByExample(AgrAgreementHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    int deleteByPrimaryKey(Long agreementHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    int insert(AgrAgreementH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    int insertSelective(AgrAgreementH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    List<AgrAgreementH> selectByExample(AgrAgreementHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    AgrAgreementH selectByPrimaryKey(Long agreementHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") AgrAgreementH record, @Param("example") AgrAgreementHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    int updateByExample(@Param("record") AgrAgreementH record, @Param("example") AgrAgreementHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    int updateByPrimaryKeySelective(AgrAgreementH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agr_agreement_h
     *
     * @mbg.generated Sat May 18 13:03:42 CST 2019
     */
    int updateByPrimaryKey(AgrAgreementH record);
}