package com.aii.crm.cm.web.dto.res;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import lombok.Data;

@Data
public class IndividualCustomerResDto implements Serializable {
	private List<ContactInfoResDto> contactInfos;
	private Long addressRelaId;
	private String  streetName;
	private String houseNo;
	private String doorNo;
	private String zipCode;
	private String mainDoor;
	private String floor;
	private String city;
	private String county;
	private String kvhx;
	private String municipality;
	private String addrDesc;
	private Long addressId;
	private Long loginId;
	private String certExpiryDate;
	private Integer prefLang;
	private Integer siteLang;
	private Integer premissionMarketing;
	private Long segment;
	private Long custId;
	private Long partyId;
	private String custServiceId;
	private String firstName;
	private String middleName;
	private String lastName;
	private String custName;
	private String shortName;
	private String englishName;
	private Integer custStatus;
	private String custPassword;
	private String custZipcode;
	private String custAddress;
	private Long custServiceLevel;
	private Integer custCertType;
	private String custCertCode;
	private String custCertAddress;
	private String custCertEffdate;
	private String custCertExpire;
	private String indivCustType;
	private String custLanguage;
	private Long isVip;
	private String creditLevel;
	private Long creditValue;
	private Long isRevisable;
	private Integer gender;
	private Long lunar;
	private String birthday;
	private String birthPlace;
	private Integer occupation;
	private Long realNameFlag;
	private Long disturbFlag;
	private String religion;
	private Long nationalType;
	private String familyInfo;
	private Long politicsFace;
	private Long educationLevel;
	private Long incomeLevel;
	private String characterDesc;
	private String jobPosition;
	private String jobCompany;
	private Long marryStatus;
	private Long physiologicalState;
	private Integer anonymousFlag;
	private String nationality;
	private String provinceId;
	private String cityId;
	private String countyId;
	private String state;
	private String createDate;
	private String effectiveDate;
	private String expireDate;
	private String remarks;
	private Long contactProtection;
	private Long updateFlag;
	private Date doneDate;
	private Long opId;
	private Long orgId;
	private String regionId;
	private Long doneCode;

}
