/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 5.6.36-82.0-log : Database - cs
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`cs` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `cs`;

/*Table structure for table `bs_remind_cfg` */

DROP TABLE IF EXISTS `bs_remind_cfg`;

CREATE TABLE `bs_remind_cfg` (
  `REMINDCON_ID` bigint(11) NOT NULL,
  `REMIND_NAME` varchar(50) DEFAULT NULL,
  `OPERATE_MAPPING` varchar(2000) DEFAULT NULL,
  `REMIND_TEMPLATE` varchar(2000) DEFAULT NULL,
  `REMIND_TYPE` varchar(50) DEFAULT NULL,
  `REMIND_OBJECT_ID` varchar(20) DEFAULT NULL,
  `MESSAGE_CLASS` varchar(128) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `ORG_ID` bigint(11) DEFAULT NULL,
  `OP_ID` bigint(11) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(11) DEFAULT NULL,
  PRIMARY KEY (`REMINDCON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `bs_remind_obj_cont` */

DROP TABLE IF EXISTS `bs_remind_obj_cont`;

CREATE TABLE `bs_remind_obj_cont` (
  `CONTACT_ID` bigint(11) NOT NULL,
  `OBJECT_ID` bigint(11) DEFAULT NULL,
  `CONTACT_NAME` varchar(150) DEFAULT NULL,
  `CONTACT_TYPE` varchar(50) DEFAULT NULL,
  `CONTACT_VALUE` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`CONTACT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `bs_remind_object` */

DROP TABLE IF EXISTS `bs_remind_object`;

CREATE TABLE `bs_remind_object` (
  `OBJECT_ID` bigint(11) NOT NULL,
  `OBJECT_NAME` varchar(250) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `ORG_ID` bigint(11) DEFAULT NULL,
  `OP_ID` bigint(11) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(11) DEFAULT NULL,
  PRIMARY KEY (`OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `cfg_static_data` */

DROP TABLE IF EXISTS `cfg_static_data`;

CREATE TABLE `cfg_static_data` (
  `CODE_TYPE` varchar(255) NOT NULL,
  `CODE_VALUE` varchar(255) NOT NULL,
  `CODE_NAME` varchar(255) NOT NULL,
  `CODE_DESC` varchar(255) DEFAULT NULL,
  `CODE_TYPE_ALIAS` varchar(255) DEFAULT NULL,
  `SORT_ID` decimal(3,0) DEFAULT NULL,
  `STATE` char(1) NOT NULL,
  `EXTERN_CODE_TYPE` varchar(2000) DEFAULT NULL,
  `ALLOW_ADMIN` char(1) NOT NULL,
  `RES_KEY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CODE_TYPE`,`CODE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_handling_log` */

DROP TABLE IF EXISTS `sr_handling_log`;

CREATE TABLE `sr_handling_log` (
  `SR_HAND_LOG_ID` bigint(12) NOT NULL,
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  `NODE_ID` varchar(100) DEFAULT NULL,
  `WORK_ITEM_ID` bigint(12) DEFAULT NULL,
  `SEQUENCE_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NAME` varchar(200) DEFAULT NULL,
  `HANDLING_TIME` datetime DEFAULT NULL,
  `ACTION_REASION` varchar(200) DEFAULT NULL,
  `OPERATE_DESC` varchar(4000) DEFAULT NULL,
  `REMARK` varchar(4000) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `TEMPLET_ID` varchar(100) DEFAULT NULL,
  `PROCESS_ID` bigint(12) DEFAULT NULL,
  `OPERATE_TYPE` bigint(12) DEFAULT NULL,
  PRIMARY KEY (`SR_HAND_LOG_ID`),
  KEY `IDX_SR_HANDLING_LOG_1` (`PROCESS_ID`),
  KEY `IDX_SR_HANDLING_LOG_2` (`SERVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_handling_log_201808` */

DROP TABLE IF EXISTS `sr_handling_log_201808`;

CREATE TABLE `sr_handling_log_201808` (
  `SR_HAND_LOG_ID` bigint(12) NOT NULL,
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  `NODE_ID` varchar(100) DEFAULT NULL,
  `WORK_ITEM_ID` bigint(12) DEFAULT NULL,
  `SEQUENCE_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NAME` varchar(200) DEFAULT NULL,
  `HANDLING_TIME` datetime DEFAULT NULL,
  `ACTION_REASION` varchar(200) DEFAULT NULL,
  `OPERATE_DESC` varchar(4000) DEFAULT NULL,
  `REMARK` varchar(4000) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `TEMPLET_ID` varchar(100) DEFAULT NULL,
  `PROCESS_ID` bigint(12) DEFAULT NULL,
  `OPERATE_TYPE` bigint(12) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_handling_log_201809` */

DROP TABLE IF EXISTS `sr_handling_log_201809`;

CREATE TABLE `sr_handling_log_201809` (
  `SR_HAND_LOG_ID` bigint(12) NOT NULL,
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  `NODE_ID` varchar(100) DEFAULT NULL,
  `WORK_ITEM_ID` bigint(12) DEFAULT NULL,
  `SEQUENCE_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NAME` varchar(200) DEFAULT NULL,
  `HANDLING_TIME` datetime DEFAULT NULL,
  `ACTION_REASION` varchar(200) DEFAULT NULL,
  `OPERATE_DESC` varchar(4000) DEFAULT NULL,
  `REMARK` varchar(4000) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `TEMPLET_ID` varchar(100) DEFAULT NULL,
  `PROCESS_ID` bigint(12) DEFAULT NULL,
  `OPERATE_TYPE` bigint(12) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_handling_log_201810` */

DROP TABLE IF EXISTS `sr_handling_log_201810`;

CREATE TABLE `sr_handling_log_201810` (
  `SR_HAND_LOG_ID` bigint(12) NOT NULL,
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  `NODE_ID` varchar(100) DEFAULT NULL,
  `WORK_ITEM_ID` bigint(12) DEFAULT NULL,
  `SEQUENCE_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NAME` varchar(200) DEFAULT NULL,
  `HANDLING_TIME` datetime DEFAULT NULL,
  `ACTION_REASION` varchar(200) DEFAULT NULL,
  `OPERATE_DESC` varchar(4000) DEFAULT NULL,
  `REMARK` varchar(4000) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `TEMPLET_ID` varchar(100) DEFAULT NULL,
  `PROCESS_ID` bigint(12) DEFAULT NULL,
  `OPERATE_TYPE` bigint(12) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_handling_log_201811` */

DROP TABLE IF EXISTS `sr_handling_log_201811`;

CREATE TABLE `sr_handling_log_201811` (
  `SR_HAND_LOG_ID` bigint(12) NOT NULL,
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  `NODE_ID` varchar(100) DEFAULT NULL,
  `WORK_ITEM_ID` bigint(12) DEFAULT NULL,
  `SEQUENCE_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NAME` varchar(200) DEFAULT NULL,
  `HANDLING_TIME` datetime DEFAULT NULL,
  `ACTION_REASION` varchar(200) DEFAULT NULL,
  `OPERATE_DESC` varchar(4000) DEFAULT NULL,
  `REMARK` varchar(4000) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `TEMPLET_ID` varchar(100) DEFAULT NULL,
  `PROCESS_ID` bigint(12) DEFAULT NULL,
  `OPERATE_TYPE` bigint(12) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_handling_log_201812` */

DROP TABLE IF EXISTS `sr_handling_log_201812`;

CREATE TABLE `sr_handling_log_201812` (
  `SR_HAND_LOG_ID` bigint(12) NOT NULL,
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  `NODE_ID` varchar(100) DEFAULT NULL,
  `WORK_ITEM_ID` bigint(12) DEFAULT NULL,
  `SEQUENCE_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NAME` varchar(200) DEFAULT NULL,
  `HANDLING_TIME` datetime DEFAULT NULL,
  `ACTION_REASION` varchar(200) DEFAULT NULL,
  `OPERATE_DESC` varchar(4000) DEFAULT NULL,
  `REMARK` varchar(4000) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `TEMPLET_ID` varchar(100) DEFAULT NULL,
  `PROCESS_ID` bigint(12) DEFAULT NULL,
  `OPERATE_TYPE` bigint(12) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_handling_log_201901` */

DROP TABLE IF EXISTS `sr_handling_log_201901`;

CREATE TABLE `sr_handling_log_201901` (
  `SR_HAND_LOG_ID` bigint(12) NOT NULL,
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  `NODE_ID` varchar(100) DEFAULT NULL,
  `WORK_ITEM_ID` bigint(12) DEFAULT NULL,
  `SEQUENCE_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NO` varchar(20) DEFAULT NULL,
  `HANDLING_STAFF_NAME` varchar(200) DEFAULT NULL,
  `HANDLING_TIME` datetime DEFAULT NULL,
  `ACTION_REASION` varchar(200) DEFAULT NULL,
  `OPERATE_DESC` varchar(4000) DEFAULT NULL,
  `REMARK` varchar(4000) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `TEMPLET_ID` varchar(100) DEFAULT NULL,
  `PROCESS_ID` bigint(12) DEFAULT NULL,
  `OPERATE_TYPE` bigint(12) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_org_decision` */

DROP TABLE IF EXISTS `sr_org_decision`;

CREATE TABLE `sr_org_decision` (
  `ID` bigint(20) NOT NULL,
  `WF_TEMPLET_ID` varchar(100) DEFAULT NULL COMMENT '模板id',
  `FROMNODE` varchar(64) DEFAULT NULL COMMENT '从那个节点',
  `TONODE` varchar(64) DEFAULT NULL COMMENT '到该节点',
  `FROMPARTICIPANT` varchar(60) DEFAULT NULL COMMENT '有那个组织发起',
  `TOPARTICIPANT` varchar(60) DEFAULT NULL COMMENT '到那个组织发起',
  `SRTYPEID` varchar(60) DEFAULT NULL COMMENT '服务类型id',
  `DECISIONTYPE` varchar(2) DEFAULT NULL COMMENT '1，指派组织；2、指派角色；3、指派员工',
  `DECISION_OBJ` varchar(64) DEFAULT NULL COMMENT '指派对象；组织id,staffId,roleId',
  `CITYID` varchar(60) DEFAULT NULL,
  `EXT1` varchar(60) DEFAULT NULL,
  `EXT2` varchar(60) DEFAULT NULL,
  `EXT3` varchar(60) DEFAULT NULL,
  `EXT4` varchar(150) DEFAULT NULL,
  `EXT5` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_page_info` */

DROP TABLE IF EXISTS `sr_page_info`;

CREATE TABLE `sr_page_info` (
  `PAGE_ID` bigint(12) NOT NULL,
  `PAGE_CODE` varchar(100) DEFAULT NULL,
  `PAGE_NAME` varchar(128) DEFAULT NULL,
  `CATEGORY` bigint(2) DEFAULT NULL,
  `PAGE_URL` varchar(512) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  PRIMARY KEY (`PAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_prcs_tm_lmt` */

DROP TABLE IF EXISTS `sr_prcs_tm_lmt`;

CREATE TABLE `sr_prcs_tm_lmt` (
  `TL_NO` bigint(11) NOT NULL,
  `UNIT_CODE` bigint(11) DEFAULT NULL,
  `AL_VALUE` bigint(11) DEFAULT NULL,
  `TL_VALUE` bigint(11) DEFAULT NULL,
  `TL_NAME` varchar(128) DEFAULT NULL,
  `START_STATUS` varchar(30) DEFAULT NULL,
  `END_STATUS` varchar(30) DEFAULT NULL,
  `PARSE_CLASS` varchar(512) DEFAULT NULL,
  `DEAL_PATH` varchar(512) DEFAULT NULL,
  `DEAL_INFO` varchar(128) DEFAULT NULL,
  `IS_HOLIDAY` bigint(11) DEFAULT NULL,
  `IS_REST` bigint(11) DEFAULT NULL,
  `OP_ID` varchar(30) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `ORG_ID` varchar(30) DEFAULT NULL,
  `STATE` bigint(11) DEFAULT NULL,
  PRIMARY KEY (`TL_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_prcs_tm_lmt_stus_mp` */

DROP TABLE IF EXISTS `sr_prcs_tm_lmt_stus_mp`;

CREATE TABLE `sr_prcs_tm_lmt_stus_mp` (
  `STATUS_CODE` bigint(11) NOT NULL,
  `BUS_MAP` varchar(128) DEFAULT NULL,
  `STATUS_TYPE` bigint(11) DEFAULT NULL,
  `STATUS_NAME` varchar(52) DEFAULT NULL,
  `STATE` bigint(11) DEFAULT NULL,
  `OP_ID` varchar(52) DEFAULT NULL,
  `ORG_ID` varchar(52) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`STATUS_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_problem_pcs_ext` */

DROP TABLE IF EXISTS `sr_problem_pcs_ext`;

CREATE TABLE `sr_problem_pcs_ext` (
  `SERIAL_ID` bigint(12) NOT NULL DEFAULT '0' COMMENT '工单号，主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '记录产生时间',
  `CHANGE_RATE_PLAN` varchar(30) DEFAULT NULL COMMENT 'Change Rate Plan',
  `NEW_RATE_PLAN` varchar(30) DEFAULT NULL COMMENT 'New Rate Plan',
  `REQUIRE_CALL_BACK` bigint(1) DEFAULT NULL COMMENT 'REQUIRE CALL Back?',
  `SENDER_NO` varchar(10) DEFAULT NULL COMMENT 'Sender NO',
  `KEYWORD` varchar(10) DEFAULT NULL COMMENT 'Keyword',
  `CONTENT_PROVIDER_NAME` varchar(30) DEFAULT NULL COMMENT 'Content Provider NAME',
  `SERVICE_ACTIVATION_CHANNEL` varchar(20) DEFAULT NULL COMMENT 'Service Activation Channel',
  `STATEMENT_DATE` datetime DEFAULT NULL COMMENT 'Statement DATE (Postpaid)',
  `EXACT_DATE_CREDIT_DEDUCTED` datetime DEFAULT NULL COMMENT 'Exact DATE & TIME Credit Deducted (Prepaid)',
  `CP_ACTIVATION_DATE` datetime DEFAULT NULL COMMENT 'CP Activation DATE AS per CPA Portal',
  `CP_DEACTIVATION_DATE` datetime DEFAULT NULL COMMENT 'CP Deactivation DATE AS per CPA Portal',
  `TOTAL_AMOUNT_DISPUTE` bigint(10) DEFAULT NULL COMMENT 'Total Amount Dispute',
  `REASON_OF_DISPUTE` varchar(30) DEFAULT NULL COMMENT 'Reason of Dispute',
  `ACCOUNT_STATUS` varchar(30) DEFAULT NULL COMMENT 'Account STATUS',
  `UNBARRING_REQUEST` varchar(50) DEFAULT NULL COMMENT 'Unbarring Request',
  `SUSPENSION_REQUEST` varchar(30) DEFAULT NULL COMMENT 'Suspension Request',
  `ACTIVATE_BILL_STATEMENT` varchar(30) DEFAULT NULL COMMENT 'Activate Bill Statement',
  `DEACTIVATE_BILL_STATEMENT` varchar(50) DEFAULT NULL COMMENT 'Deactivate Bill Statement',
  `ACTIVATE_ITEMIZED_STATEMENT` varchar(30) DEFAULT NULL COMMENT 'Activate Itemized Statement',
  `DEACTIVATE_ITEMIZED_STATEMENT` varchar(30) DEFAULT NULL COMMENT 'Deactivate Itemized Statement',
  `REFUND_STATUS_INQUIRY` varchar(30) DEFAULT NULL COMMENT 'Refund STATUS Inquiry',
  `UMOBILE_PARTNER` varchar(30) DEFAULT NULL COMMENT 'U Mobile Partner',
  `SERVICE_CENTER` varchar(50) DEFAULT NULL COMMENT 'Service Centre',
  `CONTACT_CENTER` varchar(30) DEFAULT NULL COMMENT 'Contact Centre',
  `AUTO_DEBIT_NOT_ACTIVATED_CHANNEL` varchar(30) DEFAULT NULL COMMENT 'Auto Debit NOT Activated Channel',
  `ACTIVE_VAS` varchar(100) DEFAULT NULL COMMENT 'Activate VAS',
  `DEACTIVE_VAS` varchar(100) DEFAULT NULL COMMENT 'De-activate VAS',
  `ACCOUNT_DEACTIVATED_DATE` datetime DEFAULT NULL COMMENT 'Account Deactivated DATE (FOR Refund)',
  `AMOUNT_PAID` bigint(10) DEFAULT NULL COMMENT 'Amount Paid',
  `PAYMENT_DATE` datetime DEFAULT NULL COMMENT 'Payment DATE & TIME',
  `PAYMENT_CHANNEL` varchar(30) DEFAULT NULL COMMENT 'Payment Channel',
  `PAYMENT_LOCATION` varchar(50) DEFAULT NULL COMMENT 'Payment Location',
  `PAYMENT_REFERENCE_NUMBER` varchar(20) DEFAULT NULL COMMENT 'Payment Reference number',
  `CORRECT_BSCS_ACCOUNT_NUMBER` varchar(20) DEFAULT NULL COMMENT 'Correct BSCS acount number',
  `WRONG_BSCS_ACCOUNT_NUMBER` varchar(20) DEFAULT NULL COMMENT 'Wrong BSCS account number',
  `REFUND_AMOUNT` bigint(10) DEFAULT NULL COMMENT 'Refund Amount',
  `REFUND_METHOD` varchar(20) DEFAULT NULL COMMENT 'Refund Method',
  `IBG_BANK_NAME` varchar(100) DEFAULT NULL COMMENT 'IBG Bank NAME',
  `BANK_ACCOUNT_NUMBER` varchar(30) DEFAULT NULL COMMENT 'Bank Account Number',
  `CREDIT_LIMIT` bigint(10) DEFAULT NULL COMMENT 'Credit LIMIT',
  `CURRENT_PAYMENT_TYPE` varchar(15) DEFAULT NULL COMMENT 'Current Payment TYPE',
  `AMOUNT_TO_PAY` bigint(10) DEFAULT NULL COMMENT 'Amount TO Pay',
  `UNBILLED_AMOUNT` bigint(10) DEFAULT NULL COMMENT 'Unbilled Amount',
  `BILLED_AMOUNT` bigint(10) DEFAULT NULL COMMENT 'Billed Amount/Charges',
  `AMOUNT_DISPUTE` bigint(10) DEFAULT NULL COMMENT 'Amount Dispute',
  `BSCS_ACCOUNT_NUMBER` varchar(20) DEFAULT NULL COMMENT 'BSCS Account Number',
  `WITH_POLICE_REPORT` bigint(1) DEFAULT NULL COMMENT 'WITH Police Report',
  `ID_TYPE` varchar(20) DEFAULT NULL COMMENT 'ID TYPE',
  `ID_NUMBER` varchar(12) DEFAULT NULL COMMENT 'ID Number',
  `MIS_SOLD_CHANNLE` varchar(20) DEFAULT NULL COMMENT 'Mis-sold Channel',
  `SERVICE_NAME` varchar(30) DEFAULT NULL COMMENT 'Service NAME',
  `SERVICE_STATUS` varchar(20) DEFAULT NULL COMMENT 'Service STATUS',
  `BUNDLE_NAME` varchar(20) DEFAULT NULL COMMENT 'Bundle NAME',
  `AMOUNT_CHARGE_DEDUCT` bigint(10) DEFAULT NULL COMMENT 'Amount Charge/Deduct',
  `TOP_UP_AMOUNT_RECEIVED` bigint(10) DEFAULT NULL COMMENT 'Top up Amount Received',
  `TOP_UP_AMOUNT_SENT` bigint(10) DEFAULT NULL COMMENT 'Top up Amount Sent',
  `SENDER_MSISDN` bigint(12) DEFAULT NULL COMMENT 'Sender MSISDN',
  `RECEIPIENT_MSISDN` bigint(12) DEFAULT NULL COMMENT 'Recipient MSISDN',
  `RECEIPIENT_COUNTRY` varchar(30) DEFAULT NULL COMMENT 'Recipient Country',
  `TOP_UP_TRANSFER_TRANSACTION_DATE` datetime DEFAULT NULL COMMENT 'Top Up/ Transfer TRANSACTION DATE',
  `DENOMINATION_RATE` bigint(10) DEFAULT NULL COMMENT 'Denomination Rate',
  `ERROR_MESSAGE` varchar(300) DEFAULT NULL COMMENT 'Error Message',
  `TOP_UP_SERIAL_NUMBER` bigint(20) DEFAULT NULL COMMENT 'Top Up SERIAL Number',
  `TOP_UP_DENOMINATION` bigint(10) DEFAULT NULL COMMENT 'Top Up Denomination',
  `TOP_UP_PURCHASE_CHANNEL` varchar(30) DEFAULT NULL COMMENT 'Top Up Purchase Channel',
  `TOP_UP_CHANNEL` varchar(20) DEFAULT NULL COMMENT 'Top Up Channel ',
  `TOP_UP_VOUCHER_STATUS` varchar(20) DEFAULT NULL COMMENT 'Top Up Voucher STATUS',
  `SYSTEM_NAME` varchar(30) DEFAULT NULL COMMENT 'System NAME',
  `IS_MNP` bigint(1) DEFAULT NULL COMMENT 'MNP?',
  `PENDING_ERROR` varchar(50) DEFAULT NULL COMMENT 'Pending ORDER',
  `PRODUCT_SERVICE_TYPE` varchar(30) DEFAULT NULL COMMENT 'Product & Services TYPE',
  `PRODUCT_SERVICE_NAME` varchar(50) DEFAULT NULL COMMENT 'Product & Services NAME',
  `REGISTRATION_CHANNEL` varchar(30) DEFAULT NULL COMMENT 'Registration Channel',
  `MNP_REJECT_REASON` varchar(200) DEFAULT NULL,
  `PREVIOUS_OPERATOR` varchar(20) DEFAULT NULL COMMENT 'Previous Operator',
  `MNP_MSISDN` bigint(10) DEFAULT NULL COMMENT 'MSISDN',
  `USIM` varchar(20) DEFAULT NULL COMMENT 'USIM',
  `MNP_RATE_PLAN` varchar(20) DEFAULT NULL COMMENT 'Rate Plan',
  `B_PARTY_NUMBER` bigint(12) DEFAULT NULL COMMENT 'B Party Number',
  `B_PARTY_LOCATION` varchar(50) DEFAULT NULL COMMENT 'B Party Location',
  `OCCURANCE_START_DATE` datetime DEFAULT NULL COMMENT 'START DATE & TIME Occurance',
  `FAILURE_AREA_POSTCODE` varchar(10) DEFAULT NULL,
  `FAILURE_ADDRESS` varchar(200) DEFAULT NULL,
  `FAILURE_STATE` varchar(20) DEFAULT NULL COMMENT 'Failure State',
  `FAILURE_CITY` varchar(50) DEFAULT NULL COMMENT 'Failure City',
  `FAILURE_LANDMARK` varchar(50) DEFAULT NULL COMMENT 'Failure Landmark',
  `LATITUDE` varchar(12) DEFAULT NULL COMMENT 'Latitude',
  `LONGITUDE` varchar(12) DEFAULT NULL COMMENT 'Longitude',
  `OUTAGE_WP` varchar(12) DEFAULT NULL COMMENT 'Outage/WP #',
  `NETWORK_TYPE` varchar(15) DEFAULT NULL COMMENT 'Network TYPE',
  `SIGNAL_STRENGTH` varchar(20) DEFAULT NULL COMMENT 'Signal Strength',
  `SPEED_TEST_DATE` datetime DEFAULT NULL COMMENT 'Speed Test DATE & TIME',
  `DOWNLOAD_SPEED` varchar(10) DEFAULT NULL,
  `UPLOAD_SPEED` varchar(10) DEFAULT NULL,
  `OTHER_CHANNEL` varchar(100) DEFAULT NULL COMMENT 'Other Channel',
  `BAOC_BAR_STATUS` varchar(20) DEFAULT NULL COMMENT 'BAOC Bar Status',
  `PREPAID_STATUS` varchar(20) DEFAULT NULL COMMENT 'Prepaid STATUS',
  `CURRENT_BALANCE` bigint(12) DEFAULT NULL COMMENT 'Current Balance',
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  PRIMARY KEY (`SERIAL_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_problem_process` */

DROP TABLE IF EXISTS `sr_problem_process`;

CREATE TABLE `sr_problem_process` (
  `SERIAL_ID` bigint(12) NOT NULL,
  `SHOW_SERIAL_NO` varchar(25) DEFAULT NULL,
  `FLOW_ID` varchar(50) DEFAULT NULL,
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  `SR_TYPE_ID` varchar(25) DEFAULT NULL,
  `VDN_ID` varchar(128) DEFAULT NULL,
  `ACCEPT_STAFF_NO` varchar(20) DEFAULT NULL,
  `ACCEPT_MODE` bigint(2) DEFAULT NULL,
  `CONTACT_CHANNEL` bigint(3) DEFAULT NULL,
  `ACCEPT_TIME` datetime DEFAULT NULL,
  `CALLER_NO` varchar(60) DEFAULT NULL,
  `CALLED_NO` varchar(60) DEFAULT NULL,
  `ORIGINAL_CALLED_NO` varchar(60) DEFAULT NULL,
  `LANGUAGE_ID` varchar(128) DEFAULT NULL,
  `SERVICE_CITY` varchar(20) DEFAULT NULL,
  `SUBS_CITY` varchar(20) DEFAULT NULL,
  `ACCEPT_CITY` varchar(20) DEFAULT NULL,
  `CUST_MANAGER_NUM` varchar(20) DEFAULT NULL,
  `COMBINE_NAME` varchar(512) DEFAULT NULL,
  `MARKET_ACTIVITY` varchar(512) DEFAULT NULL,
  `VIP_LEVEL` bigint(2) DEFAULT NULL,
  `BUSI_HALL` varchar(512) DEFAULT NULL,
  `SUBS_NAME` varchar(256) DEFAULT NULL,
  `SUBS_LEVEL` bigint(3) DEFAULT NULL,
  `SUBS_BRAND` bigint(3) DEFAULT NULL,
  `CUST_ID` bigint(12) DEFAULT NULL,
  `SUBS_NUMBER` varchar(60) DEFAULT NULL,
  `CONTACTP_ERSON` varchar(100) DEFAULT NULL,
  `CONTACT_MODE` bigint(3) DEFAULT NULL,
  `ID_TYPE` bigint(3) DEFAULT NULL,
  `ID_NUMBER` varchar(30) DEFAULT NULL,
  `CONTACT_PHONE1` varchar(60) DEFAULT NULL,
  `CONTACT_PHONE2` varchar(60) DEFAULT NULL,
  `FAX_NO` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `ADDRESS` varchar(100) DEFAULT NULL,
  `CUST_MANAGER_NO` varchar(20) DEFAULT NULL,
  `SUBS_COMPLAIN_CITY` varchar(20) DEFAULT NULL,
  `TERMINAL_TYPE` bigint(2) DEFAULT NULL,
  `COM_PHENOMENA` varchar(128) DEFAULT NULL,
  `COM_REASON` varchar(500) DEFAULT NULL,
  `FAULT_LOCATION` varchar(100) DEFAULT NULL,
  `TITLE` varchar(200) DEFAULT NULL,
  `SERVICE_CONTENT` varchar(4000) DEFAULT NULL,
  `OPER_STATUS` bigint(3) DEFAULT NULL,
  `HANDLING_STATUS` bigint(3) DEFAULT NULL,
  `IMPACT_ID` bigint(7) DEFAULT NULL,
  `PRIORITY_ID` bigint(3) DEFAULT NULL,
  `URGENT_ID` bigint(3) DEFAULT NULL,
  `SATISFY_ID` bigint(3) DEFAULT NULL,
  `DISSATISFIED_REASON` bigint(3) DEFAULT NULL,
  `FEEDBACK_MODE` bigint(3) DEFAULT NULL,
  `FEEDBACK_TIMES` bigint(4) DEFAULT NULL,
  `UNSCS_FEEDBACK_TIMES` bigint(4) DEFAULT NULL,
  `FEEDBACK_SUC_FLAG` bigint(1) DEFAULT NULL,
  `EXPECTED_FEEDBACK_TIME` datetime DEFAULT NULL,
  `ACTUAL_FEEDBACK_TIME` datetime DEFAULT NULL,
  `RESPONSIBILITY_TYPE` bigint(3) DEFAULT NULL,
  `RESPONSIBILITY_REASON` bigint(3) DEFAULT NULL,
  `RESPONSIBILITY_DEPT` bigint(12) DEFAULT NULL,
  `RESOLVED_EGREE` bigint(3) DEFAULT NULL,
  `QC_FLAG` bigint(1) DEFAULT NULL,
  `QC_STAFF_NO` varchar(20) DEFAULT NULL,
  `REPEAT_FLAG` bigint(1) DEFAULT NULL,
  `FRONT_REPLY_FLAG` bigint(1) DEFAULT NULL,
  `APPEND_NOTES_FLAG` bigint(1) DEFAULT NULL,
  `REPEATED_FLAG` bigint(1) DEFAULT NULL,
  `UPGRADE_FLAG` bigint(1) DEFAULT NULL,
  `REFUNDMENT_FLAG` bigint(1) DEFAULT NULL,
  `CUSTORME_RVISIT_FLAG` bigint(1) DEFAULT NULL,
  `CUSTORME_RVISIT_STATUS` bigint(1) DEFAULT NULL,
  `REFUNDMENT_TYPE` bigint(3) DEFAULT NULL,
  `EXPECTED_AMOUNT` bigint(10) DEFAULT NULL,
  `FACT_AMOUNT` bigint(10) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `MAIN_SERIAL_NO` varchar(25) DEFAULT NULL,
  `MAIN_FLAG` bigint(1) DEFAULT NULL,
  `CLOSE_DATE` datetime DEFAULT NULL,
  `ARCHIVE_DATE` datetime DEFAULT NULL,
  `CONTENT_TEMPLATE_ID` bigint(12) DEFAULT NULL,
  `ACCEPT_STAFF_DEPT` varchar(200) DEFAULT NULL,
  `CONTACT_ID` varchar(30) DEFAULT NULL,
  `MAINVALID_DATE` datetime DEFAULT NULL,
  `ACCEPT_ORG_ACODE` bigint(12) DEFAULT NULL,
  `FIRSTREPLY_TIME` datetime DEFAULT NULL,
  `TIMER_GROUP_START_TIME` datetime DEFAULT NULL,
  `TIMER_GROUP_ALARM_TIME` datetime DEFAULT NULL,
  `TIMER_GROUP_DEADLINE_TIME` datetime DEFAULT NULL,
  `TIMER_GROUP_LEAVE_TIME` datetime DEFAULT NULL,
  `REASON_TYPE_ID` bigint(3) DEFAULT NULL,
  `ORIGINAL_SR_TYPE_ID` bigint(12) DEFAULT NULL,
  `ADVISED_SR_TYPE_ID` bigint(12) DEFAULT NULL,
  `ORIGINAL_REASON_TYPE_ID` varchar(20) DEFAULT NULL,
  `RESORT_SR_TYPE_ID` bigint(12) DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL,
  `LAST_WORK_ITEM_ID` varchar(30) DEFAULT NULL,
  `CANCEL_FLAG` bigint(1) DEFAULT NULL,
  `RETURN_FLAG` bigint(1) DEFAULT NULL,
  `CALLBACK_FLAG` bigint(1) DEFAULT NULL,
  `DIRECT_FLAG` bigint(1) DEFAULT NULL,
  `REDO_TIMES` bigint(4) DEFAULT NULL,
  `REASSIGN_TIMES` bigint(4) DEFAULT NULL,
  `DELAY_TIMES` bigint(4) DEFAULT NULL,
  `DELAY_DURATION` bigint(10) DEFAULT NULL,
  `TOTAL_TIME_OUTDURATION` bigint(10) DEFAULT NULL,
  `FAUL_TO_CC_TIME` datetime DEFAULT NULL,
  `SUSPEND_DATE` datetime DEFAULT NULL,
  `ALARM_TIME` datetime DEFAULT NULL,
  `DIFFICULTY_FLAG` bigint(1) DEFAULT NULL,
  `URGE_FLAG` bigint(1) DEFAULT NULL,
  `PROCESS_COLOR` varchar(20) DEFAULT NULL,
  `PROCESS_STATE` bigint(3) DEFAULT NULL,
  `TEMPLATE_ID` bigint(12) DEFAULT NULL,
  `WORK_ORDER_TYPE` bigint(12) DEFAULT NULL,
  `DEADLINE_TIME` datetime DEFAULT NULL,
  `RESPONSIBILITY_PERSON` varchar(20) DEFAULT NULL,
  `UNIFORM_ANSWER` varchar(200) DEFAULT NULL,
  `KNOWLEDGE_KEY` varchar(400) DEFAULT NULL,
  `AUDITSR_TYPE_ID` varchar(60) DEFAULT NULL,
  `CSVC_PROCESS_TYPE` varchar(1) DEFAULT NULL,
  `IS_C_STAFF_INSERT` varchar(20) DEFAULT NULL,
  `CSVC_ACCEPT_CORP` varchar(20) DEFAULT NULL,
  `BOUND` varchar(200) DEFAULT NULL,
  `CSVC_DEAL_CORP` varchar(20) DEFAULT NULL,
  `CSVC_ID` varchar(22) DEFAULT NULL,
  `CRESPONSIBILITY_TYPE` bigint(3) DEFAULT NULL,
  `CIRCS_DESC` varchar(100) DEFAULT NULL,
  `DEAL_CIRCSDES` varchar(100) DEFAULT NULL,
  `RESPONSEANA` varchar(100) DEFAULT NULL,
  `CHG_SCHEME` varchar(100) DEFAULT NULL,
  `OPERATORS` varchar(100) DEFAULT NULL,
  `USERPARTY` varchar(512) DEFAULT NULL,
  `PARENT_SERIAL_NO` varchar(20) DEFAULT NULL,
  `PARENT_ACTIVITY_ID` varchar(20) DEFAULT NULL,
  `SP_NO` varchar(100) DEFAULT NULL,
  `SPACCESS_MODE` varchar(100) DEFAULT NULL,
  `SP_CODE` varchar(512) DEFAULT NULL,
  `SP_TYPE` varchar(512) DEFAULT NULL,
  `SP_COM_NAME` varchar(512) DEFAULT NULL,
  `SP_SERVICE_NAME` varchar(512) DEFAULT NULL,
  `EOMS_STATUS` varchar(20) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `WF_TEMPLET_ID` varchar(100) DEFAULT NULL,
  `STAFF_CODE` varchar(60) DEFAULT NULL,
  `FAILURE_TYPE` varchar(25) DEFAULT NULL,
  `SUBFAILURE_TYPE` varchar(25) DEFAULT NULL,
  `COMPLAINT_TIMES` bigint(4) DEFAULT NULL,
  `SATISFY_SMS_FLAG` bigint(1) DEFAULT NULL,
  `GROUP_CODE` varchar(60) DEFAULT NULL,
  `REL_SHOW_SERIALNO` varchar(60) DEFAULT NULL,
  `EXT_FIELD_1` varchar(512) DEFAULT NULL,
  `EXT_FIELD_2` varchar(512) DEFAULT NULL,
  `EXT_FIELD_3` varchar(512) DEFAULT NULL,
  `EXT_FIELD_4` varchar(512) DEFAULT NULL,
  `EXT_FIELD_5` varchar(512) DEFAULT NULL,
  `EXT_FIELD_6` varchar(512) DEFAULT NULL,
  `EXT_FIELD_7` varchar(512) DEFAULT NULL,
  `EXT_FIELD_8` varchar(512) DEFAULT NULL,
  `EXT_FIELD_9` varchar(512) DEFAULT NULL,
  `EXT_FIELD_10` varchar(512) DEFAULT NULL,
  `EXT_FIELD_11` varchar(512) DEFAULT NULL,
  `EXT_FIELD_12` varchar(512) DEFAULT NULL,
  `EXT_FIELD_13` varchar(512) DEFAULT NULL,
  `EXT_FIELD_14` varchar(512) DEFAULT NULL,
  `EXT_FIELD_15` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`SERIAL_ID`),
  KEY `IDX_SR_PROBLEM_PROCESS_1` (`SR_TYPE_ID`),
  KEY `IDX_SR_PROBLEM_PROCESS_2` (`SUBS_NUMBER`),
  KEY `IDX_SR_PROBLEM_PROCESS_3` (`ACCEPT_STAFF_NO`,`PROCESS_STATE`),
  KEY `IDX_SR_PROBLEM_PROCESS_4` (`CREATE_TIME`),
  KEY `IDX_SR_PROBLEM_PROCESS_5` (`STAFF_CODE`),
  KEY `IDX_SR_PROBLEM_PROCESS_6` (`FAULT_LOCATION`),
  KEY `IDX_CMS_CLOSE_DATE` (`CLOSE_DATE`),
  KEY `IDX_SR_PROBLEM_PROCESS_7` (`PROCESS_STATE`),
  KEY `IDX_SR_PROBLEM_PROCESS_8` (`MAIN_FLAG`),
  KEY `IDX_LAST_WORK_ITEM_ID` (`LAST_WORK_ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_problem_work_item` */

DROP TABLE IF EXISTS `sr_problem_work_item`;

CREATE TABLE `sr_problem_work_item` (
  `WORK_ITEM_ID` bigint(12) NOT NULL,
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  `SR_TYPE_ID` varchar(25) DEFAULT NULL,
  `SERIAL_ID` bigint(12) DEFAULT NULL,
  `PROCESS_SERIAL_NO` varchar(25) DEFAULT NULL,
  `TASK_ID` varchar(50) DEFAULT NULL,
  `FLOW_ID` varchar(50) DEFAULT NULL,
  `NODE_ID` varchar(128) DEFAULT NULL,
  `NODE_NAME` varchar(128) DEFAULT NULL,
  `NODE_TYPE` varchar(128) DEFAULT NULL,
  `SHOW_SERIAL_NO` varchar(25) DEFAULT NULL,
  `ALLOCATION_APPRAISE` bigint(12) DEFAULT NULL,
  `ALLOCATION_QUALITY` bigint(3) DEFAULT NULL,
  `ALLOCATION_APPRAISEBACK` varchar(128) DEFAULT NULL,
  `ALLOCATION_QUALITYBACK` varchar(128) DEFAULT NULL,
  `ALLOCATION_MODE` bigint(3) DEFAULT NULL,
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '提醒时间',
  `DEADLINE_TIME` datetime DEFAULT NULL COMMENT '到期时间',
  `DELAY_STATE` bigint(3) DEFAULT NULL,
  `REPLY_TYPE` bigint(3) DEFAULT NULL,
  `REPLY_SUCCESS` varchar(1) DEFAULT NULL,
  `CUSTOMER_SATISFACTION` bigint(3) DEFAULT NULL,
  `SERVICE_STATE` varchar(128) DEFAULT NULL,
  `HANDLING_DURATION` bigint(10) DEFAULT NULL,
  `WAIT_DURATION` bigint(10) DEFAULT NULL,
  `TIMEOUT_DURATION` bigint(10) DEFAULT NULL,
  `PHASE_CUST_REPLY_STATE` bigint(3) DEFAULT NULL,
  `CREATION_TIME` datetime DEFAULT NULL,
  `COMPLETE_TIME` datetime DEFAULT NULL,
  `HANDLING_DEPT` varchar(60) DEFAULT NULL,
  `HANDLING_ROLE` varchar(60) DEFAULT NULL,
  `HANDLING_STAFF` varchar(60) DEFAULT NULL,
  `HANDLING_COMMENT` varchar(4000) DEFAULT NULL,
  `HANDLING_REASON` varchar(40) DEFAULT NULL,
  `REASSIGN_TIMES` bigint(4) DEFAULT NULL,
  `CALLBACK_TIMES` bigint(4) DEFAULT NULL,
  `RETURN_TIMES` bigint(4) DEFAULT NULL,
  `RYGBRAND_FLAG` bigint(1) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `URGE_FLAG` bigint(1) DEFAULT NULL,
  `PREDECESSOR` bigint(12) DEFAULT NULL,
  `ANSWERID` bigint(12) DEFAULT NULL,
  `WORK_ITEM_COLOR` varchar(20) DEFAULT NULL,
  `CONTACT_ID` varchar(20) DEFAULT NULL,
  `CONTACT_PHONE` varchar(20) DEFAULT NULL,
  `RESPONSE_PERSON` varchar(80) DEFAULT NULL,
  `RESPONSE_TIME` datetime DEFAULT NULL,
  `CONTACTE_DCUSTOMER` varchar(2) DEFAULT NULL,
  `OPERATE_TYPE` bigint(12) DEFAULT NULL,
  `TIMER_GROUP_START_TIME` datetime DEFAULT NULL,
  `TIMER_GROUP_ALARM_TIME` datetime DEFAULT NULL,
  `TIMER_GROUP_DEADLINE_TIME` datetime DEFAULT NULL,
  `HANDLIN_GORGA_CODE` bigint(16) DEFAULT NULL,
  `CITY_ID` varchar(20) DEFAULT NULL,
  `AFFIRM_FLAG` bigint(1) DEFAULT NULL,
  `NEW_FLAG` bigint(1) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `EXT_FIELD_1` varchar(512) DEFAULT NULL,
  `EXT_FIELD_2` varchar(512) DEFAULT NULL,
  `EXT_FIELD_3` varchar(512) DEFAULT NULL,
  `EXT_FIELD_4` varchar(512) DEFAULT NULL,
  `EXT_FIELD_5` varchar(512) DEFAULT NULL,
  `EXT_FIELD_6` varchar(512) DEFAULT NULL,
  `EXT_FIELD_7` varchar(512) DEFAULT NULL,
  `EXT_FIELD_8` varchar(512) DEFAULT NULL,
  `EXT_FIELD_9` varchar(512) DEFAULT NULL,
  `EXT_FIELD_10` varchar(512) DEFAULT NULL,
  `EXECUTOR_ORG` varchar(60) DEFAULT NULL,
  `EXECUTOR_CODE` varchar(60) DEFAULT NULL,
  `OPEN_FLAG` varchar(30) DEFAULT NULL,
  `ALERT_DATE` datetime DEFAULT NULL,
  `IS_TIME_CLCL` bigint(1) DEFAULT NULL,
  `OPT_TIMES` bigint(4) DEFAULT NULL,
  `OUTPUT_STATE` bigint(2) DEFAULT NULL,
  `NEXT_DEAL_DEPT` varchar(60) DEFAULT NULL,
  `NEXT_DEAL_STAFF` varchar(60) DEFAULT NULL,
  `PRI_WORK_ITEM_ID` bigint(12) DEFAULT NULL,
  `PRI_DEAL_STAFF` varchar(60) DEFAULT NULL,
  `PRI_DEAL_DEPT` varchar(60) DEFAULT NULL,
  `PHASE_RETURN_FLAG` bigint(1) DEFAULT NULL,
  `LIMIT_DATE` datetime DEFAULT NULL,
  `DETAIL_LIMIT_ID` bigint(12) DEFAULT NULL,
  `LIMIT_ID` bigint(12) DEFAULT NULL,
  `PHASE_DEPT_RETURN_TIMES` bigint(6) DEFAULT NULL,
  `PHASE_RETURN_TIMES` bigint(6) DEFAULT NULL,
  `PHASE_SETTLE_TIME` bigint(6) DEFAULT NULL,
  `SYS_PHASE_START_DATE` datetime DEFAULT NULL,
  `PHASE_START_DATE` datetime DEFAULT NULL,
  `ACTIVE_DATE` datetime DEFAULT NULL,
  `SUSPEND_DATE` datetime DEFAULT NULL,
  `WF_TEMPLET_ID` varchar(100) DEFAULT NULL,
  `SUSPEND_NUM` bigint(10) DEFAULT NULL,
  `OUTTIME_FLAG` bigint(1) DEFAULT NULL,
  `CUST_ID` bigint(12) DEFAULT NULL,
  `PRIORITY_ID` bigint(2) DEFAULT NULL,
  `CONTACT_CHANNEL` bigint(3) DEFAULT NULL,
  `SR_CREATE_TIME` datetime DEFAULT NULL,
  `SUBS_NAME` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`WORK_ITEM_ID`),
  KEY `IDX_SR_PROBLEM_WORK_ITEM_1` (`SERIAL_ID`),
  KEY `IDX_SR_PROBLEM_WORK_ITEM_2` (`HANDLING_STAFF`,`SERVICE_STATE`),
  KEY `IDX_SR_PROBLEM_WORK_ITEM_3` (`HANDLING_DEPT`,`SERVICE_STATE`),
  KEY `IDX_SR_PROBLEM_WORK_ITEM_4` (`WF_TEMPLET_ID`,`NODE_NAME`),
  KEY `IDX_SR_PROBLEM_WORK_ITEM_5` (`COMPLETE_TIME`),
  KEY `IDX_SR_PROBLEM_WORK_ITEM_6` (`CREATION_TIME`),
  KEY `IDX_SR_PROBLEM_WORK_ITEM_7` (`SERVICE_STATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_property_exroute` */

DROP TABLE IF EXISTS `sr_property_exroute`;

CREATE TABLE `sr_property_exroute` (
  `MLTPROUTE_ID` bigint(12) NOT NULL,
  `CATEGORY` bigint(3) DEFAULT NULL COMMENT '1 - 服务请求填单页面\r\n            2 - 业务内容模板\r\n            3 - 问卷脚本\r\n            4 - 关联流程模板\r\n            5 - 工作流各节点常用语\r\n            6 - 常用短信(数据来源知识库)\r\n            7 - 责任原因\r\n            8 - 各节点处理评比\r\n            9 - 节点处理页面\r\n            10 - 处理节点内容模板\r\n            11 - 节点工单页面\r\n            12 - 组织关联渠道',
  `SR_TYPE_ID` varchar(50) DEFAULT NULL,
  `ORDER_STATUS` bigint(3) DEFAULT NULL,
  `ACCEPT_ORG` varchar(60) DEFAULT NULL,
  `ACCEPT_CITY` varchar(10) DEFAULT NULL,
  `CONTACT_CHANNEL` bigint(3) DEFAULT NULL,
  `SUBS_BRAND` bigint(3) DEFAULT NULL,
  `SUBS_LEVEL` bigint(3) DEFAULT NULL,
  `URGENT_ID` bigint(3) DEFAULT NULL,
  `FLOW_TEMPLET_ID` varchar(100) DEFAULT NULL,
  `NODE_ID` varchar(30) DEFAULT NULL,
  `ACCEPT_MODE` bigint(3) DEFAULT NULL,
  `ROUTE_KEY` varchar(200) DEFAULT NULL,
  `TARGET` varchar(2000) DEFAULT NULL,
  `TARGET_DESC` varchar(2000) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  PRIMARY KEY (`MLTPROUTE_ID`),
  KEY `IDX_SR_PROPERTY_EXROUTE_1` (`CATEGORY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_service_request` */

DROP TABLE IF EXISTS `sr_service_request`;

CREATE TABLE `sr_service_request` (
  `SERVICE_ID` bigint(12) NOT NULL,
  `SHOW_SERIALNO` varchar(25) DEFAULT NULL,
  `SR_TYPE_ID` varchar(25) DEFAULT NULL,
  `ACCEPT_STAFF_NO` varchar(20) DEFAULT NULL,
  `ACCEPT_STAFF_NAME` varchar(255) DEFAULT NULL,
  `ACCEPT_STAFF_DEPT` bigint(12) DEFAULT NULL,
  `ACCEPT_STAFF_DEPT_NAME` varchar(255) DEFAULT NULL,
  `ACCEPT_MODE` bigint(3) DEFAULT NULL,
  `CONTACT_CHANNEL` bigint(3) DEFAULT NULL,
  `TERMINAL_TYPE` bigint(1) DEFAULT NULL,
  `CUST_MANAGER_NO` varchar(20) DEFAULT NULL,
  `ACCEPT_CITY` varchar(20) DEFAULT NULL,
  `SERVICE_CITY` varchar(20) DEFAULT NULL,
  `SUBS_CITY` varchar(20) DEFAULT NULL,
  `USER_COMPLAIN_CITY` varchar(20) DEFAULT NULL,
  `CUST_ID` bigint(12) DEFAULT NULL,
  `COMBINE_FLAG` bigint(1) DEFAULT NULL,
  `CUST_MANAGER_NUM` varchar(20) DEFAULT NULL,
  `COMBINE_NAME` varchar(512) DEFAULT NULL,
  `MARKET_ACTIVITY` varchar(512) DEFAULT NULL,
  `VIP_LEVEL` bigint(2) DEFAULT NULL,
  `BUSI_HALL` varchar(512) DEFAULT NULL,
  `CALLER_NO` varchar(60) DEFAULT NULL,
  `CALLED_NO` varchar(60) DEFAULT NULL,
  `SUBS_NAME` varchar(256) DEFAULT NULL,
  `SUBS_LEVEL` bigint(3) DEFAULT NULL,
  `SUBS_BRAND` bigint(3) DEFAULT NULL,
  `SUBS_NUMBER` varchar(60) DEFAULT NULL,
  `ACCOUNT_ID` bigint(12) DEFAULT NULL,
  `ACCOUNT_TYPE` bigint(2) DEFAULT NULL,
  `OFFER_ID` bigint(12) DEFAULT NULL,
  `OFFER_NAME` varchar(128) DEFAULT NULL,
  `OFFER_TYPE` varchar(8) DEFAULT NULL,
  `USER_STATE` varchar(3) DEFAULT NULL,
  `CONTACT_PERSON` varchar(100) DEFAULT NULL,
  `CONTACT_MODE` bigint(3) DEFAULT NULL,
  `ID_TYPE` bigint(2) DEFAULT NULL,
  `ID_NUMBER` varchar(30) DEFAULT NULL,
  `CONTACT_PHONE1` varchar(60) DEFAULT NULL,
  `CONTACT_PHONE2` varchar(60) DEFAULT NULL,
  `FAX_NO` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `ADDRESS` varchar(100) DEFAULT NULL,
  `FAULT_LOCATION` varchar(100) DEFAULT NULL,
  `SERVICE_TITLE` varchar(200) DEFAULT NULL,
  `SERVICE_CONTENT` varchar(4000) DEFAULT NULL,
  `QUESTION_ID` bigint(12) DEFAULT NULL,
  `ANSWER_ID` bigint(12) DEFAULT NULL,
  `IMPORTMENT_USER` varchar(200) DEFAULT NULL,
  `TD_FLAG` bigint(1) DEFAULT NULL,
  `SMS_FLAG` bigint(1) DEFAULT NULL,
  `SR_KEY_CHAR` varchar(50) DEFAULT NULL,
  `IMPACT_ID` bigint(2) DEFAULT NULL,
  `PRIORITY_ID` bigint(2) DEFAULT NULL,
  `URGENT_ID` bigint(2) DEFAULT NULL,
  `LIMITTIME_TARGETS` varchar(1000) DEFAULT NULL,
  `PAGE_URL` varchar(512) DEFAULT NULL,
  `OPERACTION_STATUS` bigint(3) DEFAULT NULL,
  `NDNOTES_FLAG` bigint(1) DEFAULT NULL,
  `LAST_NOTES_TIME` datetime DEFAULT NULL,
  `REPEAT_FLAG` bigint(1) DEFAULT NULL,
  `REPEAT_NUM` bigint(6) DEFAULT NULL,
  `REPEAT_SERIALNO` bigint(12) DEFAULT NULL,
  `SAME_FLAG` bigint(2) DEFAULT NULL,
  `SAME_SERIALNO` varchar(25) DEFAULT NULL,
  `FEEDBACK_TIMES` bigint(1) DEFAULT NULL,
  `FEEDBACK_MODE` bigint(2) DEFAULT NULL,
  `FAULT_OCC_TIME` datetime DEFAULT NULL,
  `PRETREATMENTTIME` datetime DEFAULT NULL,
  `MAIN_DATE` datetime DEFAULT NULL,
  `FEEDBACK_TIME` datetime DEFAULT NULL,
  `FACT_FEEDBACK_TIME` datetime DEFAULT NULL,
  `FEEDBACK_SATISFIED` bigint(2) DEFAULT NULL,
  `FEEDBACK_DIS_SATIS_RSN` bigint(2) DEFAULT NULL,
  `SATISFY_ID` bigint(2) DEFAULT NULL,
  `FEEDBACK_SUCFLAG` bigint(1) DEFAULT NULL,
  `CUST_VISIT_FLAG` bigint(1) DEFAULT NULL,
  `CUST_VISIT_STATUS` bigint(1) DEFAULT NULL,
  `CALLBACK_FLAG` bigint(1) DEFAULT NULL,
  `REPLY_FLAG` bigint(1) DEFAULT NULL,
  `REASON_TYPE_ID` bigint(3) DEFAULT NULL,
  `CALLBACK_MODE` bigint(2) DEFAULT NULL,
  `CALLBACK_SATISFIED` bigint(2) DEFAULT NULL,
  `CALLBACK_DIS_REASON` bigint(2) DEFAULT NULL,
  `QC_FLAG` bigint(1) DEFAULT NULL,
  `QC_STAFFNO` varchar(20) DEFAULT NULL,
  `RESPONSIBILITY_TYPE` bigint(2) DEFAULT NULL,
  `RESPONSIBILITY_REASON` bigint(2) DEFAULT NULL,
  `DISSATISFIED_REASON` bigint(2) DEFAULT NULL,
  `RESPONSIBILITY_DEPT` bigint(12) DEFAULT NULL,
  `UNIFORM_ANSWER` varchar(200) DEFAULT NULL,
  `RESOLVEDE_GREE` bigint(1) DEFAULT NULL,
  `CONTACT_ID` varchar(30) DEFAULT NULL,
  `CONTACT_DEATIL_ID` varchar(50) DEFAULT NULL,
  `CONTACT_DURATION` bigint(6) DEFAULT NULL,
  `SUBMIT_STAFF_NO` varchar(20) DEFAULT NULL,
  `PARTNER_FLAG` bigint(2) DEFAULT NULL,
  `FIRST_REPLY_TIME` datetime DEFAULT NULL,
  `ORIGINAL_SR_TYPE_ID` bigint(12) DEFAULT NULL,
  `ORIGINAL_REASON_TYPE_ID` varchar(20) DEFAULT NULL,
  `RESORTSR_TYPE_ID` bigint(12) DEFAULT NULL,
  `LAST_TASK_ID` varchar(30) DEFAULT NULL,
  `CANCEL_FLAG` bigint(1) DEFAULT NULL,
  `RETURN_FLAG` bigint(1) DEFAULT NULL,
  `DIRECT_FLAG` bigint(1) DEFAULT NULL,
  `REASSIGN_TIMES` bigint(4) DEFAULT NULL,
  `URGE_FLAG` bigint(1) DEFAULT NULL,
  `HANDLING_STATUS` bigint(3) DEFAULT NULL,
  `PROCESS_STATE` bigint(3) DEFAULT NULL,
  `TEMPLET_ID` bigint(12) DEFAULT NULL,
  `RESPONSIBILITY_PERSON` varchar(20) DEFAULT NULL,
  `KNOWLEDGE_KEY` varchar(400) DEFAULT NULL,
  `IS_CREATE_ORDER` bigint(1) DEFAULT NULL,
  `TOTAL_TIMEOUT_DURATION` bigint(10) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `ACCEPT_TIME` datetime DEFAULT NULL,
  `ACCEPT_DURATION` bigint(6) DEFAULT NULL,
  `SUBMIT_TIME` datetime DEFAULT NULL,
  `CLOSE_DATE` datetime DEFAULT NULL,
  `SUSPEND_DATE` datetime DEFAULT NULL,
  `ALARM_TIME` datetime DEFAULT NULL,
  `ARCHIVEDATE` datetime DEFAULT NULL,
  `CSVC_ID` varchar(50) DEFAULT NULL,
  `CSVC_JUDGE_FLAG` varchar(20) DEFAULT NULL,
  `CSVC_PROCESS_TYPE` bigint(1) DEFAULT NULL,
  `CSVC_ACCEPTCORP` varchar(20) DEFAULT NULL,
  `CSVC_DEALCORP` varchar(20) DEFAULT NULL,
  `CSVC_STAFFINSERT` varchar(20) DEFAULT NULL,
  `BOUND` varchar(200) DEFAULT NULL,
  `CR_ESPONSIBILITYT_YPE` bigint(3) DEFAULT NULL,
  `CIRCSDESC` varchar(100) DEFAULT NULL,
  `DEAL_CIRCSDES` varchar(100) DEFAULT NULL,
  `RESPONSE_ANA` varchar(100) DEFAULT NULL,
  `CHG_SCHEME` varchar(100) DEFAULT NULL,
  `OPERATORS` varchar(100) DEFAULT NULL,
  `USER_PARTY` varchar(512) DEFAULT NULL,
  `SPNO` varchar(100) DEFAULT NULL,
  `PARENT_SERIALNO` varchar(20) DEFAULT NULL,
  `PARENT_ACTIVITYID` varchar(20) DEFAULT NULL,
  `SP_ACCESS_MODE` varchar(100) DEFAULT NULL,
  `SP_CODE` varchar(512) DEFAULT NULL,
  `SP_TYPE` varchar(512) DEFAULT NULL,
  `SP_COM_NAME` varchar(512) DEFAULT NULL,
  `SP_SERVICE_NAME` varchar(512) DEFAULT NULL,
  `EOMS_STATUS` varchar(20) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `COMPLAIN_PHENOMENA` varchar(128) DEFAULT NULL,
  `COMPLAIN_REASON` varchar(500) DEFAULT NULL,
  `FRONTREPLY_FLAG` bigint(1) DEFAULT NULL,
  `UPGRADE_FLAG` bigint(2) DEFAULT NULL,
  `REFUNDMENT_FLAG` bigint(1) DEFAULT NULL,
  `REFUNDMENT_TYPE` bigint(2) DEFAULT NULL,
  `EDREFUNDMENT_AMOUNT` bigint(10) DEFAULT NULL,
  `FACTREFUNDMENT_AMOUNT` bigint(10) DEFAULT NULL,
  `DELAY_DURATION` bigint(10) DEFAULT NULL,
  `AUDITSR_TYPEID` varchar(60) DEFAULT NULL,
  `SAME_NUM` bigint(6) DEFAULT NULL,
  `DELAY_TIMES` bigint(4) DEFAULT NULL,
  `DIFFICULTY_FLAG` bigint(1) DEFAULT NULL,
  `PROCESS_COLOR` varchar(20) DEFAULT NULL,
  `STAFF_CODE` varchar(60) DEFAULT NULL,
  `CC_ID` varchar(20) DEFAULT NULL,
  `FAILURE_TYPE` varchar(25) DEFAULT NULL,
  `SUBFAILURE_TYPE` varchar(25) DEFAULT NULL,
  `LANGUAGE_ID` varchar(128) DEFAULT NULL,
  `COMPLAINT_TIMES` bigint(4) DEFAULT NULL,
  `SATISFY_SMS_FLAG` bigint(1) DEFAULT NULL,
  `GROUP_CODE` varchar(60) DEFAULT NULL,
  `REL_SHOW_SERIALNO` varchar(60) DEFAULT NULL,
  `PUBDYNACHAR001` varchar(512) DEFAULT NULL,
  `PUBDYNACHAR002` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR003` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR004` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR005` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR006` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR007` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR008` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR009` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR010` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR011` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR012` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR013` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR014` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR015` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR016` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR017` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR018` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR019` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR020` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR021` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR022` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR023` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR024` varchar(200) DEFAULT NULL,
  `PUBDYNACHAR025` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`SERVICE_ID`),
  KEY `IDX_SR_SERVICE_REQUEST_1` (`SR_TYPE_ID`),
  KEY `IDX_SR_SERVICE_REQUEST_2` (`SUBS_NUMBER`),
  KEY `IDX_SR_SERVICE_REQUEST_3` (`ACCEPT_STAFF_NO`),
  KEY `IDX_SR_SERVICE_REQUEST_4` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_service_request_type` */

DROP TABLE IF EXISTS `sr_service_request_type`;

CREATE TABLE `sr_service_request_type` (
  `SR_TYPE_ID` varchar(50) NOT NULL,
  `SORT_ID` varchar(60) DEFAULT NULL,
  `SUPER_SORT_ID` varchar(50) DEFAULT NULL,
  `SUPER_SR_TYPE_ID` varchar(50) DEFAULT NULL,
  `TOP_SR_TYPE_ID` varchar(50) DEFAULT NULL,
  `CARRIER` varchar(20) DEFAULT NULL,
  `SR_TYPE_NAME` varchar(512) DEFAULT NULL,
  `FULL_NAME` varchar(1024) DEFAULT NULL,
  `DESCRIPTION` varchar(1024) DEFAULT NULL,
  `CITY_ID` varchar(20) DEFAULT NULL,
  `VEST_ORG_ID` varchar(256) DEFAULT NULL,
  `DURATION` bigint(6) DEFAULT NULL,
  `IS_LEAF` bigint(1) DEFAULT NULL COMMENT '是否叶子节点\r\n            0 - 否\r\n            1 - 是',
  `IS_CHOICE` bigint(1) DEFAULT NULL,
  `REASON_TYPE_ID` bigint(2) DEFAULT NULL,
  `SEARCH_KEY` varchar(1024) DEFAULT NULL COMMENT '搜索关键字',
  `IS_HIDDEN` bigint(1) DEFAULT NULL,
  `SKILL_QUEUE_ID` varchar(2000) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  PRIMARY KEY (`SR_TYPE_ID`),
  KEY `IDX_SR_TTYPE_1` (`SR_TYPE_NAME`(255)),
  KEY `IDX_SR_TTYPE_2` (`SUPER_SR_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_service_request_type_log` */

DROP TABLE IF EXISTS `sr_service_request_type_log`;

CREATE TABLE `sr_service_request_type_log` (
  `LOG_ID` bigint(12) NOT NULL,
  `LOG_TIME` datetime DEFAULT NULL,
  `SR_TYPE_ID` varchar(50) DEFAULT NULL,
  `SR_TYPE_NAME` varchar(128) DEFAULT NULL,
  `SERVICE_ID` bigint(12) DEFAULT NULL,
  `OPT_TYPE` bigint(2) DEFAULT NULL,
  `DESCRIPTION` varchar(1024) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `HANDLING_STAFF` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`LOG_ID`),
  KEY `IDX_SR_TYPE_LOG_1` (`SR_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_sla_cfg` */

DROP TABLE IF EXISTS `sr_sla_cfg`;

CREATE TABLE `sr_sla_cfg` (
  `SLA_CFG_ID` bigint(11) NOT NULL,
  `SR_TYPE` bigint(2) NOT NULL,
  `SR_NAME` varchar(128) DEFAULT NULL,
  `FILTER_OPTION` bigint(2) DEFAULT NULL,
  `STATE` bigint(11) NOT NULL,
  `REMARK` varchar(1024) DEFAULT NULL,
  `ORG_ID` bigint(11) DEFAULT NULL,
  `OP_ID` bigint(11) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`SLA_CFG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_sla_filter` */

DROP TABLE IF EXISTS `sr_sla_filter`;

CREATE TABLE `sr_sla_filter` (
  `SLA_FILTER_ID` bigint(11) NOT NULL,
  `SLA_CFG_ID` bigint(11) NOT NULL,
  `FILTER_TYPE` bigint(2) NOT NULL,
  `FILTER_OPTION` bigint(2) NOT NULL,
  `FILTER_VALUE` varchar(512) NOT NULL,
  `STATE` bigint(2) NOT NULL,
  `REMARK` varchar(1024) DEFAULT NULL,
  `ORG_ID` bigint(11) DEFAULT NULL,
  `OP_ID` bigint(11) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`SLA_FILTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_sla_notification` */

DROP TABLE IF EXISTS `sr_sla_notification`;

CREATE TABLE `sr_sla_notification` (
  `SLA_NOTIFICATION_ID` bigint(11) NOT NULL,
  `SLA_CFG_ID` bigint(11) NOT NULL,
  `NOTIFICATION_TYPE` bigint(2) NOT NULL,
  `RECEIVER_TYPE` bigint(2) NOT NULL,
  `RECEIVE_VALUE` varchar(16) DEFAULT NULL,
  `STATE` bigint(2) NOT NULL,
  `REMARK` varchar(1024) DEFAULT NULL,
  `ORG_ID` bigint(11) DEFAULT NULL,
  `OP_ID` bigint(11) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`SLA_NOTIFICATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_sla_notification_time` */

DROP TABLE IF EXISTS `sr_sla_notification_time`;

CREATE TABLE `sr_sla_notification_time` (
  `SLA_NOTIFICATION_TIME_ID` bigint(11) NOT NULL,
  `SLA_NOTIFICATION_ID` bigint(11) DEFAULT NULL,
  `SLA_CFG_ID` bigint(11) DEFAULT NULL,
  `TIME_DAY` bigint(8) DEFAULT NULL,
  `TIME_HOUR` bigint(8) DEFAULT NULL,
  `TIME_MIN` bigint(8) DEFAULT NULL,
  `TIME_SEC` bigint(8) DEFAULT NULL,
  `TIME_UNIT` varchar(1024) NOT NULL,
  `STATE` bigint(2) NOT NULL,
  `REMARK` varchar(1024) DEFAULT NULL,
  `ORG_ID` bigint(11) DEFAULT NULL,
  `OP_ID` bigint(11) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`SLA_NOTIFICATION_TIME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sr_sla_time_limit` */

DROP TABLE IF EXISTS `sr_sla_time_limit`;

CREATE TABLE `sr_sla_time_limit` (
  `SLA_TIME_ID` bigint(11) NOT NULL,
  `SLA_CFG_ID` bigint(11) NOT NULL,
  `PRIORITY` varchar(8) NOT NULL,
  `LIMIT_TYPE` bigint(2) NOT NULL,
  `TIME_DAY` bigint(8) DEFAULT NULL,
  `TIME_HOUR` bigint(8) DEFAULT NULL,
  `TIME_MIN` bigint(8) DEFAULT NULL,
  `TIME_SEC` bigint(8) DEFAULT NULL,
  `STATE` bigint(2) NOT NULL,
  `REMARK` varchar(1024) DEFAULT NULL,
  `ORG_ID` bigint(11) DEFAULT NULL,
  `OP_ID` bigint(11) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`SLA_TIME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sys_sequences` */

DROP TABLE IF EXISTS `sys_sequences`;

CREATE TABLE `sys_sequences` (
  `SEQUENCE_NAME` varchar(60) NOT NULL,
  `START_BY` bigint(20) NOT NULL,
  `INCREMENT_BY` bigint(10) NOT NULL,
  `LAST_NUMBER` bigint(20) NOT NULL,
  `JVM_STEP_BY` bigint(10) NOT NULL,
  PRIMARY KEY (`SEQUENCE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `undo_log` */

DROP TABLE IF EXISTS `undo_log`;

CREATE TABLE `undo_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `branch_id` bigint(20) NOT NULL,
  `xid` varchar(100) NOT NULL,
  `rollback_info` longblob NOT NULL,
  `log_status` int(11) NOT NULL,
  `log_created` datetime NOT NULL,
  `log_modified` datetime NOT NULL,
  `ext` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_unionkey` (`xid`,`branch_id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
