package com.aii.crm.msm.web.persistence.bo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MsmCompetitorSwotExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public MsmCompetitorSwotExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompetitorSwotIdIsNull() {
            addCriterion("COMPETITOR_SWOT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdIsNotNull() {
            addCriterion("COMPETITOR_SWOT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdEqualTo(Long value) {
            addCriterion("COMPETITOR_SWOT_ID =", value, "competitorSwotId");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdNotEqualTo(Long value) {
            addCriterion("COMPETITOR_SWOT_ID <>", value, "competitorSwotId");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdGreaterThan(Long value) {
            addCriterion("COMPETITOR_SWOT_ID >", value, "competitorSwotId");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdGreaterThanOrEqualTo(Long value) {
            addCriterion("COMPETITOR_SWOT_ID >=", value, "competitorSwotId");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdLessThan(Long value) {
            addCriterion("COMPETITOR_SWOT_ID <", value, "competitorSwotId");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdLessThanOrEqualTo(Long value) {
            addCriterion("COMPETITOR_SWOT_ID <=", value, "competitorSwotId");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdIn(List<Long> values) {
            addCriterion("COMPETITOR_SWOT_ID in", values, "competitorSwotId");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdNotIn(List<Long> values) {
            addCriterion("COMPETITOR_SWOT_ID not in", values, "competitorSwotId");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdBetween(Long value1, Long value2) {
            addCriterion("COMPETITOR_SWOT_ID between", value1, value2, "competitorSwotId");
            return (Criteria) this;
        }

        public Criteria andCompetitorSwotIdNotBetween(Long value1, Long value2) {
            addCriterion("COMPETITOR_SWOT_ID not between", value1, value2, "competitorSwotId");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdIsNull() {
            addCriterion("CUST_COMPET_ID is null");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdIsNotNull() {
            addCriterion("CUST_COMPET_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdEqualTo(Long value) {
            addCriterion("CUST_COMPET_ID =", value, "custCompetId");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdNotEqualTo(Long value) {
            addCriterion("CUST_COMPET_ID <>", value, "custCompetId");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdGreaterThan(Long value) {
            addCriterion("CUST_COMPET_ID >", value, "custCompetId");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CUST_COMPET_ID >=", value, "custCompetId");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdLessThan(Long value) {
            addCriterion("CUST_COMPET_ID <", value, "custCompetId");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdLessThanOrEqualTo(Long value) {
            addCriterion("CUST_COMPET_ID <=", value, "custCompetId");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdIn(List<Long> values) {
            addCriterion("CUST_COMPET_ID in", values, "custCompetId");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdNotIn(List<Long> values) {
            addCriterion("CUST_COMPET_ID not in", values, "custCompetId");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdBetween(Long value1, Long value2) {
            addCriterion("CUST_COMPET_ID between", value1, value2, "custCompetId");
            return (Criteria) this;
        }

        public Criteria andCustCompetIdNotBetween(Long value1, Long value2) {
            addCriterion("CUST_COMPET_ID not between", value1, value2, "custCompetId");
            return (Criteria) this;
        }

        public Criteria andImpactLevelIsNull() {
            addCriterion("IMPACT_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andImpactLevelIsNotNull() {
            addCriterion("IMPACT_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andImpactLevelEqualTo(String value) {
            addCriterion("IMPACT_LEVEL =", value, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelNotEqualTo(String value) {
            addCriterion("IMPACT_LEVEL <>", value, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelGreaterThan(String value) {
            addCriterion("IMPACT_LEVEL >", value, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelGreaterThanOrEqualTo(String value) {
            addCriterion("IMPACT_LEVEL >=", value, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelLessThan(String value) {
            addCriterion("IMPACT_LEVEL <", value, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelLessThanOrEqualTo(String value) {
            addCriterion("IMPACT_LEVEL <=", value, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelLike(String value) {
            addCriterion("IMPACT_LEVEL like", value, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelNotLike(String value) {
            addCriterion("IMPACT_LEVEL not like", value, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelIn(List<String> values) {
            addCriterion("IMPACT_LEVEL in", values, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelNotIn(List<String> values) {
            addCriterion("IMPACT_LEVEL not in", values, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelBetween(String value1, String value2) {
            addCriterion("IMPACT_LEVEL between", value1, value2, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andImpactLevelNotBetween(String value1, String value2) {
            addCriterion("IMPACT_LEVEL not between", value1, value2, "impactLevel");
            return (Criteria) this;
        }

        public Criteria andStrengthsIsNull() {
            addCriterion("STRENGTHS is null");
            return (Criteria) this;
        }

        public Criteria andStrengthsIsNotNull() {
            addCriterion("STRENGTHS is not null");
            return (Criteria) this;
        }

        public Criteria andStrengthsEqualTo(String value) {
            addCriterion("STRENGTHS =", value, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsNotEqualTo(String value) {
            addCriterion("STRENGTHS <>", value, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsGreaterThan(String value) {
            addCriterion("STRENGTHS >", value, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsGreaterThanOrEqualTo(String value) {
            addCriterion("STRENGTHS >=", value, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsLessThan(String value) {
            addCriterion("STRENGTHS <", value, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsLessThanOrEqualTo(String value) {
            addCriterion("STRENGTHS <=", value, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsLike(String value) {
            addCriterion("STRENGTHS like", value, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsNotLike(String value) {
            addCriterion("STRENGTHS not like", value, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsIn(List<String> values) {
            addCriterion("STRENGTHS in", values, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsNotIn(List<String> values) {
            addCriterion("STRENGTHS not in", values, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsBetween(String value1, String value2) {
            addCriterion("STRENGTHS between", value1, value2, "strengths");
            return (Criteria) this;
        }

        public Criteria andStrengthsNotBetween(String value1, String value2) {
            addCriterion("STRENGTHS not between", value1, value2, "strengths");
            return (Criteria) this;
        }

        public Criteria andWeaknessesIsNull() {
            addCriterion("WEAKNESSES is null");
            return (Criteria) this;
        }

        public Criteria andWeaknessesIsNotNull() {
            addCriterion("WEAKNESSES is not null");
            return (Criteria) this;
        }

        public Criteria andWeaknessesEqualTo(String value) {
            addCriterion("WEAKNESSES =", value, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesNotEqualTo(String value) {
            addCriterion("WEAKNESSES <>", value, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesGreaterThan(String value) {
            addCriterion("WEAKNESSES >", value, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesGreaterThanOrEqualTo(String value) {
            addCriterion("WEAKNESSES >=", value, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesLessThan(String value) {
            addCriterion("WEAKNESSES <", value, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesLessThanOrEqualTo(String value) {
            addCriterion("WEAKNESSES <=", value, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesLike(String value) {
            addCriterion("WEAKNESSES like", value, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesNotLike(String value) {
            addCriterion("WEAKNESSES not like", value, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesIn(List<String> values) {
            addCriterion("WEAKNESSES in", values, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesNotIn(List<String> values) {
            addCriterion("WEAKNESSES not in", values, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesBetween(String value1, String value2) {
            addCriterion("WEAKNESSES between", value1, value2, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andWeaknessesNotBetween(String value1, String value2) {
            addCriterion("WEAKNESSES not between", value1, value2, "weaknesses");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesIsNull() {
            addCriterion("OPPORTUNITIES is null");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesIsNotNull() {
            addCriterion("OPPORTUNITIES is not null");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesEqualTo(String value) {
            addCriterion("OPPORTUNITIES =", value, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesNotEqualTo(String value) {
            addCriterion("OPPORTUNITIES <>", value, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesGreaterThan(String value) {
            addCriterion("OPPORTUNITIES >", value, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesGreaterThanOrEqualTo(String value) {
            addCriterion("OPPORTUNITIES >=", value, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesLessThan(String value) {
            addCriterion("OPPORTUNITIES <", value, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesLessThanOrEqualTo(String value) {
            addCriterion("OPPORTUNITIES <=", value, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesLike(String value) {
            addCriterion("OPPORTUNITIES like", value, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesNotLike(String value) {
            addCriterion("OPPORTUNITIES not like", value, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesIn(List<String> values) {
            addCriterion("OPPORTUNITIES in", values, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesNotIn(List<String> values) {
            addCriterion("OPPORTUNITIES not in", values, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesBetween(String value1, String value2) {
            addCriterion("OPPORTUNITIES between", value1, value2, "opportunities");
            return (Criteria) this;
        }

        public Criteria andOpportunitiesNotBetween(String value1, String value2) {
            addCriterion("OPPORTUNITIES not between", value1, value2, "opportunities");
            return (Criteria) this;
        }

        public Criteria andThreatsIsNull() {
            addCriterion("THREATS is null");
            return (Criteria) this;
        }

        public Criteria andThreatsIsNotNull() {
            addCriterion("THREATS is not null");
            return (Criteria) this;
        }

        public Criteria andThreatsEqualTo(String value) {
            addCriterion("THREATS =", value, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsNotEqualTo(String value) {
            addCriterion("THREATS <>", value, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsGreaterThan(String value) {
            addCriterion("THREATS >", value, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsGreaterThanOrEqualTo(String value) {
            addCriterion("THREATS >=", value, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsLessThan(String value) {
            addCriterion("THREATS <", value, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsLessThanOrEqualTo(String value) {
            addCriterion("THREATS <=", value, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsLike(String value) {
            addCriterion("THREATS like", value, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsNotLike(String value) {
            addCriterion("THREATS not like", value, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsIn(List<String> values) {
            addCriterion("THREATS in", values, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsNotIn(List<String> values) {
            addCriterion("THREATS not in", values, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsBetween(String value1, String value2) {
            addCriterion("THREATS between", value1, value2, "threats");
            return (Criteria) this;
        }

        public Criteria andThreatsNotBetween(String value1, String value2) {
            addCriterion("THREATS not between", value1, value2, "threats");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateDateIsNull() {
            addCriterion("STATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStateDateIsNotNull() {
            addCriterion("STATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateDateEqualTo(Date value) {
            addCriterion("STATE_DATE =", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateNotEqualTo(Date value) {
            addCriterion("STATE_DATE <>", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateGreaterThan(Date value) {
            addCriterion("STATE_DATE >", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("STATE_DATE >=", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateLessThan(Date value) {
            addCriterion("STATE_DATE <", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateLessThanOrEqualTo(Date value) {
            addCriterion("STATE_DATE <=", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateIn(List<Date> values) {
            addCriterion("STATE_DATE in", values, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateNotIn(List<Date> values) {
            addCriterion("STATE_DATE not in", values, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateBetween(Date value1, Date value2) {
            addCriterion("STATE_DATE between", value1, value2, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateNotBetween(Date value1, Date value2) {
            addCriterion("STATE_DATE not between", value1, value2, "stateDate");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(Long value) {
            addCriterion("ORG_ID =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(Long value) {
            addCriterion("ORG_ID <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(Long value) {
            addCriterion("ORG_ID >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ORG_ID >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(Long value) {
            addCriterion("ORG_ID <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(Long value) {
            addCriterion("ORG_ID <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<Long> values) {
            addCriterion("ORG_ID in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<Long> values) {
            addCriterion("ORG_ID not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(Long value1, Long value2) {
            addCriterion("ORG_ID between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(Long value1, Long value2) {
            addCriterion("ORG_ID not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOpIdIsNull() {
            addCriterion("OP_ID is null");
            return (Criteria) this;
        }

        public Criteria andOpIdIsNotNull() {
            addCriterion("OP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOpIdEqualTo(Long value) {
            addCriterion("OP_ID =", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdNotEqualTo(Long value) {
            addCriterion("OP_ID <>", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdGreaterThan(Long value) {
            addCriterion("OP_ID >", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("OP_ID >=", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdLessThan(Long value) {
            addCriterion("OP_ID <", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdLessThanOrEqualTo(Long value) {
            addCriterion("OP_ID <=", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdIn(List<Long> values) {
            addCriterion("OP_ID in", values, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdNotIn(List<Long> values) {
            addCriterion("OP_ID not in", values, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdBetween(Long value1, Long value2) {
            addCriterion("OP_ID between", value1, value2, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdNotBetween(Long value1, Long value2) {
            addCriterion("OP_ID not between", value1, value2, "opId");
            return (Criteria) this;
        }

        public Criteria andDoneDateIsNull() {
            addCriterion("DONE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andDoneDateIsNotNull() {
            addCriterion("DONE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andDoneDateEqualTo(Date value) {
            addCriterion("DONE_DATE =", value, "doneDate");
            return (Criteria) this;
        }

        public Criteria andDoneDateNotEqualTo(Date value) {
            addCriterion("DONE_DATE <>", value, "doneDate");
            return (Criteria) this;
        }

        public Criteria andDoneDateGreaterThan(Date value) {
            addCriterion("DONE_DATE >", value, "doneDate");
            return (Criteria) this;
        }

        public Criteria andDoneDateGreaterThanOrEqualTo(Date value) {
            addCriterion("DONE_DATE >=", value, "doneDate");
            return (Criteria) this;
        }

        public Criteria andDoneDateLessThan(Date value) {
            addCriterion("DONE_DATE <", value, "doneDate");
            return (Criteria) this;
        }

        public Criteria andDoneDateLessThanOrEqualTo(Date value) {
            addCriterion("DONE_DATE <=", value, "doneDate");
            return (Criteria) this;
        }

        public Criteria andDoneDateIn(List<Date> values) {
            addCriterion("DONE_DATE in", values, "doneDate");
            return (Criteria) this;
        }

        public Criteria andDoneDateNotIn(List<Date> values) {
            addCriterion("DONE_DATE not in", values, "doneDate");
            return (Criteria) this;
        }

        public Criteria andDoneDateBetween(Date value1, Date value2) {
            addCriterion("DONE_DATE between", value1, value2, "doneDate");
            return (Criteria) this;
        }

        public Criteria andDoneDateNotBetween(Date value1, Date value2) {
            addCriterion("DONE_DATE not between", value1, value2, "doneDate");
            return (Criteria) this;
        }

        public Criteria andDoneCodeIsNull() {
            addCriterion("DONE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDoneCodeIsNotNull() {
            addCriterion("DONE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDoneCodeEqualTo(String value) {
            addCriterion("DONE_CODE =", value, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeNotEqualTo(String value) {
            addCriterion("DONE_CODE <>", value, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeGreaterThan(String value) {
            addCriterion("DONE_CODE >", value, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DONE_CODE >=", value, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeLessThan(String value) {
            addCriterion("DONE_CODE <", value, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeLessThanOrEqualTo(String value) {
            addCriterion("DONE_CODE <=", value, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeLike(String value) {
            addCriterion("DONE_CODE like", value, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeNotLike(String value) {
            addCriterion("DONE_CODE not like", value, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeIn(List<String> values) {
            addCriterion("DONE_CODE in", values, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeNotIn(List<String> values) {
            addCriterion("DONE_CODE not in", values, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeBetween(String value1, String value2) {
            addCriterion("DONE_CODE between", value1, value2, "doneCode");
            return (Criteria) this;
        }

        public Criteria andDoneCodeNotBetween(String value1, String value2) {
            addCriterion("DONE_CODE not between", value1, value2, "doneCode");
            return (Criteria) this;
        }

        public Criteria andState2IsNull() {
            addCriterion("STATE2 is null");
            return (Criteria) this;
        }

        public Criteria andState2IsNotNull() {
            addCriterion("STATE2 is not null");
            return (Criteria) this;
        }

        public Criteria andState2EqualTo(Long value) {
            addCriterion("STATE2 =", value, "state2");
            return (Criteria) this;
        }

        public Criteria andState2NotEqualTo(Long value) {
            addCriterion("STATE2 <>", value, "state2");
            return (Criteria) this;
        }

        public Criteria andState2GreaterThan(Long value) {
            addCriterion("STATE2 >", value, "state2");
            return (Criteria) this;
        }

        public Criteria andState2GreaterThanOrEqualTo(Long value) {
            addCriterion("STATE2 >=", value, "state2");
            return (Criteria) this;
        }

        public Criteria andState2LessThan(Long value) {
            addCriterion("STATE2 <", value, "state2");
            return (Criteria) this;
        }

        public Criteria andState2LessThanOrEqualTo(Long value) {
            addCriterion("STATE2 <=", value, "state2");
            return (Criteria) this;
        }

        public Criteria andState2In(List<Long> values) {
            addCriterion("STATE2 in", values, "state2");
            return (Criteria) this;
        }

        public Criteria andState2NotIn(List<Long> values) {
            addCriterion("STATE2 not in", values, "state2");
            return (Criteria) this;
        }

        public Criteria andState2Between(Long value1, Long value2) {
            addCriterion("STATE2 between", value1, value2, "state2");
            return (Criteria) this;
        }

        public Criteria andState2NotBetween(Long value1, Long value2) {
            addCriterion("STATE2 not between", value1, value2, "state2");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("PRODUCT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("PRODUCT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("PRODUCT_NAME =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("PRODUCT_NAME <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("PRODUCT_NAME >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NAME >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("PRODUCT_NAME <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NAME <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("PRODUCT_NAME like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("PRODUCT_NAME not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("PRODUCT_NAME in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("PRODUCT_NAME not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("PRODUCT_NAME between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_NAME not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductUnitIsNull() {
            addCriterion("PRODUCT_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andProductUnitIsNotNull() {
            addCriterion("PRODUCT_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andProductUnitEqualTo(Long value) {
            addCriterion("PRODUCT_UNIT =", value, "productUnit");
            return (Criteria) this;
        }

        public Criteria andProductUnitNotEqualTo(Long value) {
            addCriterion("PRODUCT_UNIT <>", value, "productUnit");
            return (Criteria) this;
        }

        public Criteria andProductUnitGreaterThan(Long value) {
            addCriterion("PRODUCT_UNIT >", value, "productUnit");
            return (Criteria) this;
        }

        public Criteria andProductUnitGreaterThanOrEqualTo(Long value) {
            addCriterion("PRODUCT_UNIT >=", value, "productUnit");
            return (Criteria) this;
        }

        public Criteria andProductUnitLessThan(Long value) {
            addCriterion("PRODUCT_UNIT <", value, "productUnit");
            return (Criteria) this;
        }

        public Criteria andProductUnitLessThanOrEqualTo(Long value) {
            addCriterion("PRODUCT_UNIT <=", value, "productUnit");
            return (Criteria) this;
        }

        public Criteria andProductUnitIn(List<Long> values) {
            addCriterion("PRODUCT_UNIT in", values, "productUnit");
            return (Criteria) this;
        }

        public Criteria andProductUnitNotIn(List<Long> values) {
            addCriterion("PRODUCT_UNIT not in", values, "productUnit");
            return (Criteria) this;
        }

        public Criteria andProductUnitBetween(Long value1, Long value2) {
            addCriterion("PRODUCT_UNIT between", value1, value2, "productUnit");
            return (Criteria) this;
        }

        public Criteria andProductUnitNotBetween(Long value1, Long value2) {
            addCriterion("PRODUCT_UNIT not between", value1, value2, "productUnit");
            return (Criteria) this;
        }

        public Criteria andRevenueIsNull() {
            addCriterion("REVENUE is null");
            return (Criteria) this;
        }

        public Criteria andRevenueIsNotNull() {
            addCriterion("REVENUE is not null");
            return (Criteria) this;
        }

        public Criteria andRevenueEqualTo(Long value) {
            addCriterion("REVENUE =", value, "revenue");
            return (Criteria) this;
        }

        public Criteria andRevenueNotEqualTo(Long value) {
            addCriterion("REVENUE <>", value, "revenue");
            return (Criteria) this;
        }

        public Criteria andRevenueGreaterThan(Long value) {
            addCriterion("REVENUE >", value, "revenue");
            return (Criteria) this;
        }

        public Criteria andRevenueGreaterThanOrEqualTo(Long value) {
            addCriterion("REVENUE >=", value, "revenue");
            return (Criteria) this;
        }

        public Criteria andRevenueLessThan(Long value) {
            addCriterion("REVENUE <", value, "revenue");
            return (Criteria) this;
        }

        public Criteria andRevenueLessThanOrEqualTo(Long value) {
            addCriterion("REVENUE <=", value, "revenue");
            return (Criteria) this;
        }

        public Criteria andRevenueIn(List<Long> values) {
            addCriterion("REVENUE in", values, "revenue");
            return (Criteria) this;
        }

        public Criteria andRevenueNotIn(List<Long> values) {
            addCriterion("REVENUE not in", values, "revenue");
            return (Criteria) this;
        }

        public Criteria andRevenueBetween(Long value1, Long value2) {
            addCriterion("REVENUE between", value1, value2, "revenue");
            return (Criteria) this;
        }

        public Criteria andRevenueNotBetween(Long value1, Long value2) {
            addCriterion("REVENUE not between", value1, value2, "revenue");
            return (Criteria) this;
        }

        public Criteria andContractEndDateIsNull() {
            addCriterion("CONTRACT_END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andContractEndDateIsNotNull() {
            addCriterion("CONTRACT_END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andContractEndDateEqualTo(Date value) {
            addCriterion("CONTRACT_END_DATE =", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateNotEqualTo(Date value) {
            addCriterion("CONTRACT_END_DATE <>", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateGreaterThan(Date value) {
            addCriterion("CONTRACT_END_DATE >", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CONTRACT_END_DATE >=", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateLessThan(Date value) {
            addCriterion("CONTRACT_END_DATE <", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateLessThanOrEqualTo(Date value) {
            addCriterion("CONTRACT_END_DATE <=", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateIn(List<Date> values) {
            addCriterion("CONTRACT_END_DATE in", values, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateNotIn(List<Date> values) {
            addCriterion("CONTRACT_END_DATE not in", values, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateBetween(Date value1, Date value2) {
            addCriterion("CONTRACT_END_DATE between", value1, value2, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateNotBetween(Date value1, Date value2) {
            addCriterion("CONTRACT_END_DATE not between", value1, value2, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andReminderTimeIsNull() {
            addCriterion("REMINDER_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReminderTimeIsNotNull() {
            addCriterion("REMINDER_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReminderTimeEqualTo(String value) {
            addCriterion("REMINDER_TIME =", value, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeNotEqualTo(String value) {
            addCriterion("REMINDER_TIME <>", value, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeGreaterThan(String value) {
            addCriterion("REMINDER_TIME >", value, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeGreaterThanOrEqualTo(String value) {
            addCriterion("REMINDER_TIME >=", value, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeLessThan(String value) {
            addCriterion("REMINDER_TIME <", value, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeLessThanOrEqualTo(String value) {
            addCriterion("REMINDER_TIME <=", value, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeLike(String value) {
            addCriterion("REMINDER_TIME like", value, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeNotLike(String value) {
            addCriterion("REMINDER_TIME not like", value, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeIn(List<String> values) {
            addCriterion("REMINDER_TIME in", values, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeNotIn(List<String> values) {
            addCriterion("REMINDER_TIME not in", values, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeBetween(String value1, String value2) {
            addCriterion("REMINDER_TIME between", value1, value2, "reminderTime");
            return (Criteria) this;
        }

        public Criteria andReminderTimeNotBetween(String value1, String value2) {
            addCriterion("REMINDER_TIME not between", value1, value2, "reminderTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated do_not_delete_during_merge Wed May 29 10:23:13 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msm_competitor_swot
     *
     * @mbg.generated Wed May 29 10:23:13 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}