package com.aii.crm.msm.web.persistence.bo;

import java.util.Date;

public class MsmOptyCompetRela {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msm_opty_compet_rela.RELA_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    private Long relaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msm_opty_compet_rela.OPPORTUNITY_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    private Long opportunityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msm_opty_compet_rela.CUST_COMPET_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    private Long custCompetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msm_opty_compet_rela.CREATE_DATE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msm_opty_compet_rela.ORG_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msm_opty_compet_rela.OP_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    private Long opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msm_opty_compet_rela.DONE_DATE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msm_opty_compet_rela.DONE_CODE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    private String doneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msm_opty_compet_rela.STATE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    private Long state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msm_opty_compet_rela.RELA_ID
     *
     * @return the value of msm_opty_compet_rela.RELA_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public Long getRelaId() {
        return relaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msm_opty_compet_rela.RELA_ID
     *
     * @param relaId the value for msm_opty_compet_rela.RELA_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public void setRelaId(Long relaId) {
        this.relaId = relaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msm_opty_compet_rela.OPPORTUNITY_ID
     *
     * @return the value of msm_opty_compet_rela.OPPORTUNITY_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public Long getOpportunityId() {
        return opportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msm_opty_compet_rela.OPPORTUNITY_ID
     *
     * @param opportunityId the value for msm_opty_compet_rela.OPPORTUNITY_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public void setOpportunityId(Long opportunityId) {
        this.opportunityId = opportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msm_opty_compet_rela.CUST_COMPET_ID
     *
     * @return the value of msm_opty_compet_rela.CUST_COMPET_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public Long getCustCompetId() {
        return custCompetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msm_opty_compet_rela.CUST_COMPET_ID
     *
     * @param custCompetId the value for msm_opty_compet_rela.CUST_COMPET_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public void setCustCompetId(Long custCompetId) {
        this.custCompetId = custCompetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msm_opty_compet_rela.CREATE_DATE
     *
     * @return the value of msm_opty_compet_rela.CREATE_DATE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msm_opty_compet_rela.CREATE_DATE
     *
     * @param createDate the value for msm_opty_compet_rela.CREATE_DATE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msm_opty_compet_rela.ORG_ID
     *
     * @return the value of msm_opty_compet_rela.ORG_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msm_opty_compet_rela.ORG_ID
     *
     * @param orgId the value for msm_opty_compet_rela.ORG_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msm_opty_compet_rela.OP_ID
     *
     * @return the value of msm_opty_compet_rela.OP_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msm_opty_compet_rela.OP_ID
     *
     * @param opId the value for msm_opty_compet_rela.OP_ID
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msm_opty_compet_rela.DONE_DATE
     *
     * @return the value of msm_opty_compet_rela.DONE_DATE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msm_opty_compet_rela.DONE_DATE
     *
     * @param doneDate the value for msm_opty_compet_rela.DONE_DATE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msm_opty_compet_rela.DONE_CODE
     *
     * @return the value of msm_opty_compet_rela.DONE_CODE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public String getDoneCode() {
        return doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msm_opty_compet_rela.DONE_CODE
     *
     * @param doneCode the value for msm_opty_compet_rela.DONE_CODE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public void setDoneCode(String doneCode) {
        this.doneCode = doneCode == null ? null : doneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msm_opty_compet_rela.STATE
     *
     * @return the value of msm_opty_compet_rela.STATE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msm_opty_compet_rela.STATE
     *
     * @param state the value for msm_opty_compet_rela.STATE
     *
     * @mbg.generated Wed May 29 10:24:16 CST 2019
     */
    public void setState(Long state) {
        this.state = state;
    }
}