package com.aii.crm.msm.web.persistence.bo;

import java.util.Date;

public class OptOpptyCustReq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_oppty_cust_req.OPPTY_CUST_REQ_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    private Long opptyCustReqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_oppty_cust_req.CUSTOMER_REQUIREMENT_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    private Long customerRequirementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_oppty_cust_req.OPPORTUNITY_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    private Long opportunityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_oppty_cust_req.ORG_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_oppty_cust_req.OP_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    private Long opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_oppty_cust_req.DONE_DATE
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_oppty_cust_req.DONE_CODE
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    private String doneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_oppty_cust_req.STATE
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    private Long state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_oppty_cust_req.OPPTY_CUST_REQ_ID
     *
     * @return the value of opt_oppty_cust_req.OPPTY_CUST_REQ_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public Long getOpptyCustReqId() {
        return opptyCustReqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_oppty_cust_req.OPPTY_CUST_REQ_ID
     *
     * @param opptyCustReqId the value for opt_oppty_cust_req.OPPTY_CUST_REQ_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public void setOpptyCustReqId(Long opptyCustReqId) {
        this.opptyCustReqId = opptyCustReqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_oppty_cust_req.CUSTOMER_REQUIREMENT_ID
     *
     * @return the value of opt_oppty_cust_req.CUSTOMER_REQUIREMENT_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public Long getCustomerRequirementId() {
        return customerRequirementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_oppty_cust_req.CUSTOMER_REQUIREMENT_ID
     *
     * @param customerRequirementId the value for opt_oppty_cust_req.CUSTOMER_REQUIREMENT_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public void setCustomerRequirementId(Long customerRequirementId) {
        this.customerRequirementId = customerRequirementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_oppty_cust_req.OPPORTUNITY_ID
     *
     * @return the value of opt_oppty_cust_req.OPPORTUNITY_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public Long getOpportunityId() {
        return opportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_oppty_cust_req.OPPORTUNITY_ID
     *
     * @param opportunityId the value for opt_oppty_cust_req.OPPORTUNITY_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public void setOpportunityId(Long opportunityId) {
        this.opportunityId = opportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_oppty_cust_req.ORG_ID
     *
     * @return the value of opt_oppty_cust_req.ORG_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_oppty_cust_req.ORG_ID
     *
     * @param orgId the value for opt_oppty_cust_req.ORG_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_oppty_cust_req.OP_ID
     *
     * @return the value of opt_oppty_cust_req.OP_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_oppty_cust_req.OP_ID
     *
     * @param opId the value for opt_oppty_cust_req.OP_ID
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_oppty_cust_req.DONE_DATE
     *
     * @return the value of opt_oppty_cust_req.DONE_DATE
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_oppty_cust_req.DONE_DATE
     *
     * @param doneDate the value for opt_oppty_cust_req.DONE_DATE
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_oppty_cust_req.DONE_CODE
     *
     * @return the value of opt_oppty_cust_req.DONE_CODE
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public String getDoneCode() {
        return doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_oppty_cust_req.DONE_CODE
     *
     * @param doneCode the value for opt_oppty_cust_req.DONE_CODE
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public void setDoneCode(String doneCode) {
        this.doneCode = doneCode == null ? null : doneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_oppty_cust_req.STATE
     *
     * @return the value of opt_oppty_cust_req.STATE
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_oppty_cust_req.STATE
     *
     * @param state the value for opt_oppty_cust_req.STATE
     *
     * @mbg.generated Wed May 29 10:29:13 CST 2019
     */
    public void setState(Long state) {
        this.state = state;
    }
}