package com.aii.crm.msm.web.persistence.bo;

import java.util.Date;

public class OptSalesProposal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.SALES_PROPOSAL_ID
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private Long salesProposalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.PROPOSAL_NAME
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private String proposalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.IS_LEGAL
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private String isLegal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.DESCRIPTION
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.ESTIMATE_ARPU
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private Long estimateArpu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.ESTIMATE_PRICE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private Long estimatePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.ESTIMATE_WAVIER_PRICE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private Long estimateWavierPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.CREATE_DATE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.ORG_ID
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.OP_ID
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private Long opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.DONE_DATE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.DONE_CODE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private String doneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_sales_proposal.STATE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    private Long state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.SALES_PROPOSAL_ID
     *
     * @return the value of opt_sales_proposal.SALES_PROPOSAL_ID
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public Long getSalesProposalId() {
        return salesProposalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.SALES_PROPOSAL_ID
     *
     * @param salesProposalId the value for opt_sales_proposal.SALES_PROPOSAL_ID
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setSalesProposalId(Long salesProposalId) {
        this.salesProposalId = salesProposalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.PROPOSAL_NAME
     *
     * @return the value of opt_sales_proposal.PROPOSAL_NAME
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public String getProposalName() {
        return proposalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.PROPOSAL_NAME
     *
     * @param proposalName the value for opt_sales_proposal.PROPOSAL_NAME
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setProposalName(String proposalName) {
        this.proposalName = proposalName == null ? null : proposalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.IS_LEGAL
     *
     * @return the value of opt_sales_proposal.IS_LEGAL
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public String getIsLegal() {
        return isLegal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.IS_LEGAL
     *
     * @param isLegal the value for opt_sales_proposal.IS_LEGAL
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setIsLegal(String isLegal) {
        this.isLegal = isLegal == null ? null : isLegal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.DESCRIPTION
     *
     * @return the value of opt_sales_proposal.DESCRIPTION
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.DESCRIPTION
     *
     * @param description the value for opt_sales_proposal.DESCRIPTION
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.ESTIMATE_ARPU
     *
     * @return the value of opt_sales_proposal.ESTIMATE_ARPU
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public Long getEstimateArpu() {
        return estimateArpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.ESTIMATE_ARPU
     *
     * @param estimateArpu the value for opt_sales_proposal.ESTIMATE_ARPU
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setEstimateArpu(Long estimateArpu) {
        this.estimateArpu = estimateArpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.ESTIMATE_PRICE
     *
     * @return the value of opt_sales_proposal.ESTIMATE_PRICE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public Long getEstimatePrice() {
        return estimatePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.ESTIMATE_PRICE
     *
     * @param estimatePrice the value for opt_sales_proposal.ESTIMATE_PRICE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setEstimatePrice(Long estimatePrice) {
        this.estimatePrice = estimatePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.ESTIMATE_WAVIER_PRICE
     *
     * @return the value of opt_sales_proposal.ESTIMATE_WAVIER_PRICE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public Long getEstimateWavierPrice() {
        return estimateWavierPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.ESTIMATE_WAVIER_PRICE
     *
     * @param estimateWavierPrice the value for opt_sales_proposal.ESTIMATE_WAVIER_PRICE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setEstimateWavierPrice(Long estimateWavierPrice) {
        this.estimateWavierPrice = estimateWavierPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.CREATE_DATE
     *
     * @return the value of opt_sales_proposal.CREATE_DATE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.CREATE_DATE
     *
     * @param createDate the value for opt_sales_proposal.CREATE_DATE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.ORG_ID
     *
     * @return the value of opt_sales_proposal.ORG_ID
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.ORG_ID
     *
     * @param orgId the value for opt_sales_proposal.ORG_ID
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.OP_ID
     *
     * @return the value of opt_sales_proposal.OP_ID
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.OP_ID
     *
     * @param opId the value for opt_sales_proposal.OP_ID
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.DONE_DATE
     *
     * @return the value of opt_sales_proposal.DONE_DATE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.DONE_DATE
     *
     * @param doneDate the value for opt_sales_proposal.DONE_DATE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.DONE_CODE
     *
     * @return the value of opt_sales_proposal.DONE_CODE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public String getDoneCode() {
        return doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.DONE_CODE
     *
     * @param doneCode the value for opt_sales_proposal.DONE_CODE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setDoneCode(String doneCode) {
        this.doneCode = doneCode == null ? null : doneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_sales_proposal.STATE
     *
     * @return the value of opt_sales_proposal.STATE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_sales_proposal.STATE
     *
     * @param state the value for opt_sales_proposal.STATE
     *
     * @mbg.generated Wed May 29 10:31:38 CST 2019
     */
    public void setState(Long state) {
        this.state = state;
    }
}