package com.aii.crm.msm.web.persistence.mapper;

import com.aii.crm.msm.web.persistence.bo.MsmCustAssimt;
import com.aii.crm.msm.web.persistence.bo.MsmCustAssimtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsmCustAssimtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    long countByExample(MsmCustAssimtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    int deleteByExample(MsmCustAssimtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    int deleteByPrimaryKey(Long custAssimtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    int insert(MsmCustAssimt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    int insertSelective(MsmCustAssimt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    List<MsmCustAssimt> selectByExample(MsmCustAssimtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    MsmCustAssimt selectByPrimaryKey(Long custAssimtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") MsmCustAssimt record, @Param("example") MsmCustAssimtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    int updateByExample(@Param("record") MsmCustAssimt record, @Param("example") MsmCustAssimtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    int updateByPrimaryKeySelective(MsmCustAssimt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_cust_assimt
     *
     * @mbg.generated Wed May 29 10:23:28 CST 2019
     */
    int updateByPrimaryKey(MsmCustAssimt record);
}