package com.aii.crm.msm.web.persistence.mapper;

import com.aii.crm.msm.web.persistence.bo.MsmOperatorInOrg;
import com.aii.crm.msm.web.persistence.bo.MsmOperatorInOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsmOperatorInOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    long countByExample(MsmOperatorInOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    int deleteByExample(MsmOperatorInOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    int deleteByPrimaryKey(Long operatorInOrgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    int insert(MsmOperatorInOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    int insertSelective(MsmOperatorInOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    List<MsmOperatorInOrg> selectByExample(MsmOperatorInOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    MsmOperatorInOrg selectByPrimaryKey(Long operatorInOrgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") MsmOperatorInOrg record, @Param("example") MsmOperatorInOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    int updateByExample(@Param("record") MsmOperatorInOrg record, @Param("example") MsmOperatorInOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    int updateByPrimaryKeySelective(MsmOperatorInOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msm_operator_in_org
     *
     * @mbg.generated Wed May 29 10:23:49 CST 2019
     */
    int updateByPrimaryKey(MsmOperatorInOrg record);
}