package com.aii.crm.msm.web.persistence.mapper;

import com.aii.crm.msm.web.persistence.bo.OptFunnelLyrOppty;
import com.aii.crm.msm.web.persistence.bo.OptFunnelLyrOpptyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptFunnelLyrOpptyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    long countByExample(OptFunnelLyrOpptyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    int deleteByExample(OptFunnelLyrOpptyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    int deleteByPrimaryKey(Long funnelLayerStateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    int insert(OptFunnelLyrOppty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    int insertSelective(OptFunnelLyrOppty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    List<OptFunnelLyrOppty> selectByExample(OptFunnelLyrOpptyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    OptFunnelLyrOppty selectByPrimaryKey(Long funnelLayerStateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") OptFunnelLyrOppty record, @Param("example") OptFunnelLyrOpptyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    int updateByExample(@Param("record") OptFunnelLyrOppty record, @Param("example") OptFunnelLyrOpptyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    int updateByPrimaryKeySelective(OptFunnelLyrOppty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_funnel_lyr_oppty
     *
     * @mbg.generated Wed May 29 10:26:50 CST 2019
     */
    int updateByPrimaryKey(OptFunnelLyrOppty record);
}