package com.aii.crm.msm.web.persistence.mapper;

import com.aii.crm.msm.web.persistence.bo.OptLeadAssimt;
import com.aii.crm.msm.web.persistence.bo.OptLeadAssimtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptLeadAssimtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    long countByExample(OptLeadAssimtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    int deleteByExample(OptLeadAssimtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    int insert(OptLeadAssimt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    int insertSelective(OptLeadAssimt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    List<OptLeadAssimt> selectByExample(OptLeadAssimtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    OptLeadAssimt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") OptLeadAssimt record, @Param("example") OptLeadAssimtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    int updateByExample(@Param("record") OptLeadAssimt record, @Param("example") OptLeadAssimtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    int updateByPrimaryKeySelective(OptLeadAssimt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_lead_assimt
     *
     * @mbg.generated Wed May 29 10:28:02 CST 2019
     */
    int updateByPrimaryKey(OptLeadAssimt record);
}