package com.aii.crm.msm.web.persistence.mapper;

import com.aii.crm.msm.web.persistence.bo.OptProposeResource;
import com.aii.crm.msm.web.persistence.bo.OptProposeResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptProposeResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    long countByExample(OptProposeResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    int deleteByExample(OptProposeResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    int deleteByPrimaryKey(Long proposeResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    int insert(OptProposeResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    int insertSelective(OptProposeResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    List<OptProposeResource> selectByExample(OptProposeResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    OptProposeResource selectByPrimaryKey(Long proposeResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") OptProposeResource record, @Param("example") OptProposeResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    int updateByExample(@Param("record") OptProposeResource record, @Param("example") OptProposeResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    int updateByPrimaryKeySelective(OptProposeResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_propose_resource
     *
     * @mbg.generated Wed May 29 10:30:48 CST 2019
     */
    int updateByPrimaryKey(OptProposeResource record);
}