package com.aii.crm.msm.web.persistence.mapper;

import com.aii.crm.msm.web.persistence.bo.OptProposalDoc;
import com.aii.crm.msm.web.persistence.bo.OptProposalDocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptProposalDocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    long countByExample(OptProposalDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    int deleteByExample(OptProposalDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    int deleteByPrimaryKey(Long proposalDocumentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    int insert(OptProposalDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    int insertSelective(OptProposalDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    List<OptProposalDoc> selectByExample(OptProposalDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    OptProposalDoc selectByPrimaryKey(Long proposalDocumentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") OptProposalDoc record, @Param("example") OptProposalDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    int updateByExample(@Param("record") OptProposalDoc record, @Param("example") OptProposalDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    int updateByPrimaryKeySelective(OptProposalDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_proposal_doc
     *
     * @mbg.generated Wed May 29 10:30:20 CST 2019
     */
    int updateByPrimaryKey(OptProposalDoc record);
}