package com.aii.crm.msm.web.persistence.mapper;

import com.aii.crm.msm.web.persistence.bo.OptStaticCodeEnum;
import com.aii.crm.msm.web.persistence.bo.OptStaticCodeEnumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptStaticCodeEnumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    long countByExample(OptStaticCodeEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    int deleteByExample(OptStaticCodeEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    int deleteByPrimaryKey(Long codeEnumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    int insert(OptStaticCodeEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    int insertSelective(OptStaticCodeEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    List<OptStaticCodeEnum> selectByExample(OptStaticCodeEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    OptStaticCodeEnum selectByPrimaryKey(Long codeEnumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") OptStaticCodeEnum record, @Param("example") OptStaticCodeEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    int updateByExample(@Param("record") OptStaticCodeEnum record, @Param("example") OptStaticCodeEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    int updateByPrimaryKeySelective(OptStaticCodeEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_static_code_enum
     *
     * @mbg.generated Wed May 29 10:31:59 CST 2019
     */
    int updateByPrimaryKey(OptStaticCodeEnum record);
}