package com.aii.crm.msm.web.persistence.mapper;

import com.aii.crm.msm.web.persistence.bo.OptSaleleadImpLog;
import com.aii.crm.msm.web.persistence.bo.OptSaleleadImpLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptSaleleadImpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    long countByExample(OptSaleleadImpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    int deleteByExample(OptSaleleadImpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    int insert(OptSaleleadImpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    int insertSelective(OptSaleleadImpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    List<OptSaleleadImpLog> selectByExample(OptSaleleadImpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    OptSaleleadImpLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") OptSaleleadImpLog record, @Param("example") OptSaleleadImpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    int updateByExample(@Param("record") OptSaleleadImpLog record, @Param("example") OptSaleleadImpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    int updateByPrimaryKeySelective(OptSaleleadImpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_salelead_imp_log
     *
     * @mbg.generated Wed May 29 10:31:06 CST 2019
     */
    int updateByPrimaryKey(OptSaleleadImpLog record);
}