package com.aii.crm.msm.web.persistence.mapper;

import com.aii.crm.msm.web.persistence.bo.OptTaskImpLog;
import com.aii.crm.msm.web.persistence.bo.OptTaskImpLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptTaskImpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    long countByExample(OptTaskImpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    int deleteByExample(OptTaskImpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    int insert(OptTaskImpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    int insertSelective(OptTaskImpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    List<OptTaskImpLog> selectByExample(OptTaskImpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    OptTaskImpLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") OptTaskImpLog record, @Param("example") OptTaskImpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    int updateByExample(@Param("record") OptTaskImpLog record, @Param("example") OptTaskImpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    int updateByPrimaryKeySelective(OptTaskImpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_task_imp_log
     *
     * @mbg.generated Wed May 29 10:32:30 CST 2019
     */
    int updateByPrimaryKey(OptTaskImpLog record);
}