/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 5.6.36-82.0-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `notice_msg_order` (`notice_id`, `notice_channel`, `notice_type`, `notice_subject`, `notice_from`, `notice_from_name`, `notice_to`, `notice_cc`, `notice_bcc`, `notice_template_code`, `notice_template_lang`, `notice_create_date`, `notice_effect_time`, `notice_send_time`, `notice_status`, `notice_description`, `notice_tenant`, `notice_send_count`, `notice_content_id`) values('3','1','2','测试发送邮件111',NULL,'测试111','qinay@asiainfo.sg','qinay@asiainfo.sg','qinay@asiainfo.sg','A001','EN','2019-04-18 06:38:53','2019-04-18 06:38:53','2019-04-18 06:39:03','2','测试',NULL,'2','15');
insert into `notice_msg_order` (`notice_id`, `notice_channel`, `notice_type`, `notice_subject`, `notice_from`, `notice_from_name`, `notice_to`, `notice_cc`, `notice_bcc`, `notice_template_code`, `notice_template_lang`, `notice_create_date`, `notice_effect_time`, `notice_send_time`, `notice_status`, `notice_description`, `notice_tenant`, `notice_send_count`, `notice_content_id`) values('4','1','2','测试发送邮件222',NULL,'测试222','qinay@asiainfo.sg','qinay@asiainfo.sg','qinay@asiainfo.sg','A001','EN','2019-04-18 06:40:28','2019-04-18 06:40:28','2019-04-18 06:40:32','2','测试',NULL,'2','16');
insert into `notice_msg_order` (`notice_id`, `notice_channel`, `notice_type`, `notice_subject`, `notice_from`, `notice_from_name`, `notice_to`, `notice_cc`, `notice_bcc`, `notice_template_code`, `notice_template_lang`, `notice_create_date`, `notice_effect_time`, `notice_send_time`, `notice_status`, `notice_description`, `notice_tenant`, `notice_send_count`, `notice_content_id`) values('5','1','2','测试发送邮件555',NULL,'测试555','qinay@asiainfo.sg','qinay@asiainfo.sg','qinay@asiainfo.sg','A001','EN','2019-04-18 06:49:51','2019-04-18 06:49:51','2019-04-18 06:50:03','2','测试',NULL,'2','19');
insert into `notice_msg_order` (`notice_id`, `notice_channel`, `notice_type`, `notice_subject`, `notice_from`, `notice_from_name`, `notice_to`, `notice_cc`, `notice_bcc`, `notice_template_code`, `notice_template_lang`, `notice_create_date`, `notice_effect_time`, `notice_send_time`, `notice_status`, `notice_description`, `notice_tenant`, `notice_send_count`, `notice_content_id`) values('6','1','2','测试发送邮件666',NULL,'测试666','qinay@asiainfo.sg','qinay@asiainfo.sg','qinay@asiainfo.sg','A001','EN','2019-04-18 07:00:31','2019-04-18 07:00:31','2019-04-18 07:00:43','2','测试',NULL,'1','20');
insert into `notice_msg_order` (`notice_id`, `notice_channel`, `notice_type`, `notice_subject`, `notice_from`, `notice_from_name`, `notice_to`, `notice_cc`, `notice_bcc`, `notice_template_code`, `notice_template_lang`, `notice_create_date`, `notice_effect_time`, `notice_send_time`, `notice_status`, `notice_description`, `notice_tenant`, `notice_send_count`, `notice_content_id`) values('7','1','2','测试发送邮件777',NULL,'测试777','qinay@asiainfo.sg','qinay@asiainfo.sg','qinay@asiainfo.sg',NULL,'EN','2019-04-18 07:07:24','2019-04-18 07:07:24','2019-04-18 07:07:32','2','测试',NULL,'1','21');
insert into `notice_msg_order` (`notice_id`, `notice_channel`, `notice_type`, `notice_subject`, `notice_from`, `notice_from_name`, `notice_to`, `notice_cc`, `notice_bcc`, `notice_template_code`, `notice_template_lang`, `notice_create_date`, `notice_effect_time`, `notice_send_time`, `notice_status`, `notice_description`, `notice_tenant`, `notice_send_count`, `notice_content_id`) values('8','1','2','测试发送邮件1213',NULL,'测试1213','qinay@asiainfo.sg','qinay@asiainfo.sg','qinay@asiainfo.sg',NULL,'EN','2019-04-18 22:56:04','2019-04-18 22:56:04','2019-04-18 22:57:16','2','测试',NULL,'5','28');
