debug: true
server:
  port: 15151
spring:
  application:
    name: order
  main:
    allow-bean-definition-overriding: true
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    cluster:
      nodes: 10.21.14.164:6381,10.21.14.164:6382,10.21.14.165:6381,10.21.14.165:6382,10.21.14.166:6381,10.21.14.166:6382
  shardingsphere:
    datasource:
      name: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.21.14.160:3306/ord?serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: Huawei@123
    sharding:
      defaultDataSourceName: ds0
    props:
      sql:
        show: true
# mybatis-spring-boot-starter
mybatis:
  type-aliases-package: com.ai.order
  mapper-locations: classpath:com/ai/order/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
# pagehelper-spring-boot-starter
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql