package com.aii.crm.cache.web.persistence.mapper;

import com.aii.crm.cache.web.persistence.bo.BsDistrict;
import com.aii.crm.cache.web.persistence.bo.BsDistrictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    long countByExample(BsDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    int deleteByExample(BsDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    int deleteByPrimaryKey(Long districtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    int insert(BsDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    int insertSelective(BsDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    List<BsDistrict> selectByExample(BsDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    BsDistrict selectByPrimaryKey(Long districtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") BsDistrict record, @Param("example") BsDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    int updateByExample(@Param("record") BsDistrict record, @Param("example") BsDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    int updateByPrimaryKeySelective(BsDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_district
     *
     * @mbg.generated Mon May 20 09:46:08 CST 2019
     */
    int updateByPrimaryKey(BsDistrict record);
}