package com.aii.crm.cache.web.persistence.mapper;

import com.aii.crm.cache.web.persistence.bo.CfgMsgClient;
import com.aii.crm.cache.web.persistence.bo.CfgMsgClientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgMsgClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    long countByExample(CfgMsgClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    int deleteByExample(CfgMsgClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    int deleteByPrimaryKey(String cfgMsgControlCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    int insert(CfgMsgClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    int insertSelective(CfgMsgClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    List<CfgMsgClient> selectByExample(CfgMsgClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    CfgMsgClient selectByPrimaryKey(String cfgMsgControlCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") CfgMsgClient record, @Param("example") CfgMsgClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    int updateByExample(@Param("record") CfgMsgClient record, @Param("example") CfgMsgClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    int updateByPrimaryKeySelective(CfgMsgClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_msg_client
     *
     * @mbg.generated Tue May 21 10:32:15 CST 2019
     */
    int updateByPrimaryKey(CfgMsgClient record);
}