package com.aii.crm.cm.web.persistence.mapper;

import com.aii.crm.cm.web.persistence.bo.CmCustContactMedium;
import com.aii.crm.cm.web.persistence.bo.CmCustContactMediumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmCustContactMediumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    long countByExample(CmCustContactMediumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    int deleteByExample(CmCustContactMediumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    int deleteByPrimaryKey(Long custContRelaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    int insert(CmCustContactMedium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    int insertSelective(CmCustContactMedium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    List<CmCustContactMedium> selectByExample(CmCustContactMediumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    CmCustContactMedium selectByPrimaryKey(Long custContRelaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmCustContactMedium record, @Param("example") CmCustContactMediumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    int updateByExample(@Param("record") CmCustContactMedium record, @Param("example") CmCustContactMediumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    int updateByPrimaryKeySelective(CmCustContactMedium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium
     *
     * @mbg.generated Tue May 28 20:11:35 CST 2019
     */
    int updateByPrimaryKey(CmCustContactMedium record);
}