package com.aii.crm.cm.web.persistence.mapper;

import com.aii.crm.cm.web.persistence.bo.CmCustContactMediumH;
import com.aii.crm.cm.web.persistence.bo.CmCustContactMediumHExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmCustContactMediumHMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    long countByExample(CmCustContactMediumHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    int deleteByExample(CmCustContactMediumHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    int deleteByPrimaryKey(Long hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    int insert(CmCustContactMediumH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    int insertSelective(CmCustContactMediumH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    List<CmCustContactMediumH> selectByExample(CmCustContactMediumHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    CmCustContactMediumH selectByPrimaryKey(Long hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmCustContactMediumH record, @Param("example") CmCustContactMediumHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    int updateByExample(@Param("record") CmCustContactMediumH record, @Param("example") CmCustContactMediumHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    int updateByPrimaryKeySelective(CmCustContactMediumH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_contact_medium_h
     *
     * @mbg.generated Tue May 28 20:11:57 CST 2019
     */
    int updateByPrimaryKey(CmCustContactMediumH record);
}