package com.aii.crm.cm.web.persistence.mapper;

import com.aii.crm.cm.web.persistence.bo.CmCustAcctRel;
import com.aii.crm.cm.web.persistence.bo.CmCustAcctRelExample;
import com.aii.crm.cm.web.persistence.bo.CmCustAcctRelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmCustAcctRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    long countByExample(CmCustAcctRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    int deleteByExample(CmCustAcctRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    int deleteByPrimaryKey(CmCustAcctRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    int insert(CmCustAcctRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    int insertSelective(CmCustAcctRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    List<CmCustAcctRel> selectByExample(CmCustAcctRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    CmCustAcctRel selectByPrimaryKey(CmCustAcctRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmCustAcctRel record, @Param("example") CmCustAcctRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    int updateByExample(@Param("record") CmCustAcctRel record, @Param("example") CmCustAcctRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    int updateByPrimaryKeySelective(CmCustAcctRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_acct_rel
     *
     * @mbg.generated Tue May 28 20:08:19 CST 2019
     */
    int updateByPrimaryKey(CmCustAcctRel record);
}