package com.aii.crm.cm.web.persistence.mapper;

import com.aii.crm.cm.web.persistence.bo.CmCustContMedTypeH;
import com.aii.crm.cm.web.persistence.bo.CmCustContMedTypeHExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmCustContMedTypeHMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    long countByExample(CmCustContMedTypeHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    int deleteByExample(CmCustContMedTypeHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    int deleteByPrimaryKey(Long hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    int insert(CmCustContMedTypeH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    int insertSelective(CmCustContMedTypeH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    List<CmCustContMedTypeH> selectByExample(CmCustContMedTypeHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    CmCustContMedTypeH selectByPrimaryKey(Long hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmCustContMedTypeH record, @Param("example") CmCustContMedTypeHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    int updateByExample(@Param("record") CmCustContMedTypeH record, @Param("example") CmCustContMedTypeHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    int updateByPrimaryKeySelective(CmCustContMedTypeH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_cont_med_type_h
     *
     * @mbg.generated Tue May 28 20:11:22 CST 2019
     */
    int updateByPrimaryKey(CmCustContMedTypeH record);
}