package com.aii.crm.cm.web.persistence.mapper;

import com.aii.crm.cm.web.persistence.bo.CmCustSegmentRela;
import com.aii.crm.cm.web.persistence.bo.CmCustSegmentRelaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmCustSegmentRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    long countByExample(CmCustSegmentRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    int deleteByExample(CmCustSegmentRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    int deleteByPrimaryKey(Long relaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    int insert(CmCustSegmentRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    int insertSelective(CmCustSegmentRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    List<CmCustSegmentRela> selectByExample(CmCustSegmentRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    CmCustSegmentRela selectByPrimaryKey(Long relaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmCustSegmentRela record, @Param("example") CmCustSegmentRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    int updateByExample(@Param("record") CmCustSegmentRela record, @Param("example") CmCustSegmentRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    int updateByPrimaryKeySelective(CmCustSegmentRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_cust_segment_rela
     *
     * @mbg.generated Tue May 28 20:13:28 CST 2019
     */
    int updateByPrimaryKey(CmCustSegmentRela record);
}