package com.aii.crm.cm.web.persistence.mapper;

import com.aii.crm.cm.web.persistence.bo.CmGroupCustomerAudit;
import com.aii.crm.cm.web.persistence.bo.CmGroupCustomerAuditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmGroupCustomerAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    long countByExample(CmGroupCustomerAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    int deleteByExample(CmGroupCustomerAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    int deleteByPrimaryKey(Long auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    int insert(CmGroupCustomerAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    int insertSelective(CmGroupCustomerAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    List<CmGroupCustomerAudit> selectByExample(CmGroupCustomerAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    CmGroupCustomerAudit selectByPrimaryKey(Long auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmGroupCustomerAudit record, @Param("example") CmGroupCustomerAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    int updateByExample(@Param("record") CmGroupCustomerAudit record, @Param("example") CmGroupCustomerAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    int updateByPrimaryKeySelective(CmGroupCustomerAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_customer_audit
     *
     * @mbg.generated Tue May 28 20:23:35 CST 2019
     */
    int updateByPrimaryKey(CmGroupCustomerAudit record);
}