package com.aii.crm.cm.web.persistence.mapper;

import com.aii.crm.cm.web.persistence.bo.CmGroupAccounting;
import com.aii.crm.cm.web.persistence.bo.CmGroupAccountingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmGroupAccountingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    long countByExample(CmGroupAccountingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    int deleteByExample(CmGroupAccountingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    int deleteByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    int insert(CmGroupAccounting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    int insertSelective(CmGroupAccounting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    List<CmGroupAccounting> selectByExample(CmGroupAccountingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    CmGroupAccounting selectByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmGroupAccounting record, @Param("example") CmGroupAccountingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    int updateByExample(@Param("record") CmGroupAccounting record, @Param("example") CmGroupAccountingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    int updateByPrimaryKeySelective(CmGroupAccounting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_group_accounting
     *
     * @mbg.generated Tue May 28 20:14:30 CST 2019
     */
    int updateByPrimaryKey(CmGroupAccounting record);
}