package com.aii.crm.cm.web.persistence.mapper;

import com.aii.crm.cm.web.persistence.bo.CmIndivPartyH;
import com.aii.crm.cm.web.persistence.bo.CmIndivPartyHExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmIndivPartyHMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    long countByExample(CmIndivPartyHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    int deleteByExample(CmIndivPartyHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    int deleteByPrimaryKey(Long hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    int insert(CmIndivPartyH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    int insertSelective(CmIndivPartyH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    List<CmIndivPartyH> selectByExample(CmIndivPartyHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    CmIndivPartyH selectByPrimaryKey(Long hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmIndivPartyH record, @Param("example") CmIndivPartyHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    int updateByExample(@Param("record") CmIndivPartyH record, @Param("example") CmIndivPartyHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    int updateByPrimaryKeySelective(CmIndivPartyH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_indiv_party_h
     *
     * @mbg.generated Tue May 28 20:29:21 CST 2019
     */
    int updateByPrimaryKey(CmIndivPartyH record);
}