package com.aii.crm.cm.web.persistence.mapper;

import com.aii.crm.cm.web.persistence.bo.CmPartyRole;
import com.aii.crm.cm.web.persistence.bo.CmPartyRoleExample;
import com.aii.crm.cm.web.persistence.bo.CmPartyRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmPartyRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    long countByExample(CmPartyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    int deleteByExample(CmPartyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    int deleteByPrimaryKey(CmPartyRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    int insert(CmPartyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    int insertSelective(CmPartyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    List<CmPartyRole> selectByExample(CmPartyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    CmPartyRole selectByPrimaryKey(CmPartyRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmPartyRole record, @Param("example") CmPartyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    int updateByExample(@Param("record") CmPartyRole record, @Param("example") CmPartyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    int updateByPrimaryKeySelective(CmPartyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_role
     *
     * @mbg.generated Tue May 28 20:32:48 CST 2019
     */
    int updateByPrimaryKey(CmPartyRole record);
}