package com.aii.crm.cm.web.persistence.mapper;

import com.aii.crm.cm.web.persistence.bo.CmPartyAcctRel;
import com.aii.crm.cm.web.persistence.bo.CmPartyAcctRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmPartyAcctRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    long countByExample(CmPartyAcctRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    int deleteByExample(CmPartyAcctRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    int deleteByPrimaryKey(Long relId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    int insert(CmPartyAcctRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    int insertSelective(CmPartyAcctRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    List<CmPartyAcctRel> selectByExample(CmPartyAcctRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    CmPartyAcctRel selectByPrimaryKey(Long relId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmPartyAcctRel record, @Param("example") CmPartyAcctRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    int updateByExample(@Param("record") CmPartyAcctRel record, @Param("example") CmPartyAcctRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    int updateByPrimaryKeySelective(CmPartyAcctRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_party_acct_rel
     *
     * @mbg.generated Tue May 28 20:31:14 CST 2019
     */
    int updateByPrimaryKey(CmPartyAcctRel record);
}