package com.aii.crm.ci.web.persistence.mapper;

import com.aii.crm.ci.web.persistence.bo.CiChannelMapping;
import com.aii.crm.ci.web.persistence.bo.CiChannelMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CiChannelMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    long countByExample(CiChannelMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    int deleteByExample(CiChannelMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    int deleteByPrimaryKey(Long chnlMappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    int insert(CiChannelMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    int insertSelective(CiChannelMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    List<CiChannelMapping> selectByExample(CiChannelMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    CiChannelMapping selectByPrimaryKey(Long chnlMappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") CiChannelMapping record, @Param("example") CiChannelMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    int updateByExample(@Param("record") CiChannelMapping record, @Param("example") CiChannelMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    int updateByPrimaryKeySelective(CiChannelMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ci_channel_mapping
     *
     * @mbg.generated Tue May 21 15:46:30 CST 2019
     */
    int updateByPrimaryKey(CiChannelMapping record);
}