/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 5.7.24-log : Database - agr
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`agr` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `agr`;

/*Table structure for table `agr_agreement` */

DROP TABLE IF EXISTS `agr_agreement`;

CREATE TABLE `agr_agreement` (
  `AGREEMENT_ID` bigint(12) NOT NULL,
  `AGREEMENT_TEMPLATE_ID` bigint(12) DEFAULT NULL,
  `AGREEMENT_TEMP_CODE` varchar(128) DEFAULT NULL,
  `AGR_BAR_CODE` varchar(128) DEFAULT NULL,
  `UP_AGREEMENT_ID` bigint(12) DEFAULT NULL,
  `AGR_TYPE_ID` bigint(12) DEFAULT NULL,
  `AGREEMENT_NAME` varchar(255) DEFAULT NULL,
  `AGREEMENT_CODE` varchar(128) DEFAULT NULL,
  `OWNER_ID` bigint(15) DEFAULT NULL,
  `AUTO_RENEW` varchar(3) DEFAULT NULL,
  `RENEW_CIRCLE` varchar(3) DEFAULT NULL,
  `AGR_LEVEL_ID` bigint(12) DEFAULT NULL,
  `SECRECY_LEVEL` varchar(3) DEFAULT NULL,
  `SIGN_TIME` datetime DEFAULT NULL,
  `SIGN_PLACE` varchar(128) DEFAULT NULL,
  `AGR_DOC_URL` varchar(1024) DEFAULT NULL,
  `DESCRIPTION` varchar(256) DEFAULT NULL,
  `AGR_SOURCE` varchar(3) DEFAULT NULL,
  `AGR_SOURCE_OBJ_ID` bigint(12) DEFAULT NULL,
  `AGR_SOURCE_BIZ_ID` varchar(128) DEFAULT NULL,
  `EFF_DATE` datetime DEFAULT NULL,
  `EXP_DATE` datetime DEFAULT NULL,
  `AGREEMENT_STATUS` bigint(12) DEFAULT NULL,
  `STATUS_TIME` datetime DEFAULT NULL,
  `PARENT_CREATE_DATE` datetime DEFAULT NULL,
  `EMAIL_STATUS` varchar(3) DEFAULT NULL,
  `BREACH_STATUS` varchar(3) DEFAULT NULL,
  `IS_ADDENDUM` bigint(1) DEFAULT NULL,
  `RENEW_TIMES` bigint(12) DEFAULT NULL,
  `OPERATOR_ID` bigint(12) DEFAULT NULL,
  `ORGANIZATION_ID` bigint(12) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `CREATE_OP_ID` bigint(12) DEFAULT NULL,
  `CREATE_ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `OWNER_TYPE` varchar(3) DEFAULT NULL,
  `AGR_SOURCE_SUB_OBJ_ID` varchar(32) DEFAULT NULL,
  `AGR_TEMP_VERSION_ID` bigint(12) DEFAULT NULL,
  `BILL_CYCLE` char(1) DEFAULT NULL,
  `PAYMENT_TERMS` varchar(2) DEFAULT NULL,
  `BILL_NO` varchar(30) DEFAULT NULL,
  `CVR_NO` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`AGREEMENT_ID`),
  KEY `IDX_AGR_AGREEMENT_01` (`AGREEMENT_CODE`),
  KEY `IDX_AGR_AGREEMENT_02` (`AGR_LEVEL_ID`,`AGREEMENT_STATUS`),
  KEY `IDX_AGR_AGREEMENT_03` (`OWNER_ID`),
  KEY `IDX_AGR_AGREEMENT_04` (`CREATE_DATE`),
  KEY `IDX_AGR_AGREEMENT_05` (`CREATE_OP_ID`),
  KEY `IDX_AGR_AGREEMENT_06` (`CREATE_ORG_ID`),
  KEY `IDX_AGR_AGREEMENT_07` (`AGR_SOURCE_OBJ_ID`),
  KEY `IDX_AGR_AGREEMENT_08` (`AGR_BAR_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `agr_agreement_h` */

DROP TABLE IF EXISTS `agr_agreement_h`;

CREATE TABLE `agr_agreement_h` (
  `AGREEMENT_HIS_ID` bigint(12) NOT NULL,
  `AGREEMENT_ID` bigint(12) DEFAULT NULL,
  `AGR_VERSION_ID` bigint(12) DEFAULT NULL,
  `AGR_VERSION_CODE` varchar(128) DEFAULT NULL,
  `AGREEMENT_TEMPLATE_ID` bigint(12) DEFAULT NULL,
  `AGREEMENT_TEMP_CODE` varchar(128) DEFAULT NULL,
  `UP_AGREEMENT_ID` bigint(12) DEFAULT NULL,
  `AGR_TYPE_ID` bigint(12) DEFAULT NULL,
  `AGREEMENT_NAME` varchar(255) DEFAULT NULL,
  `AGREEMENT_CODE` varchar(128) DEFAULT NULL,
  `AUTO_RENEW` varchar(3) DEFAULT NULL,
  `AGR_LEVEL_ID` bigint(12) DEFAULT NULL,
  `SECRECY_LEVEL` varchar(3) DEFAULT NULL,
  `SIGN_TIME` datetime DEFAULT NULL,
  `SIGN_PLACE` varchar(128) DEFAULT NULL,
  `AGR_DOC_URL` varchar(1024) DEFAULT NULL,
  `DESCRIPTION` varchar(256) DEFAULT NULL,
  `AGR_SOURCE` varchar(3) DEFAULT NULL,
  `AGR_SOURCE_OBJ_ID` bigint(12) DEFAULT NULL,
  `EFF_DATE` datetime DEFAULT NULL,
  `EXP_DATE` datetime DEFAULT NULL,
  `AGREEMENT_STATUS` bigint(12) DEFAULT NULL,
  `STATUS_TIME` datetime DEFAULT NULL,
  `PARENT_CREATE_DATE` datetime DEFAULT NULL,
  `OPERATOR_ID` bigint(12) DEFAULT NULL,
  `ORGANIZATION_ID` bigint(12) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `CREATE_OP_ID` bigint(12) DEFAULT NULL,
  `CREATE_ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `AGR_BAR_CODE` varchar(128) DEFAULT NULL,
  `RENEW_CIRCLE` varchar(3) DEFAULT NULL,
  `AGR_SOURCE_BIZ_ID` varchar(128) DEFAULT NULL,
  `IS_ADDENDUM` bigint(1) DEFAULT NULL,
  `OWNER_ID` bigint(15) DEFAULT NULL,
  `EMAIL_STATUS` varchar(3) DEFAULT NULL,
  `BREACH_STATUS` varchar(3) DEFAULT NULL,
  `RENEW_TIMES` bigint(12) DEFAULT NULL,
  `OWNER_TYPE` varchar(3) DEFAULT NULL,
  `AGR_TEMP_VERSION_ID` bigint(12) DEFAULT NULL,
  `IS_NEWVER` varchar(3) DEFAULT NULL,
  `BILL_CYCLE` char(1) DEFAULT NULL,
  `PAYMENT_TERMS` varchar(2) DEFAULT NULL,
  `BILL_NO` varchar(30) DEFAULT NULL,
  `CVR_NO` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`AGREEMENT_HIS_ID`),
  KEY `IDX_AGR_AGREEMENT_H_01` (`AGREEMENT_ID`),
  KEY `IDX_AGR_AGREEMENT_H_02` (`AGREEMENT_CODE`),
  KEY `IDX_AGR_AGREEMENT_H_03` (`AGR_LEVEL_ID`,`AGREEMENT_STATUS`),
  KEY `IDX_AGR_AGREEMENT_H_04` (`OWNER_ID`),
  KEY `IDX_AGR_AGREEMENT_H_05` (`AGR_BAR_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `agr_attach` */

DROP TABLE IF EXISTS `agr_attach`;

CREATE TABLE `agr_attach` (
  `ATTACH_ID` bigint(12) NOT NULL,
  `BUSI_TYPE_CODE` varchar(30) DEFAULT NULL,
  `BUSI_SHEET_ID` varchar(128) DEFAULT NULL,
  `ATTACH_TYPE` varchar(3) DEFAULT NULL,
  `FILE_NAME` varchar(128) DEFAULT NULL,
  `STORAGE_FILE_URI` varchar(1024) DEFAULT NULL,
  `STORE_MEDIUM_TYPE` varchar(3) DEFAULT NULL,
  `ATTACH_STATUS` varchar(3) DEFAULT NULL,
  `REMARKS` varchar(1024) DEFAULT NULL,
  `AGR_CREATION_TIME` datetime DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `CREATE_OP_ID` bigint(12) DEFAULT NULL,
  `CREATE_ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  PRIMARY KEY (`ATTACH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `agr_attach_h` */

DROP TABLE IF EXISTS `agr_attach_h`;

CREATE TABLE `agr_attach_h` (
  `ATTACH_ID` bigint(12) NOT NULL,
  `BUSI_TYPE_CODE` varchar(30) DEFAULT NULL,
  `BUSI_SHEET_ID` varchar(128) DEFAULT NULL,
  `ATTACH_TYPE` varchar(3) DEFAULT NULL,
  `FILE_NAME` varchar(128) DEFAULT NULL,
  `STORAGE_FILE_URI` varchar(1024) DEFAULT NULL,
  `STORE_MEDIUM_TYPE` varchar(3) DEFAULT NULL,
  `ATTACH_STATUS` varchar(3) DEFAULT NULL,
  `REMARKS` varchar(1024) DEFAULT NULL,
  `AGR_CREATION_TIME` datetime DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `CREATE_OP_ID` bigint(12) DEFAULT NULL,
  `CREATE_ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL,
  `AGR_VERSION_ID` bigint(12) DEFAULT NULL,
  PRIMARY KEY (`ATTACH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `agr_template` */

DROP TABLE IF EXISTS `agr_template`;

CREATE TABLE `agr_template` (
  `AGREEMENT_TEMPLATE_ID` bigint(12) NOT NULL,
  `AGR_TYPE_ID` bigint(12) DEFAULT NULL,
  `TEMPLATE_CODE` varchar(128) DEFAULT NULL,
  `TEMPLATE_STATUS` varchar(3) DEFAULT NULL COMMENT '10A 草稿 Draft \n10C 修订稿\n10E 提交审批 Submitted \n10G 审批通过 Approved \n10X 失效 InActive\n\nCODE_TYPE=AGR_TEMPLATE_STATUS',
  `STATUS_TIME` datetime DEFAULT NULL,
  `UP_TEMPLATE_ID` bigint(12) DEFAULT NULL,
  `AGREEMENT_TEMPLATE_NAME` varchar(128) DEFAULT NULL,
  `AGR_LEVEL_ID` bigint(12) DEFAULT NULL,
  `AGR_DOC_URL` varchar(1024) DEFAULT NULL,
  `OPERATOR_ID` bigint(12) DEFAULT NULL,
  `ORGANIZATION_ID` bigint(12) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `CREATE_OP_ID` bigint(12) DEFAULT NULL,
  `CREATE_ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL COMMENT '0 失效 1 有效',
  `IS_ADDENDUM` bigint(1) DEFAULT NULL,
  `OFFER_ID` bigint(12) DEFAULT NULL,
  `LANGUAGE` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`AGREEMENT_TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='协议模板';

/*Table structure for table `agr_template_h` */

DROP TABLE IF EXISTS `agr_template_h`;

CREATE TABLE `agr_template_h` (
  `AGREEMENT_TEMPLATE_H_ID` bigint(12) NOT NULL,
  `AGR_VERSION_ID` bigint(12) DEFAULT NULL,
  `AGREEMENT_TEMPLATE_ID` bigint(12) DEFAULT NULL,
  `AGR_TYPE_ID` bigint(12) DEFAULT NULL,
  `TEMPLATE_CODE` varchar(128) DEFAULT NULL,
  `TEMPLATE_STATUS` varchar(3) DEFAULT NULL COMMENT '10A 草稿 Draft \n10C 修订稿\n10E 提交审批 Submitted \n10G 审批通过 Approved \n10X 失效 InActive\n\nCODE_TYPE=AGR_TEMPLATE_STATUS',
  `STATUS_TIME` datetime DEFAULT NULL,
  `UP_TEMPLATE_ID` bigint(12) DEFAULT NULL,
  `AGREEMENT_TEMPLATE_NAME` varchar(128) DEFAULT NULL,
  `AGR_LEVEL_ID` bigint(12) DEFAULT NULL,
  `AGR_DOC_URL` varchar(1024) DEFAULT NULL,
  `OPERATOR_ID` bigint(12) DEFAULT NULL,
  `ORGANIZATION_ID` bigint(12) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `CREATE_OP_ID` bigint(12) DEFAULT NULL,
  `CREATE_ORG_ID` bigint(12) DEFAULT NULL,
  `OP_ID` bigint(12) DEFAULT NULL,
  `ORG_ID` bigint(12) DEFAULT NULL,
  `DONE_DATE` datetime DEFAULT NULL,
  `DONE_CODE` varchar(30) DEFAULT NULL,
  `STATE` bigint(1) DEFAULT NULL COMMENT '0 失效 1 有效',
  `IS_ADDENDUM` bigint(1) DEFAULT NULL,
  `LANGUAGE` varchar(3) DEFAULT NULL,
  `OFFER_ID` bigint(12) DEFAULT NULL,
  PRIMARY KEY (`AGREEMENT_TEMPLATE_H_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='协议模板历史记录';

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
