package com.aii.crm.shop.web.persistence.mapper;

import com.aii.crm.shop.web.persistence.bo.SubscriberOrder;
import com.aii.crm.shop.web.persistence.bo.SubscriberOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubscriberOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    long countByExample(SubscriberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    int deleteByExample(SubscriberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    int deleteByPrimaryKey(Long subscriberOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    int insert(SubscriberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    int insertSelective(SubscriberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    List<SubscriberOrder> selectByExampleWithBLOBs(SubscriberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    List<SubscriberOrder> selectByExample(SubscriberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    SubscriberOrder selectByPrimaryKey(Long subscriberOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") SubscriberOrder record, @Param("example") SubscriberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SubscriberOrder record, @Param("example") SubscriberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    int updateByExample(@Param("record") SubscriberOrder record, @Param("example") SubscriberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    int updateByPrimaryKeySelective(SubscriberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(SubscriberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_order
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    int updateByPrimaryKey(SubscriberOrder record);
}