package com.aii.crm.shop.web.persistence.bo;

import java.util.Date;

public class PreQualification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.PREQ_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Long preqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.CUST_ORDER_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String custOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.REQ_ORDER_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String reqOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.REGION_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.HAS_TNDSL
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String hasTndsl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.HAS_GOING_ORDER
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String hasGoingOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.BILL_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.PASSWORD
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.MUNICIPAL_CODE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String municipalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.ROUTE_NUMBER
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Short routeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.OPTION_SPEC
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String optionSpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.LINE_OPTIONS
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String lineOptions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.SLE_OPTION
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String sleOption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.VISIT_OPTION
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String visitOption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.VISIT_TIME
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String visitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.STATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.CREATE_OP_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Long createOpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.CREATE_ORG_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Long createOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.OP_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Long opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.ORG_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.DONE_CODE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Long doneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.CREATE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.DONE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.EFFECTIVE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.EXPIRE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.TENANT_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.REMARKS
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.HAS_CHECK_PSTN
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String hasCheckPstn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.CONTACT_NUMBER
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String contactNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.LOCKED_SPEED
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String lockedSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.KVHX
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String kvhx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.OFF_STATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String offState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_qualification.TECHNOLOGY
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    private String technology;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.PREQ_ID
     *
     * @return the value of pre_qualification.PREQ_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Long getPreqId() {
        return preqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.PREQ_ID
     *
     * @param preqId the value for pre_qualification.PREQ_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setPreqId(Long preqId) {
        this.preqId = preqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.CUST_ORDER_ID
     *
     * @return the value of pre_qualification.CUST_ORDER_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getCustOrderId() {
        return custOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.CUST_ORDER_ID
     *
     * @param custOrderId the value for pre_qualification.CUST_ORDER_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setCustOrderId(String custOrderId) {
        this.custOrderId = custOrderId == null ? null : custOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.REQ_ORDER_ID
     *
     * @return the value of pre_qualification.REQ_ORDER_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getReqOrderId() {
        return reqOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.REQ_ORDER_ID
     *
     * @param reqOrderId the value for pre_qualification.REQ_ORDER_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setReqOrderId(String reqOrderId) {
        this.reqOrderId = reqOrderId == null ? null : reqOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.REGION_ID
     *
     * @return the value of pre_qualification.REGION_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.REGION_ID
     *
     * @param regionId the value for pre_qualification.REGION_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.HAS_TNDSL
     *
     * @return the value of pre_qualification.HAS_TNDSL
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getHasTndsl() {
        return hasTndsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.HAS_TNDSL
     *
     * @param hasTndsl the value for pre_qualification.HAS_TNDSL
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setHasTndsl(String hasTndsl) {
        this.hasTndsl = hasTndsl == null ? null : hasTndsl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.HAS_GOING_ORDER
     *
     * @return the value of pre_qualification.HAS_GOING_ORDER
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getHasGoingOrder() {
        return hasGoingOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.HAS_GOING_ORDER
     *
     * @param hasGoingOrder the value for pre_qualification.HAS_GOING_ORDER
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setHasGoingOrder(String hasGoingOrder) {
        this.hasGoingOrder = hasGoingOrder == null ? null : hasGoingOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.BILL_ID
     *
     * @return the value of pre_qualification.BILL_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.BILL_ID
     *
     * @param billId the value for pre_qualification.BILL_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setBillId(String billId) {
        this.billId = billId == null ? null : billId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.PASSWORD
     *
     * @return the value of pre_qualification.PASSWORD
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.PASSWORD
     *
     * @param password the value for pre_qualification.PASSWORD
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.MUNICIPAL_CODE
     *
     * @return the value of pre_qualification.MUNICIPAL_CODE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getMunicipalCode() {
        return municipalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.MUNICIPAL_CODE
     *
     * @param municipalCode the value for pre_qualification.MUNICIPAL_CODE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setMunicipalCode(String municipalCode) {
        this.municipalCode = municipalCode == null ? null : municipalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.ROUTE_NUMBER
     *
     * @return the value of pre_qualification.ROUTE_NUMBER
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Short getRouteNumber() {
        return routeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.ROUTE_NUMBER
     *
     * @param routeNumber the value for pre_qualification.ROUTE_NUMBER
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setRouteNumber(Short routeNumber) {
        this.routeNumber = routeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.OPTION_SPEC
     *
     * @return the value of pre_qualification.OPTION_SPEC
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getOptionSpec() {
        return optionSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.OPTION_SPEC
     *
     * @param optionSpec the value for pre_qualification.OPTION_SPEC
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setOptionSpec(String optionSpec) {
        this.optionSpec = optionSpec == null ? null : optionSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.LINE_OPTIONS
     *
     * @return the value of pre_qualification.LINE_OPTIONS
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getLineOptions() {
        return lineOptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.LINE_OPTIONS
     *
     * @param lineOptions the value for pre_qualification.LINE_OPTIONS
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setLineOptions(String lineOptions) {
        this.lineOptions = lineOptions == null ? null : lineOptions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.SLE_OPTION
     *
     * @return the value of pre_qualification.SLE_OPTION
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getSleOption() {
        return sleOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.SLE_OPTION
     *
     * @param sleOption the value for pre_qualification.SLE_OPTION
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setSleOption(String sleOption) {
        this.sleOption = sleOption == null ? null : sleOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.VISIT_OPTION
     *
     * @return the value of pre_qualification.VISIT_OPTION
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getVisitOption() {
        return visitOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.VISIT_OPTION
     *
     * @param visitOption the value for pre_qualification.VISIT_OPTION
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setVisitOption(String visitOption) {
        this.visitOption = visitOption == null ? null : visitOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.VISIT_TIME
     *
     * @return the value of pre_qualification.VISIT_TIME
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.VISIT_TIME
     *
     * @param visitTime the value for pre_qualification.VISIT_TIME
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setVisitTime(String visitTime) {
        this.visitTime = visitTime == null ? null : visitTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.STATE
     *
     * @return the value of pre_qualification.STATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.STATE
     *
     * @param state the value for pre_qualification.STATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.CREATE_OP_ID
     *
     * @return the value of pre_qualification.CREATE_OP_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Long getCreateOpId() {
        return createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.CREATE_OP_ID
     *
     * @param createOpId the value for pre_qualification.CREATE_OP_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setCreateOpId(Long createOpId) {
        this.createOpId = createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.CREATE_ORG_ID
     *
     * @return the value of pre_qualification.CREATE_ORG_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Long getCreateOrgId() {
        return createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.CREATE_ORG_ID
     *
     * @param createOrgId the value for pre_qualification.CREATE_ORG_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setCreateOrgId(Long createOrgId) {
        this.createOrgId = createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.OP_ID
     *
     * @return the value of pre_qualification.OP_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.OP_ID
     *
     * @param opId the value for pre_qualification.OP_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.ORG_ID
     *
     * @return the value of pre_qualification.ORG_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.ORG_ID
     *
     * @param orgId the value for pre_qualification.ORG_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.DONE_CODE
     *
     * @return the value of pre_qualification.DONE_CODE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Long getDoneCode() {
        return doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.DONE_CODE
     *
     * @param doneCode the value for pre_qualification.DONE_CODE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setDoneCode(Long doneCode) {
        this.doneCode = doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.CREATE_DATE
     *
     * @return the value of pre_qualification.CREATE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.CREATE_DATE
     *
     * @param createDate the value for pre_qualification.CREATE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.DONE_DATE
     *
     * @return the value of pre_qualification.DONE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.DONE_DATE
     *
     * @param doneDate the value for pre_qualification.DONE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.EFFECTIVE_DATE
     *
     * @return the value of pre_qualification.EFFECTIVE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for pre_qualification.EFFECTIVE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.EXPIRE_DATE
     *
     * @return the value of pre_qualification.EXPIRE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.EXPIRE_DATE
     *
     * @param expireDate the value for pre_qualification.EXPIRE_DATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.TENANT_ID
     *
     * @return the value of pre_qualification.TENANT_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.TENANT_ID
     *
     * @param tenantId the value for pre_qualification.TENANT_ID
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.REMARKS
     *
     * @return the value of pre_qualification.REMARKS
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.REMARKS
     *
     * @param remarks the value for pre_qualification.REMARKS
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.HAS_CHECK_PSTN
     *
     * @return the value of pre_qualification.HAS_CHECK_PSTN
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getHasCheckPstn() {
        return hasCheckPstn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.HAS_CHECK_PSTN
     *
     * @param hasCheckPstn the value for pre_qualification.HAS_CHECK_PSTN
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setHasCheckPstn(String hasCheckPstn) {
        this.hasCheckPstn = hasCheckPstn == null ? null : hasCheckPstn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.CONTACT_NUMBER
     *
     * @return the value of pre_qualification.CONTACT_NUMBER
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.CONTACT_NUMBER
     *
     * @param contactNumber the value for pre_qualification.CONTACT_NUMBER
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber == null ? null : contactNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.LOCKED_SPEED
     *
     * @return the value of pre_qualification.LOCKED_SPEED
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getLockedSpeed() {
        return lockedSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.LOCKED_SPEED
     *
     * @param lockedSpeed the value for pre_qualification.LOCKED_SPEED
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setLockedSpeed(String lockedSpeed) {
        this.lockedSpeed = lockedSpeed == null ? null : lockedSpeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.KVHX
     *
     * @return the value of pre_qualification.KVHX
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getKvhx() {
        return kvhx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.KVHX
     *
     * @param kvhx the value for pre_qualification.KVHX
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setKvhx(String kvhx) {
        this.kvhx = kvhx == null ? null : kvhx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.OFF_STATE
     *
     * @return the value of pre_qualification.OFF_STATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getOffState() {
        return offState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.OFF_STATE
     *
     * @param offState the value for pre_qualification.OFF_STATE
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setOffState(String offState) {
        this.offState = offState == null ? null : offState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_qualification.TECHNOLOGY
     *
     * @return the value of pre_qualification.TECHNOLOGY
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public String getTechnology() {
        return technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_qualification.TECHNOLOGY
     *
     * @param technology the value for pre_qualification.TECHNOLOGY
     *
     * @mbg.generated Wed May 29 09:25:11 CST 2019
     */
    public void setTechnology(String technology) {
        this.technology = technology == null ? null : technology.trim();
    }
}