package com.aii.crm.shop.web.persistence.bo;

import java.util.Date;

public class ShoppingCartPayMethod {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.PAY_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Long payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.CART_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Long cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.ACCOUNT_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private String accountCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.INSTALLMENT_FLAG
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private String installmentFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.STATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.CREATE_OP_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Long createOpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.CREATE_ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Long createOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.OP_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Long opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.DONE_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Long doneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.CREATE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.DONE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.EFFECTIVE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.EXPIRE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.TENANT_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.REMARKS
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.FEE_TYPE_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private String feeTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.PAYMENT_METHOD_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private String paymentMethodCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.BANK_DEBIT_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private Long bankDebitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_pay_method.TRANSACTION_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    private String transactionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.PAY_ID
     *
     * @return the value of shopping_cart_pay_method.PAY_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.PAY_ID
     *
     * @param payId the value for shopping_cart_pay_method.PAY_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.CART_ID
     *
     * @return the value of shopping_cart_pay_method.CART_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Long getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.CART_ID
     *
     * @param cartId the value for shopping_cart_pay_method.CART_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setCartId(Long cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.ACCOUNT_CODE
     *
     * @return the value of shopping_cart_pay_method.ACCOUNT_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.ACCOUNT_CODE
     *
     * @param accountCode the value for shopping_cart_pay_method.ACCOUNT_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.INSTALLMENT_FLAG
     *
     * @return the value of shopping_cart_pay_method.INSTALLMENT_FLAG
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public String getInstallmentFlag() {
        return installmentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.INSTALLMENT_FLAG
     *
     * @param installmentFlag the value for shopping_cart_pay_method.INSTALLMENT_FLAG
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setInstallmentFlag(String installmentFlag) {
        this.installmentFlag = installmentFlag == null ? null : installmentFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.STATE
     *
     * @return the value of shopping_cart_pay_method.STATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.STATE
     *
     * @param state the value for shopping_cart_pay_method.STATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.CREATE_OP_ID
     *
     * @return the value of shopping_cart_pay_method.CREATE_OP_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Long getCreateOpId() {
        return createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.CREATE_OP_ID
     *
     * @param createOpId the value for shopping_cart_pay_method.CREATE_OP_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setCreateOpId(Long createOpId) {
        this.createOpId = createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.CREATE_ORG_ID
     *
     * @return the value of shopping_cart_pay_method.CREATE_ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Long getCreateOrgId() {
        return createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.CREATE_ORG_ID
     *
     * @param createOrgId the value for shopping_cart_pay_method.CREATE_ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setCreateOrgId(Long createOrgId) {
        this.createOrgId = createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.OP_ID
     *
     * @return the value of shopping_cart_pay_method.OP_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.OP_ID
     *
     * @param opId the value for shopping_cart_pay_method.OP_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.ORG_ID
     *
     * @return the value of shopping_cart_pay_method.ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.ORG_ID
     *
     * @param orgId the value for shopping_cart_pay_method.ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.DONE_CODE
     *
     * @return the value of shopping_cart_pay_method.DONE_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Long getDoneCode() {
        return doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.DONE_CODE
     *
     * @param doneCode the value for shopping_cart_pay_method.DONE_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setDoneCode(Long doneCode) {
        this.doneCode = doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.CREATE_DATE
     *
     * @return the value of shopping_cart_pay_method.CREATE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.CREATE_DATE
     *
     * @param createDate the value for shopping_cart_pay_method.CREATE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.DONE_DATE
     *
     * @return the value of shopping_cart_pay_method.DONE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.DONE_DATE
     *
     * @param doneDate the value for shopping_cart_pay_method.DONE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.EFFECTIVE_DATE
     *
     * @return the value of shopping_cart_pay_method.EFFECTIVE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for shopping_cart_pay_method.EFFECTIVE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.EXPIRE_DATE
     *
     * @return the value of shopping_cart_pay_method.EXPIRE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.EXPIRE_DATE
     *
     * @param expireDate the value for shopping_cart_pay_method.EXPIRE_DATE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.TENANT_ID
     *
     * @return the value of shopping_cart_pay_method.TENANT_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.TENANT_ID
     *
     * @param tenantId the value for shopping_cart_pay_method.TENANT_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.REMARKS
     *
     * @return the value of shopping_cart_pay_method.REMARKS
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.REMARKS
     *
     * @param remarks the value for shopping_cart_pay_method.REMARKS
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.FEE_TYPE_CODE
     *
     * @return the value of shopping_cart_pay_method.FEE_TYPE_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public String getFeeTypeCode() {
        return feeTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.FEE_TYPE_CODE
     *
     * @param feeTypeCode the value for shopping_cart_pay_method.FEE_TYPE_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setFeeTypeCode(String feeTypeCode) {
        this.feeTypeCode = feeTypeCode == null ? null : feeTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.PAYMENT_METHOD_CODE
     *
     * @return the value of shopping_cart_pay_method.PAYMENT_METHOD_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public String getPaymentMethodCode() {
        return paymentMethodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.PAYMENT_METHOD_CODE
     *
     * @param paymentMethodCode the value for shopping_cart_pay_method.PAYMENT_METHOD_CODE
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setPaymentMethodCode(String paymentMethodCode) {
        this.paymentMethodCode = paymentMethodCode == null ? null : paymentMethodCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.BANK_DEBIT_ID
     *
     * @return the value of shopping_cart_pay_method.BANK_DEBIT_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public Long getBankDebitId() {
        return bankDebitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.BANK_DEBIT_ID
     *
     * @param bankDebitId the value for shopping_cart_pay_method.BANK_DEBIT_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setBankDebitId(Long bankDebitId) {
        this.bankDebitId = bankDebitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_pay_method.TRANSACTION_ID
     *
     * @return the value of shopping_cart_pay_method.TRANSACTION_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_pay_method.TRANSACTION_ID
     *
     * @param transactionId the value for shopping_cart_pay_method.TRANSACTION_ID
     *
     * @mbg.generated Wed May 29 09:27:10 CST 2019
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }
}