package com.aii.crm.shop.web.persistence.bo;

import java.util.Date;

public class SubscriberOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.SUBSCRIBER_ORDER_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Long subscriberOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.SUBSCRIBER_ORDER_NAME
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String subscriberOrderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.ORDER_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.TEMPLETE_SPEC_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Long templeteSpecId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.ORDER_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.ITEM_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String itemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.ACCOUNT_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String accountCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.MSG_TYPE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.STATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.CREATE_OP_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Long createOpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.CREATE_ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Long createOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.OP_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Long opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.DONE_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Long doneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.CREATE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.DONE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.EFFECTIVE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.EXPIRE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.TENANT_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.REMARKS
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.SUBSCRIBER_TRADE_TYPE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String subscriberTradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.SERVICE_NUMBER
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String serviceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.SUBSCRIBER_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String subscriberCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_order.ORDER_MSG
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    private String orderMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.SUBSCRIBER_ORDER_ID
     *
     * @return the value of subscriber_order.SUBSCRIBER_ORDER_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Long getSubscriberOrderId() {
        return subscriberOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.SUBSCRIBER_ORDER_ID
     *
     * @param subscriberOrderId the value for subscriber_order.SUBSCRIBER_ORDER_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setSubscriberOrderId(Long subscriberOrderId) {
        this.subscriberOrderId = subscriberOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.SUBSCRIBER_ORDER_NAME
     *
     * @return the value of subscriber_order.SUBSCRIBER_ORDER_NAME
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getSubscriberOrderName() {
        return subscriberOrderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.SUBSCRIBER_ORDER_NAME
     *
     * @param subscriberOrderName the value for subscriber_order.SUBSCRIBER_ORDER_NAME
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setSubscriberOrderName(String subscriberOrderName) {
        this.subscriberOrderName = subscriberOrderName == null ? null : subscriberOrderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.ORDER_ID
     *
     * @return the value of subscriber_order.ORDER_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.ORDER_ID
     *
     * @param orderId the value for subscriber_order.ORDER_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.TEMPLETE_SPEC_ID
     *
     * @return the value of subscriber_order.TEMPLETE_SPEC_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Long getTempleteSpecId() {
        return templeteSpecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.TEMPLETE_SPEC_ID
     *
     * @param templeteSpecId the value for subscriber_order.TEMPLETE_SPEC_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setTempleteSpecId(Long templeteSpecId) {
        this.templeteSpecId = templeteSpecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.ORDER_CODE
     *
     * @return the value of subscriber_order.ORDER_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.ORDER_CODE
     *
     * @param orderCode the value for subscriber_order.ORDER_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.ITEM_CODE
     *
     * @return the value of subscriber_order.ITEM_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.ITEM_CODE
     *
     * @param itemCode the value for subscriber_order.ITEM_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.ACCOUNT_CODE
     *
     * @return the value of subscriber_order.ACCOUNT_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.ACCOUNT_CODE
     *
     * @param accountCode the value for subscriber_order.ACCOUNT_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.MSG_TYPE
     *
     * @return the value of subscriber_order.MSG_TYPE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.MSG_TYPE
     *
     * @param msgType the value for subscriber_order.MSG_TYPE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType == null ? null : msgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.STATE
     *
     * @return the value of subscriber_order.STATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.STATE
     *
     * @param state the value for subscriber_order.STATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.CREATE_OP_ID
     *
     * @return the value of subscriber_order.CREATE_OP_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Long getCreateOpId() {
        return createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.CREATE_OP_ID
     *
     * @param createOpId the value for subscriber_order.CREATE_OP_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setCreateOpId(Long createOpId) {
        this.createOpId = createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.CREATE_ORG_ID
     *
     * @return the value of subscriber_order.CREATE_ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Long getCreateOrgId() {
        return createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.CREATE_ORG_ID
     *
     * @param createOrgId the value for subscriber_order.CREATE_ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setCreateOrgId(Long createOrgId) {
        this.createOrgId = createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.OP_ID
     *
     * @return the value of subscriber_order.OP_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.OP_ID
     *
     * @param opId the value for subscriber_order.OP_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.ORG_ID
     *
     * @return the value of subscriber_order.ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.ORG_ID
     *
     * @param orgId the value for subscriber_order.ORG_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.DONE_CODE
     *
     * @return the value of subscriber_order.DONE_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Long getDoneCode() {
        return doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.DONE_CODE
     *
     * @param doneCode the value for subscriber_order.DONE_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setDoneCode(Long doneCode) {
        this.doneCode = doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.CREATE_DATE
     *
     * @return the value of subscriber_order.CREATE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.CREATE_DATE
     *
     * @param createDate the value for subscriber_order.CREATE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.DONE_DATE
     *
     * @return the value of subscriber_order.DONE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.DONE_DATE
     *
     * @param doneDate the value for subscriber_order.DONE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.EFFECTIVE_DATE
     *
     * @return the value of subscriber_order.EFFECTIVE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for subscriber_order.EFFECTIVE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.EXPIRE_DATE
     *
     * @return the value of subscriber_order.EXPIRE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.EXPIRE_DATE
     *
     * @param expireDate the value for subscriber_order.EXPIRE_DATE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.TENANT_ID
     *
     * @return the value of subscriber_order.TENANT_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.TENANT_ID
     *
     * @param tenantId the value for subscriber_order.TENANT_ID
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.REMARKS
     *
     * @return the value of subscriber_order.REMARKS
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.REMARKS
     *
     * @param remarks the value for subscriber_order.REMARKS
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.SUBSCRIBER_TRADE_TYPE
     *
     * @return the value of subscriber_order.SUBSCRIBER_TRADE_TYPE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getSubscriberTradeType() {
        return subscriberTradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.SUBSCRIBER_TRADE_TYPE
     *
     * @param subscriberTradeType the value for subscriber_order.SUBSCRIBER_TRADE_TYPE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setSubscriberTradeType(String subscriberTradeType) {
        this.subscriberTradeType = subscriberTradeType == null ? null : subscriberTradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.SERVICE_NUMBER
     *
     * @return the value of subscriber_order.SERVICE_NUMBER
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getServiceNumber() {
        return serviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.SERVICE_NUMBER
     *
     * @param serviceNumber the value for subscriber_order.SERVICE_NUMBER
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setServiceNumber(String serviceNumber) {
        this.serviceNumber = serviceNumber == null ? null : serviceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.SUBSCRIBER_CODE
     *
     * @return the value of subscriber_order.SUBSCRIBER_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getSubscriberCode() {
        return subscriberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.SUBSCRIBER_CODE
     *
     * @param subscriberCode the value for subscriber_order.SUBSCRIBER_CODE
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setSubscriberCode(String subscriberCode) {
        this.subscriberCode = subscriberCode == null ? null : subscriberCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_order.ORDER_MSG
     *
     * @return the value of subscriber_order.ORDER_MSG
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public String getOrderMsg() {
        return orderMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_order.ORDER_MSG
     *
     * @param orderMsg the value for subscriber_order.ORDER_MSG
     *
     * @mbg.generated Wed May 29 09:27:38 CST 2019
     */
    public void setOrderMsg(String orderMsg) {
        this.orderMsg = orderMsg == null ? null : orderMsg.trim();
    }
}