package com.aii.crm.loyalty.web.persistence.mapper;

import com.aii.crm.loyalty.web.persistence.bo.IntegralBook;
import com.aii.crm.loyalty.web.persistence.bo.IntegralBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IntegralBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    long countByExample(IntegralBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    int deleteByExample(IntegralBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    int deleteByPrimaryKey(Long integralBookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    int insert(IntegralBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    int insertSelective(IntegralBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    List<IntegralBook> selectByExample(IntegralBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    IntegralBook selectByPrimaryKey(Long integralBookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") IntegralBook record, @Param("example") IntegralBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    int updateByExample(@Param("record") IntegralBook record, @Param("example") IntegralBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    int updateByPrimaryKeySelective(IntegralBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_book
     *
     * @mbg.generated Wed May 29 09:45:31 CST 2019
     */
    int updateByPrimaryKey(IntegralBook record);
}