package com.aii.crm.cm.web.persistence.bo;

import java.util.Date;

public class CmAcctBillCycle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.CYCLE_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long cycleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.ACCT_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long acctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.CYCLE_TYPE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long cycleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.CYCLE_UNIT
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long cycleUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.BILL_DAY
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long billDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.BILL_DUE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long billDueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.CYCLE_REASON
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private String cycleReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.STATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.CREATE_OP_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long createOpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.CREATE_ORG_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long createOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.OP_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.ORG_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.DONE_CODE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Long doneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.CREATE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.DONE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.EFFECTIVE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.EXPIRE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.REGION_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private String regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct_bill_cycle.REMARKS
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.CYCLE_ID
     *
     * @return the value of cm_acct_bill_cycle.CYCLE_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getCycleId() {
        return cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.CYCLE_ID
     *
     * @param cycleId the value for cm_acct_bill_cycle.CYCLE_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setCycleId(Long cycleId) {
        this.cycleId = cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.ACCT_ID
     *
     * @return the value of cm_acct_bill_cycle.ACCT_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getAcctId() {
        return acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.ACCT_ID
     *
     * @param acctId the value for cm_acct_bill_cycle.ACCT_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setAcctId(Long acctId) {
        this.acctId = acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.CYCLE_TYPE
     *
     * @return the value of cm_acct_bill_cycle.CYCLE_TYPE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getCycleType() {
        return cycleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.CYCLE_TYPE
     *
     * @param cycleType the value for cm_acct_bill_cycle.CYCLE_TYPE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setCycleType(Long cycleType) {
        this.cycleType = cycleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.CYCLE_UNIT
     *
     * @return the value of cm_acct_bill_cycle.CYCLE_UNIT
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getCycleUnit() {
        return cycleUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.CYCLE_UNIT
     *
     * @param cycleUnit the value for cm_acct_bill_cycle.CYCLE_UNIT
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setCycleUnit(Long cycleUnit) {
        this.cycleUnit = cycleUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.BILL_DAY
     *
     * @return the value of cm_acct_bill_cycle.BILL_DAY
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getBillDay() {
        return billDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.BILL_DAY
     *
     * @param billDay the value for cm_acct_bill_cycle.BILL_DAY
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setBillDay(Long billDay) {
        this.billDay = billDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.BILL_DUE_DATE
     *
     * @return the value of cm_acct_bill_cycle.BILL_DUE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getBillDueDate() {
        return billDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.BILL_DUE_DATE
     *
     * @param billDueDate the value for cm_acct_bill_cycle.BILL_DUE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setBillDueDate(Long billDueDate) {
        this.billDueDate = billDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.CYCLE_REASON
     *
     * @return the value of cm_acct_bill_cycle.CYCLE_REASON
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public String getCycleReason() {
        return cycleReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.CYCLE_REASON
     *
     * @param cycleReason the value for cm_acct_bill_cycle.CYCLE_REASON
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setCycleReason(String cycleReason) {
        this.cycleReason = cycleReason == null ? null : cycleReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.STATE
     *
     * @return the value of cm_acct_bill_cycle.STATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.STATE
     *
     * @param state the value for cm_acct_bill_cycle.STATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.CREATE_OP_ID
     *
     * @return the value of cm_acct_bill_cycle.CREATE_OP_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getCreateOpId() {
        return createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.CREATE_OP_ID
     *
     * @param createOpId the value for cm_acct_bill_cycle.CREATE_OP_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setCreateOpId(Long createOpId) {
        this.createOpId = createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.CREATE_ORG_ID
     *
     * @return the value of cm_acct_bill_cycle.CREATE_ORG_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getCreateOrgId() {
        return createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.CREATE_ORG_ID
     *
     * @param createOrgId the value for cm_acct_bill_cycle.CREATE_ORG_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setCreateOrgId(Long createOrgId) {
        this.createOrgId = createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.OP_ID
     *
     * @return the value of cm_acct_bill_cycle.OP_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.OP_ID
     *
     * @param opId the value for cm_acct_bill_cycle.OP_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.ORG_ID
     *
     * @return the value of cm_acct_bill_cycle.ORG_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.ORG_ID
     *
     * @param orgId the value for cm_acct_bill_cycle.ORG_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.DONE_CODE
     *
     * @return the value of cm_acct_bill_cycle.DONE_CODE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Long getDoneCode() {
        return doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.DONE_CODE
     *
     * @param doneCode the value for cm_acct_bill_cycle.DONE_CODE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setDoneCode(Long doneCode) {
        this.doneCode = doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.CREATE_DATE
     *
     * @return the value of cm_acct_bill_cycle.CREATE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.CREATE_DATE
     *
     * @param createDate the value for cm_acct_bill_cycle.CREATE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.DONE_DATE
     *
     * @return the value of cm_acct_bill_cycle.DONE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.DONE_DATE
     *
     * @param doneDate the value for cm_acct_bill_cycle.DONE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.EFFECTIVE_DATE
     *
     * @return the value of cm_acct_bill_cycle.EFFECTIVE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for cm_acct_bill_cycle.EFFECTIVE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.EXPIRE_DATE
     *
     * @return the value of cm_acct_bill_cycle.EXPIRE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.EXPIRE_DATE
     *
     * @param expireDate the value for cm_acct_bill_cycle.EXPIRE_DATE
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.REGION_ID
     *
     * @return the value of cm_acct_bill_cycle.REGION_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.REGION_ID
     *
     * @param regionId the value for cm_acct_bill_cycle.REGION_ID
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct_bill_cycle.REMARKS
     *
     * @return the value of cm_acct_bill_cycle.REMARKS
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct_bill_cycle.REMARKS
     *
     * @param remarks the value for cm_acct_bill_cycle.REMARKS
     *
     * @mbg.generated Tue May 28 20:03:42 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}