package com.aii.crm.cm.web.persistence.bo;

public class CmCustBadRecordHKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record_h.BESKED_ID
     *
     * @mbg.generated Tue May 28 20:11:00 CST 2019
     */
    private String beskedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record_h.CUST_ID
     *
     * @mbg.generated Tue May 28 20:11:00 CST 2019
     */
    private Long custId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record_h.BESKED_ID
     *
     * @return the value of cm_cust_bad_record_h.BESKED_ID
     *
     * @mbg.generated Tue May 28 20:11:00 CST 2019
     */
    public String getBeskedId() {
        return beskedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record_h.BESKED_ID
     *
     * @param beskedId the value for cm_cust_bad_record_h.BESKED_ID
     *
     * @mbg.generated Tue May 28 20:11:00 CST 2019
     */
    public void setBeskedId(String beskedId) {
        this.beskedId = beskedId == null ? null : beskedId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record_h.CUST_ID
     *
     * @return the value of cm_cust_bad_record_h.CUST_ID
     *
     * @mbg.generated Tue May 28 20:11:00 CST 2019
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record_h.CUST_ID
     *
     * @param custId the value for cm_cust_bad_record_h.CUST_ID
     *
     * @mbg.generated Tue May 28 20:11:00 CST 2019
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }
}