package com.aii.crm.cm.web.persistence.bo;

import java.util.Date;

public class CmCustBadRecord extends CmCustBadRecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.DELETION_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Date deletionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.DELETION_CAUS
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String deletionCaus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.CREATE_BY
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.REGIST_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.REGIST_REMARK
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String registRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.AMOUNT
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT1
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT2
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT3
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT4
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT5
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT6
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT7
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT8
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT9
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT10
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT11
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT12
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT13
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT14
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT15
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT16
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT17
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT18
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String ext18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT19
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long ext19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT20
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long ext20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT21
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long ext21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT22
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long ext22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT23
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long ext23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT24
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long ext24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT25
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long ext25;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT26
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long ext26;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT27
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Date ext27;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT28
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Date ext28;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT29
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Date ext29;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXT30
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Date ext30;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.STATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.CREATE_OP_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long createOpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.CREATE_ORG_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long createOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.OP_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.ORG_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.DONE_CODE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Long doneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.CREATE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.DONE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EFFECTIVE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.EXPIRE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.REGION_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_cust_bad_record.REMARKS
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.DELETION_DATE
     *
     * @return the value of cm_cust_bad_record.DELETION_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Date getDeletionDate() {
        return deletionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.DELETION_DATE
     *
     * @param deletionDate the value for cm_cust_bad_record.DELETION_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setDeletionDate(Date deletionDate) {
        this.deletionDate = deletionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.DELETION_CAUS
     *
     * @return the value of cm_cust_bad_record.DELETION_CAUS
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getDeletionCaus() {
        return deletionCaus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.DELETION_CAUS
     *
     * @param deletionCaus the value for cm_cust_bad_record.DELETION_CAUS
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setDeletionCaus(String deletionCaus) {
        this.deletionCaus = deletionCaus == null ? null : deletionCaus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.CREATE_BY
     *
     * @return the value of cm_cust_bad_record.CREATE_BY
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.CREATE_BY
     *
     * @param createBy the value for cm_cust_bad_record.CREATE_BY
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.REGIST_DATE
     *
     * @return the value of cm_cust_bad_record.REGIST_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.REGIST_DATE
     *
     * @param registDate the value for cm_cust_bad_record.REGIST_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.REGIST_REMARK
     *
     * @return the value of cm_cust_bad_record.REGIST_REMARK
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getRegistRemark() {
        return registRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.REGIST_REMARK
     *
     * @param registRemark the value for cm_cust_bad_record.REGIST_REMARK
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setRegistRemark(String registRemark) {
        this.registRemark = registRemark == null ? null : registRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.AMOUNT
     *
     * @return the value of cm_cust_bad_record.AMOUNT
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.AMOUNT
     *
     * @param amount the value for cm_cust_bad_record.AMOUNT
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT1
     *
     * @return the value of cm_cust_bad_record.EXT1
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT1
     *
     * @param ext1 the value for cm_cust_bad_record.EXT1
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT2
     *
     * @return the value of cm_cust_bad_record.EXT2
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT2
     *
     * @param ext2 the value for cm_cust_bad_record.EXT2
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT3
     *
     * @return the value of cm_cust_bad_record.EXT3
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT3
     *
     * @param ext3 the value for cm_cust_bad_record.EXT3
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT4
     *
     * @return the value of cm_cust_bad_record.EXT4
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT4
     *
     * @param ext4 the value for cm_cust_bad_record.EXT4
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT5
     *
     * @return the value of cm_cust_bad_record.EXT5
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT5
     *
     * @param ext5 the value for cm_cust_bad_record.EXT5
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT6
     *
     * @return the value of cm_cust_bad_record.EXT6
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt6() {
        return ext6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT6
     *
     * @param ext6 the value for cm_cust_bad_record.EXT6
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt6(String ext6) {
        this.ext6 = ext6 == null ? null : ext6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT7
     *
     * @return the value of cm_cust_bad_record.EXT7
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt7() {
        return ext7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT7
     *
     * @param ext7 the value for cm_cust_bad_record.EXT7
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt7(String ext7) {
        this.ext7 = ext7 == null ? null : ext7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT8
     *
     * @return the value of cm_cust_bad_record.EXT8
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt8() {
        return ext8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT8
     *
     * @param ext8 the value for cm_cust_bad_record.EXT8
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt8(String ext8) {
        this.ext8 = ext8 == null ? null : ext8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT9
     *
     * @return the value of cm_cust_bad_record.EXT9
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt9() {
        return ext9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT9
     *
     * @param ext9 the value for cm_cust_bad_record.EXT9
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt9(String ext9) {
        this.ext9 = ext9 == null ? null : ext9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT10
     *
     * @return the value of cm_cust_bad_record.EXT10
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt10() {
        return ext10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT10
     *
     * @param ext10 the value for cm_cust_bad_record.EXT10
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt10(String ext10) {
        this.ext10 = ext10 == null ? null : ext10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT11
     *
     * @return the value of cm_cust_bad_record.EXT11
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt11() {
        return ext11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT11
     *
     * @param ext11 the value for cm_cust_bad_record.EXT11
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt11(String ext11) {
        this.ext11 = ext11 == null ? null : ext11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT12
     *
     * @return the value of cm_cust_bad_record.EXT12
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt12() {
        return ext12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT12
     *
     * @param ext12 the value for cm_cust_bad_record.EXT12
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt12(String ext12) {
        this.ext12 = ext12 == null ? null : ext12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT13
     *
     * @return the value of cm_cust_bad_record.EXT13
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt13() {
        return ext13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT13
     *
     * @param ext13 the value for cm_cust_bad_record.EXT13
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt13(String ext13) {
        this.ext13 = ext13 == null ? null : ext13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT14
     *
     * @return the value of cm_cust_bad_record.EXT14
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt14() {
        return ext14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT14
     *
     * @param ext14 the value for cm_cust_bad_record.EXT14
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt14(String ext14) {
        this.ext14 = ext14 == null ? null : ext14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT15
     *
     * @return the value of cm_cust_bad_record.EXT15
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt15() {
        return ext15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT15
     *
     * @param ext15 the value for cm_cust_bad_record.EXT15
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt15(String ext15) {
        this.ext15 = ext15 == null ? null : ext15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT16
     *
     * @return the value of cm_cust_bad_record.EXT16
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt16() {
        return ext16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT16
     *
     * @param ext16 the value for cm_cust_bad_record.EXT16
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt16(String ext16) {
        this.ext16 = ext16 == null ? null : ext16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT17
     *
     * @return the value of cm_cust_bad_record.EXT17
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt17() {
        return ext17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT17
     *
     * @param ext17 the value for cm_cust_bad_record.EXT17
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt17(String ext17) {
        this.ext17 = ext17 == null ? null : ext17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT18
     *
     * @return the value of cm_cust_bad_record.EXT18
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getExt18() {
        return ext18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT18
     *
     * @param ext18 the value for cm_cust_bad_record.EXT18
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt18(String ext18) {
        this.ext18 = ext18 == null ? null : ext18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT19
     *
     * @return the value of cm_cust_bad_record.EXT19
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getExt19() {
        return ext19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT19
     *
     * @param ext19 the value for cm_cust_bad_record.EXT19
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt19(Long ext19) {
        this.ext19 = ext19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT20
     *
     * @return the value of cm_cust_bad_record.EXT20
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getExt20() {
        return ext20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT20
     *
     * @param ext20 the value for cm_cust_bad_record.EXT20
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt20(Long ext20) {
        this.ext20 = ext20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT21
     *
     * @return the value of cm_cust_bad_record.EXT21
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getExt21() {
        return ext21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT21
     *
     * @param ext21 the value for cm_cust_bad_record.EXT21
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt21(Long ext21) {
        this.ext21 = ext21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT22
     *
     * @return the value of cm_cust_bad_record.EXT22
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getExt22() {
        return ext22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT22
     *
     * @param ext22 the value for cm_cust_bad_record.EXT22
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt22(Long ext22) {
        this.ext22 = ext22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT23
     *
     * @return the value of cm_cust_bad_record.EXT23
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getExt23() {
        return ext23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT23
     *
     * @param ext23 the value for cm_cust_bad_record.EXT23
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt23(Long ext23) {
        this.ext23 = ext23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT24
     *
     * @return the value of cm_cust_bad_record.EXT24
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getExt24() {
        return ext24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT24
     *
     * @param ext24 the value for cm_cust_bad_record.EXT24
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt24(Long ext24) {
        this.ext24 = ext24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT25
     *
     * @return the value of cm_cust_bad_record.EXT25
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getExt25() {
        return ext25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT25
     *
     * @param ext25 the value for cm_cust_bad_record.EXT25
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt25(Long ext25) {
        this.ext25 = ext25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT26
     *
     * @return the value of cm_cust_bad_record.EXT26
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getExt26() {
        return ext26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT26
     *
     * @param ext26 the value for cm_cust_bad_record.EXT26
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt26(Long ext26) {
        this.ext26 = ext26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT27
     *
     * @return the value of cm_cust_bad_record.EXT27
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Date getExt27() {
        return ext27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT27
     *
     * @param ext27 the value for cm_cust_bad_record.EXT27
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt27(Date ext27) {
        this.ext27 = ext27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT28
     *
     * @return the value of cm_cust_bad_record.EXT28
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Date getExt28() {
        return ext28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT28
     *
     * @param ext28 the value for cm_cust_bad_record.EXT28
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt28(Date ext28) {
        this.ext28 = ext28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT29
     *
     * @return the value of cm_cust_bad_record.EXT29
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Date getExt29() {
        return ext29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT29
     *
     * @param ext29 the value for cm_cust_bad_record.EXT29
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt29(Date ext29) {
        this.ext29 = ext29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXT30
     *
     * @return the value of cm_cust_bad_record.EXT30
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Date getExt30() {
        return ext30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXT30
     *
     * @param ext30 the value for cm_cust_bad_record.EXT30
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExt30(Date ext30) {
        this.ext30 = ext30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.STATE
     *
     * @return the value of cm_cust_bad_record.STATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.STATE
     *
     * @param state the value for cm_cust_bad_record.STATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.CREATE_OP_ID
     *
     * @return the value of cm_cust_bad_record.CREATE_OP_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getCreateOpId() {
        return createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.CREATE_OP_ID
     *
     * @param createOpId the value for cm_cust_bad_record.CREATE_OP_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setCreateOpId(Long createOpId) {
        this.createOpId = createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.CREATE_ORG_ID
     *
     * @return the value of cm_cust_bad_record.CREATE_ORG_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getCreateOrgId() {
        return createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.CREATE_ORG_ID
     *
     * @param createOrgId the value for cm_cust_bad_record.CREATE_ORG_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setCreateOrgId(Long createOrgId) {
        this.createOrgId = createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.OP_ID
     *
     * @return the value of cm_cust_bad_record.OP_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.OP_ID
     *
     * @param opId the value for cm_cust_bad_record.OP_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.ORG_ID
     *
     * @return the value of cm_cust_bad_record.ORG_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.ORG_ID
     *
     * @param orgId the value for cm_cust_bad_record.ORG_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.DONE_CODE
     *
     * @return the value of cm_cust_bad_record.DONE_CODE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Long getDoneCode() {
        return doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.DONE_CODE
     *
     * @param doneCode the value for cm_cust_bad_record.DONE_CODE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setDoneCode(Long doneCode) {
        this.doneCode = doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.CREATE_DATE
     *
     * @return the value of cm_cust_bad_record.CREATE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.CREATE_DATE
     *
     * @param createDate the value for cm_cust_bad_record.CREATE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.DONE_DATE
     *
     * @return the value of cm_cust_bad_record.DONE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.DONE_DATE
     *
     * @param doneDate the value for cm_cust_bad_record.DONE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EFFECTIVE_DATE
     *
     * @return the value of cm_cust_bad_record.EFFECTIVE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for cm_cust_bad_record.EFFECTIVE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.EXPIRE_DATE
     *
     * @return the value of cm_cust_bad_record.EXPIRE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.EXPIRE_DATE
     *
     * @param expireDate the value for cm_cust_bad_record.EXPIRE_DATE
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.REGION_ID
     *
     * @return the value of cm_cust_bad_record.REGION_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.REGION_ID
     *
     * @param regionId the value for cm_cust_bad_record.REGION_ID
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_cust_bad_record.REMARKS
     *
     * @return the value of cm_cust_bad_record.REMARKS
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_cust_bad_record.REMARKS
     *
     * @param remarks the value for cm_cust_bad_record.REMARKS
     *
     * @mbg.generated Tue May 28 20:10:50 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}