package com.aii.crm.cm.web.persistence.bo;

import java.util.Date;

public class CmGroupMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.cust_rel_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long custRelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.group_cust_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long groupCustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.member_cust_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long memberCustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.member_name
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.member_type
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long memberType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.member_status
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long memberStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.gender
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.provide_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long provideId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.brand
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.user_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.bill_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private String billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.remarks
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.state
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.create_op_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long createOpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.create_org_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long createOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.op_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.org_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.done_code
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Long doneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.create_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.done_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.effective_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.expire_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_group_member.region_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    private String regionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.cust_rel_id
     *
     * @return the value of cm_group_member.cust_rel_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getCustRelId() {
        return custRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.cust_rel_id
     *
     * @param custRelId the value for cm_group_member.cust_rel_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setCustRelId(Long custRelId) {
        this.custRelId = custRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.group_cust_id
     *
     * @return the value of cm_group_member.group_cust_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getGroupCustId() {
        return groupCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.group_cust_id
     *
     * @param groupCustId the value for cm_group_member.group_cust_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setGroupCustId(Long groupCustId) {
        this.groupCustId = groupCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.member_cust_id
     *
     * @return the value of cm_group_member.member_cust_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getMemberCustId() {
        return memberCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.member_cust_id
     *
     * @param memberCustId the value for cm_group_member.member_cust_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setMemberCustId(Long memberCustId) {
        this.memberCustId = memberCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.member_name
     *
     * @return the value of cm_group_member.member_name
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.member_name
     *
     * @param memberName the value for cm_group_member.member_name
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.member_type
     *
     * @return the value of cm_group_member.member_type
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.member_type
     *
     * @param memberType the value for cm_group_member.member_type
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setMemberType(Long memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.member_status
     *
     * @return the value of cm_group_member.member_status
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getMemberStatus() {
        return memberStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.member_status
     *
     * @param memberStatus the value for cm_group_member.member_status
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setMemberStatus(Long memberStatus) {
        this.memberStatus = memberStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.gender
     *
     * @return the value of cm_group_member.gender
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.gender
     *
     * @param gender the value for cm_group_member.gender
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.provide_id
     *
     * @return the value of cm_group_member.provide_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getProvideId() {
        return provideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.provide_id
     *
     * @param provideId the value for cm_group_member.provide_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setProvideId(Long provideId) {
        this.provideId = provideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.brand
     *
     * @return the value of cm_group_member.brand
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.brand
     *
     * @param brand the value for cm_group_member.brand
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.user_id
     *
     * @return the value of cm_group_member.user_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.user_id
     *
     * @param userId the value for cm_group_member.user_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.bill_id
     *
     * @return the value of cm_group_member.bill_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.bill_id
     *
     * @param billId the value for cm_group_member.bill_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setBillId(String billId) {
        this.billId = billId == null ? null : billId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.remarks
     *
     * @return the value of cm_group_member.remarks
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.remarks
     *
     * @param remarks the value for cm_group_member.remarks
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.state
     *
     * @return the value of cm_group_member.state
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.state
     *
     * @param state the value for cm_group_member.state
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.create_op_id
     *
     * @return the value of cm_group_member.create_op_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getCreateOpId() {
        return createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.create_op_id
     *
     * @param createOpId the value for cm_group_member.create_op_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setCreateOpId(Long createOpId) {
        this.createOpId = createOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.create_org_id
     *
     * @return the value of cm_group_member.create_org_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getCreateOrgId() {
        return createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.create_org_id
     *
     * @param createOrgId the value for cm_group_member.create_org_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setCreateOrgId(Long createOrgId) {
        this.createOrgId = createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.op_id
     *
     * @return the value of cm_group_member.op_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.op_id
     *
     * @param opId the value for cm_group_member.op_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.org_id
     *
     * @return the value of cm_group_member.org_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.org_id
     *
     * @param orgId the value for cm_group_member.org_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.done_code
     *
     * @return the value of cm_group_member.done_code
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Long getDoneCode() {
        return doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.done_code
     *
     * @param doneCode the value for cm_group_member.done_code
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setDoneCode(Long doneCode) {
        this.doneCode = doneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.create_date
     *
     * @return the value of cm_group_member.create_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.create_date
     *
     * @param createDate the value for cm_group_member.create_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.done_date
     *
     * @return the value of cm_group_member.done_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.done_date
     *
     * @param doneDate the value for cm_group_member.done_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.effective_date
     *
     * @return the value of cm_group_member.effective_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.effective_date
     *
     * @param effectiveDate the value for cm_group_member.effective_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.expire_date
     *
     * @return the value of cm_group_member.expire_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.expire_date
     *
     * @param expireDate the value for cm_group_member.expire_date
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_group_member.region_id
     *
     * @return the value of cm_group_member.region_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_group_member.region_id
     *
     * @param regionId the value for cm_group_member.region_id
     *
     * @mbg.generated Tue May 28 20:25:07 CST 2019
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }
}