package com.aii.crm.cache.web.persistence.bo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BsParaDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public BsParaDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRegionIdIsNull() {
            addCriterion("REGION_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNotNull() {
            addCriterion("REGION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegionIdEqualTo(String value) {
            addCriterion("REGION_ID =", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotEqualTo(String value) {
            addCriterion("REGION_ID <>", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThan(String value) {
            addCriterion("REGION_ID >", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGION_ID >=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThan(String value) {
            addCriterion("REGION_ID <", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThanOrEqualTo(String value) {
            addCriterion("REGION_ID <=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLike(String value) {
            addCriterion("REGION_ID like", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotLike(String value) {
            addCriterion("REGION_ID not like", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIn(List<String> values) {
            addCriterion("REGION_ID in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotIn(List<String> values) {
            addCriterion("REGION_ID not in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdBetween(String value1, String value2) {
            addCriterion("REGION_ID between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotBetween(String value1, String value2) {
            addCriterion("REGION_ID not between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andParaTypeIsNull() {
            addCriterion("PARA_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andParaTypeIsNotNull() {
            addCriterion("PARA_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andParaTypeEqualTo(String value) {
            addCriterion("PARA_TYPE =", value, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeNotEqualTo(String value) {
            addCriterion("PARA_TYPE <>", value, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeGreaterThan(String value) {
            addCriterion("PARA_TYPE >", value, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PARA_TYPE >=", value, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeLessThan(String value) {
            addCriterion("PARA_TYPE <", value, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeLessThanOrEqualTo(String value) {
            addCriterion("PARA_TYPE <=", value, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeLike(String value) {
            addCriterion("PARA_TYPE like", value, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeNotLike(String value) {
            addCriterion("PARA_TYPE not like", value, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeIn(List<String> values) {
            addCriterion("PARA_TYPE in", values, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeNotIn(List<String> values) {
            addCriterion("PARA_TYPE not in", values, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeBetween(String value1, String value2) {
            addCriterion("PARA_TYPE between", value1, value2, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaTypeNotBetween(String value1, String value2) {
            addCriterion("PARA_TYPE not between", value1, value2, "paraType");
            return (Criteria) this;
        }

        public Criteria andParaCodeIsNull() {
            addCriterion("PARA_CODE is null");
            return (Criteria) this;
        }

        public Criteria andParaCodeIsNotNull() {
            addCriterion("PARA_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andParaCodeEqualTo(String value) {
            addCriterion("PARA_CODE =", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeNotEqualTo(String value) {
            addCriterion("PARA_CODE <>", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeGreaterThan(String value) {
            addCriterion("PARA_CODE >", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PARA_CODE >=", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeLessThan(String value) {
            addCriterion("PARA_CODE <", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeLessThanOrEqualTo(String value) {
            addCriterion("PARA_CODE <=", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeLike(String value) {
            addCriterion("PARA_CODE like", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeNotLike(String value) {
            addCriterion("PARA_CODE not like", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeIn(List<String> values) {
            addCriterion("PARA_CODE in", values, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeNotIn(List<String> values) {
            addCriterion("PARA_CODE not in", values, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeBetween(String value1, String value2) {
            addCriterion("PARA_CODE between", value1, value2, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeNotBetween(String value1, String value2) {
            addCriterion("PARA_CODE not between", value1, value2, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaNameIsNull() {
            addCriterion("PARA_NAME is null");
            return (Criteria) this;
        }

        public Criteria andParaNameIsNotNull() {
            addCriterion("PARA_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andParaNameEqualTo(String value) {
            addCriterion("PARA_NAME =", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameNotEqualTo(String value) {
            addCriterion("PARA_NAME <>", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameGreaterThan(String value) {
            addCriterion("PARA_NAME >", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameGreaterThanOrEqualTo(String value) {
            addCriterion("PARA_NAME >=", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameLessThan(String value) {
            addCriterion("PARA_NAME <", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameLessThanOrEqualTo(String value) {
            addCriterion("PARA_NAME <=", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameLike(String value) {
            addCriterion("PARA_NAME like", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameNotLike(String value) {
            addCriterion("PARA_NAME not like", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameIn(List<String> values) {
            addCriterion("PARA_NAME in", values, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameNotIn(List<String> values) {
            addCriterion("PARA_NAME not in", values, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameBetween(String value1, String value2) {
            addCriterion("PARA_NAME between", value1, value2, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameNotBetween(String value1, String value2) {
            addCriterion("PARA_NAME not between", value1, value2, "paraName");
            return (Criteria) this;
        }

        public Criteria andPara1IsNull() {
            addCriterion("PARA1 is null");
            return (Criteria) this;
        }

        public Criteria andPara1IsNotNull() {
            addCriterion("PARA1 is not null");
            return (Criteria) this;
        }

        public Criteria andPara1EqualTo(String value) {
            addCriterion("PARA1 =", value, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1NotEqualTo(String value) {
            addCriterion("PARA1 <>", value, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1GreaterThan(String value) {
            addCriterion("PARA1 >", value, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1GreaterThanOrEqualTo(String value) {
            addCriterion("PARA1 >=", value, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1LessThan(String value) {
            addCriterion("PARA1 <", value, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1LessThanOrEqualTo(String value) {
            addCriterion("PARA1 <=", value, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1Like(String value) {
            addCriterion("PARA1 like", value, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1NotLike(String value) {
            addCriterion("PARA1 not like", value, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1In(List<String> values) {
            addCriterion("PARA1 in", values, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1NotIn(List<String> values) {
            addCriterion("PARA1 not in", values, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1Between(String value1, String value2) {
            addCriterion("PARA1 between", value1, value2, "para1");
            return (Criteria) this;
        }

        public Criteria andPara1NotBetween(String value1, String value2) {
            addCriterion("PARA1 not between", value1, value2, "para1");
            return (Criteria) this;
        }

        public Criteria andPara2IsNull() {
            addCriterion("PARA2 is null");
            return (Criteria) this;
        }

        public Criteria andPara2IsNotNull() {
            addCriterion("PARA2 is not null");
            return (Criteria) this;
        }

        public Criteria andPara2EqualTo(String value) {
            addCriterion("PARA2 =", value, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2NotEqualTo(String value) {
            addCriterion("PARA2 <>", value, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2GreaterThan(String value) {
            addCriterion("PARA2 >", value, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2GreaterThanOrEqualTo(String value) {
            addCriterion("PARA2 >=", value, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2LessThan(String value) {
            addCriterion("PARA2 <", value, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2LessThanOrEqualTo(String value) {
            addCriterion("PARA2 <=", value, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2Like(String value) {
            addCriterion("PARA2 like", value, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2NotLike(String value) {
            addCriterion("PARA2 not like", value, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2In(List<String> values) {
            addCriterion("PARA2 in", values, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2NotIn(List<String> values) {
            addCriterion("PARA2 not in", values, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2Between(String value1, String value2) {
            addCriterion("PARA2 between", value1, value2, "para2");
            return (Criteria) this;
        }

        public Criteria andPara2NotBetween(String value1, String value2) {
            addCriterion("PARA2 not between", value1, value2, "para2");
            return (Criteria) this;
        }

        public Criteria andPara3IsNull() {
            addCriterion("PARA3 is null");
            return (Criteria) this;
        }

        public Criteria andPara3IsNotNull() {
            addCriterion("PARA3 is not null");
            return (Criteria) this;
        }

        public Criteria andPara3EqualTo(String value) {
            addCriterion("PARA3 =", value, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3NotEqualTo(String value) {
            addCriterion("PARA3 <>", value, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3GreaterThan(String value) {
            addCriterion("PARA3 >", value, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3GreaterThanOrEqualTo(String value) {
            addCriterion("PARA3 >=", value, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3LessThan(String value) {
            addCriterion("PARA3 <", value, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3LessThanOrEqualTo(String value) {
            addCriterion("PARA3 <=", value, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3Like(String value) {
            addCriterion("PARA3 like", value, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3NotLike(String value) {
            addCriterion("PARA3 not like", value, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3In(List<String> values) {
            addCriterion("PARA3 in", values, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3NotIn(List<String> values) {
            addCriterion("PARA3 not in", values, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3Between(String value1, String value2) {
            addCriterion("PARA3 between", value1, value2, "para3");
            return (Criteria) this;
        }

        public Criteria andPara3NotBetween(String value1, String value2) {
            addCriterion("PARA3 not between", value1, value2, "para3");
            return (Criteria) this;
        }

        public Criteria andPara4IsNull() {
            addCriterion("PARA4 is null");
            return (Criteria) this;
        }

        public Criteria andPara4IsNotNull() {
            addCriterion("PARA4 is not null");
            return (Criteria) this;
        }

        public Criteria andPara4EqualTo(String value) {
            addCriterion("PARA4 =", value, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4NotEqualTo(String value) {
            addCriterion("PARA4 <>", value, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4GreaterThan(String value) {
            addCriterion("PARA4 >", value, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4GreaterThanOrEqualTo(String value) {
            addCriterion("PARA4 >=", value, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4LessThan(String value) {
            addCriterion("PARA4 <", value, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4LessThanOrEqualTo(String value) {
            addCriterion("PARA4 <=", value, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4Like(String value) {
            addCriterion("PARA4 like", value, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4NotLike(String value) {
            addCriterion("PARA4 not like", value, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4In(List<String> values) {
            addCriterion("PARA4 in", values, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4NotIn(List<String> values) {
            addCriterion("PARA4 not in", values, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4Between(String value1, String value2) {
            addCriterion("PARA4 between", value1, value2, "para4");
            return (Criteria) this;
        }

        public Criteria andPara4NotBetween(String value1, String value2) {
            addCriterion("PARA4 not between", value1, value2, "para4");
            return (Criteria) this;
        }

        public Criteria andPara5IsNull() {
            addCriterion("PARA5 is null");
            return (Criteria) this;
        }

        public Criteria andPara5IsNotNull() {
            addCriterion("PARA5 is not null");
            return (Criteria) this;
        }

        public Criteria andPara5EqualTo(String value) {
            addCriterion("PARA5 =", value, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5NotEqualTo(String value) {
            addCriterion("PARA5 <>", value, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5GreaterThan(String value) {
            addCriterion("PARA5 >", value, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5GreaterThanOrEqualTo(String value) {
            addCriterion("PARA5 >=", value, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5LessThan(String value) {
            addCriterion("PARA5 <", value, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5LessThanOrEqualTo(String value) {
            addCriterion("PARA5 <=", value, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5Like(String value) {
            addCriterion("PARA5 like", value, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5NotLike(String value) {
            addCriterion("PARA5 not like", value, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5In(List<String> values) {
            addCriterion("PARA5 in", values, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5NotIn(List<String> values) {
            addCriterion("PARA5 not in", values, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5Between(String value1, String value2) {
            addCriterion("PARA5 between", value1, value2, "para5");
            return (Criteria) this;
        }

        public Criteria andPara5NotBetween(String value1, String value2) {
            addCriterion("PARA5 not between", value1, value2, "para5");
            return (Criteria) this;
        }

        public Criteria andParaDescIsNull() {
            addCriterion("PARA_DESC is null");
            return (Criteria) this;
        }

        public Criteria andParaDescIsNotNull() {
            addCriterion("PARA_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andParaDescEqualTo(String value) {
            addCriterion("PARA_DESC =", value, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescNotEqualTo(String value) {
            addCriterion("PARA_DESC <>", value, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescGreaterThan(String value) {
            addCriterion("PARA_DESC >", value, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescGreaterThanOrEqualTo(String value) {
            addCriterion("PARA_DESC >=", value, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescLessThan(String value) {
            addCriterion("PARA_DESC <", value, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescLessThanOrEqualTo(String value) {
            addCriterion("PARA_DESC <=", value, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescLike(String value) {
            addCriterion("PARA_DESC like", value, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescNotLike(String value) {
            addCriterion("PARA_DESC not like", value, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescIn(List<String> values) {
            addCriterion("PARA_DESC in", values, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescNotIn(List<String> values) {
            addCriterion("PARA_DESC not in", values, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescBetween(String value1, String value2) {
            addCriterion("PARA_DESC between", value1, value2, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andParaDescNotBetween(String value1, String value2) {
            addCriterion("PARA_DESC not between", value1, value2, "paraDesc");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andOpIdIsNull() {
            addCriterion("OP_ID is null");
            return (Criteria) this;
        }

        public Criteria andOpIdIsNotNull() {
            addCriterion("OP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOpIdEqualTo(Long value) {
            addCriterion("OP_ID =", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdNotEqualTo(Long value) {
            addCriterion("OP_ID <>", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdGreaterThan(Long value) {
            addCriterion("OP_ID >", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("OP_ID >=", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdLessThan(Long value) {
            addCriterion("OP_ID <", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdLessThanOrEqualTo(Long value) {
            addCriterion("OP_ID <=", value, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdIn(List<Long> values) {
            addCriterion("OP_ID in", values, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdNotIn(List<Long> values) {
            addCriterion("OP_ID not in", values, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdBetween(Long value1, Long value2) {
            addCriterion("OP_ID between", value1, value2, "opId");
            return (Criteria) this;
        }

        public Criteria andOpIdNotBetween(Long value1, Long value2) {
            addCriterion("OP_ID not between", value1, value2, "opId");
            return (Criteria) this;
        }

        public Criteria andStateDateIsNull() {
            addCriterion("STATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStateDateIsNotNull() {
            addCriterion("STATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateDateEqualTo(Date value) {
            addCriterion("STATE_DATE =", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateNotEqualTo(Date value) {
            addCriterion("STATE_DATE <>", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateGreaterThan(Date value) {
            addCriterion("STATE_DATE >", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("STATE_DATE >=", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateLessThan(Date value) {
            addCriterion("STATE_DATE <", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateLessThanOrEqualTo(Date value) {
            addCriterion("STATE_DATE <=", value, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateIn(List<Date> values) {
            addCriterion("STATE_DATE in", values, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateNotIn(List<Date> values) {
            addCriterion("STATE_DATE not in", values, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateBetween(Date value1, Date value2) {
            addCriterion("STATE_DATE between", value1, value2, "stateDate");
            return (Criteria) this;
        }

        public Criteria andStateDateNotBetween(Date value1, Date value2) {
            addCriterion("STATE_DATE not between", value1, value2, "stateDate");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_para_detail
     *
     * @mbg.generated do_not_delete_during_merge Mon May 20 09:47:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_para_detail
     *
     * @mbg.generated Mon May 20 09:47:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}